import type { LucideIcon } from "lucide-react";
import {
  AtSignIcon,
  BookmarkIcon,
  BriefcaseIcon,
  Building2Icon,
  CakeIcon,
  CalendarIcon,
  CarIcon,
  ClockIcon,
  CreditCardIcon,
  FileTextIcon,
  GiftIcon,
  GlobeIcon,
  HashIcon,
  HeartIcon,
  HomeIcon,
  IdCardIcon,
  LanguagesIcon,
  LinkIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  PhoneIcon,
  ShoppingBagIcon,
  StarIcon,
  TagIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
} from "lucide-react";

/** Maps DB `contact_field_icons.key` values to Lucide components. */
export const CONTACT_FIELD_ICON_MAP: Record<string, LucideIcon> = {
  tag: TagIcon,
  briefcase: BriefcaseIcon,
  globe: GlobeIcon,
  home: HomeIcon,
  car: CarIcon,
  cake: CakeIcon,
  heart: HeartIcon,
  star: StarIcon,
  link: LinkIcon,
  hash: HashIcon,
  bookmark: BookmarkIcon,
  "credit-card": CreditCardIcon,
  "id-card": IdCardIcon,
  "building-2": Building2Icon,
  "map-pin": MapPinIcon,
  calendar: CalendarIcon,
  clock: ClockIcon,
  users: UsersIcon,
  user: UserIcon,
  phone: PhoneIcon,
  mail: MailIcon,
  "message-square": MessageSquareIcon,
  "file-text": FileTextIcon,
  wallet: WalletIcon,
  "shopping-bag": ShoppingBagIcon,
  gift: GiftIcon,
  languages: LanguagesIcon,
  "at-sign": AtSignIcon,
};

export function resolveContactFieldIcon(iconKey: string): LucideIcon {
  return CONTACT_FIELD_ICON_MAP[iconKey] ?? TagIcon;
}
