import {
  INTEGRATION_CHANNEL_LIST,
  MESSAGING_INTEGRATION_CHANNELS,
} from "@/features/integrations/constants";

const channelLabelById = new Map(
  INTEGRATION_CHANNEL_LIST.map((channel) => [channel.id, channel.label]),
);

export const CONTACTS_PAGE_SIZE = 50;

export const CONTACTS_MESSAGES = {
  pageTitle: "CRM",
  pageSubtitle: "Contacts, leads & deals",
  tabContacts: "Contacts",
  tabLeads: "Leads",
  tabDeals: "Deals",
  pageDescription:
    "All contacts across WhatsApp, Instagram, Telegram, and Website Forms.",
  filtersLabel: "Filters",
  segmentsLabel: "Segments",
  searchPlaceholder: "Search by name, phone, or email…",
  searchEmptyTitle: "No matches",
  searchEmptyDescription: "Try a different name, phone number, or email.",
  selectContactTitle: "Select a contact",
  selectContactDescription:
    "Choose a contact from the list or pipeline to view their record.",
  backToList: "Back to contacts",
  previousPage: "Previous",
  nextPage: "Next",
  pageIndicator: (page: number) => `Page ${page}`,
  emptyTitle: "No contacts yet",
  emptyDescription:
    "Connect a channel in Integrations. Contacts appear when customers message you.",
  emptyCta: "Open Integrations",
  filterAll: "All channels",
  profileTitle: "Contact profile",
  showContactProfile: "Show contact profile",
  hideContactProfile: "Hide contact profile",
  workPanelTitle: "Work center",
  createdAtLabel: "Client since",
  lastContactLabel: "Last contact",
  assignedToLabel: "Assigned to",
  messageCountLabel: "Total messages",
  favoriteLabel: "Favorite",
  addToFavorites: "Add to favorites",
  removeFromFavorites: "Remove from favorites",
  messagesTitle: "Recent messages",
  messagesEmpty: "No messages yet.",
  columnStatus: "Status",
  columnTask: "Task",
  columnDue: "Due",
  columnCreated: "Created",
  columnWhen: "When",
  columnChannel: "Channel",
  columnFrom: "From",
  columnPreview: "Preview",
  columnDeal: "Deal",
  columnStage: "Stage",
  columnValue: "Value",
  columnClose: "Close date",
  columnDealStatus: "Status",
  columnPrimary: "Primary",
  columnActions: "Actions",
  dealStatusOpen: "Open",
  dealStatusWon: "Won",
  dealStatusLost: "Lost",
  timelineTitle: "Recent activity",
  timelineEmpty: "No messages yet.",
  openInbox: "Open in Inbox",
  viewInChat: "View in chat",
  lastMessage: "Last message",
  contactsCount: (count: number) =>
    count === 1 ? "1 contact" : `${count} contacts`,
  emailLabel: "Email",
  primaryPhoneLabel: "Phone",
  additionalPhoneLabel: "Additional phone",
  additionalEmailLabel: "Additional email",
  additionalContactsTitle: "Additional contacts",
  addAdditionalContact: "Add contact",
  additionalContactTypeLabel: "Type",
  additionalContactValueLabel: "Value",
  additionalContactLabelField: "Label (optional)",
  additionalContactPhoneType: "Phone",
  additionalContactEmailType: "Email",
  additionalContactSaved: "Additional contact added.",
  additionalContactRemoved: "Additional contact removed.",
  additionalContactSaveFailed: "Unable to save additional contact.",
  additionalContactRemoveFailed: "Unable to remove additional contact.",
  tagsLabel: "Tags",
  tagsHint: "Comma-separated, e.g. hot-lead, vip",
  companyLabel: "Company",
  locationLabel: "Location",
  notesLabel: "Notes",
  pipelineStageLabel: "Pipeline stage",
  editContact: "Edit contact",
  saveContact: "Save changes",
  cancelEdit: "Cancel",
  deleteContact: "Delete contact",
  deleteConfirmTitle: "Delete this contact?",
  deleteConfirmDescription:
    "The contact and linked conversations will be permanently removed.",
  contactSaved: "Contact updated.",
  contactDeleted: "Contact deleted.",
  contactSaveFailed: "Unable to save contact. Please try again.",
  contactDeleteFailed: "Unable to delete contact. Please try again.",
  leadScoreLabel: "Lead score",
  aiSummaryLabel: "AI summary",
  generateInsights: "Generate AI insights",
  generatingInsights: "Analyzing…",
  insightsGenerated: "AI insights updated.",
  insightsFailed: "Unable to generate AI insights. Please try again.",
  insightsUnavailable: "AI insights require Gemini API configuration.",
  internalNoteActivity: "Internal note",
  hotLead: "Hot lead",
  warmLead: "Warm lead",
  coldLead: "Cold lead",
  segmentAll: "All contacts",
  segmentHotLeads: "Hot leads",
  segmentNoReply48h: "No reply 48h+",
  segmentAllLeads: "All leads",
  segmentWarmLeads: "Warm leads",
  segmentStaleLeads: "Stale 48h+",
  leadsEmptyTitle: "No active leads",
  leadsEmptyDescription:
    "Leads are contacts in New, Qualified, or Proposal stages.",
  dealsEmptyTitle: "No deals yet",
  dealsEmptyDescription: "Create a deal and link it to a contact.",
  viewKanban: "Kanban",
  dealsSearchPlaceholder: "Search deals or contacts…",
  newDeal: "New deal",
  selectContactForDeal: "Contact",
  selectContactPlaceholder: "Search contacts…",
  openContact: "Open contact",
  dealDetailTitle: "Deal details",
  dealsCount: (count: number) =>
    count === 1 ? "1 deal" : `${count} deals`,
  viewList: "List",
  viewPipeline: "Pipeline",
  pipelineNew: "New",
  pipelineQualified: "Qualified",
  pipelineProposal: "Proposal",
  pipelineWon: "Won",
  pipelineLost: "Lost",
  pipelineUpdated: "Pipeline stage updated.",
  dealValueLabel: "Deal value",
  dealCurrencyLabel: "Currency",
  expectedCloseLabel: "Expected close",
  tasksTitle: "Tasks",
  tasksEmpty: "No tasks yet. Click + to add one.",
  taskTitleLabel: "Task title",
  taskDueLabel: "Due date",
  taskDueDateLabel: "Due date",
  taskDueTimeLabel: "Due time",
  createTaskTitle: "New task",
  createTaskDescription: "Set a title and optional due date for this contact.",
  addTask: "Add task",
  taskSaved: "Task created.",
  taskDeleted: "Task deleted.",
  taskSaveFailed: "Unable to save task.",
  taskDeleteFailed: "Unable to delete task.",
  deleteTask: "Delete task",
  deleteTaskConfirmTitle: "Delete this task?",
  deleteTaskConfirmDescription:
    "This task will be permanently removed from the contact.",
  taskDone: "Done",
  taskOpen: "Open",
  locationSearchPlaceholder: "Start typing an address…",
  contactInfoTitle: "Contact details",
  sentimentLabel: "Sentiment",
  dealsTitle: "Deals",
  dealsEmpty: "No deals yet. Click + to add one.",
  dealTitleLabel: "Deal title",
  createDealTitle: "New deal",
  createDealDescription:
    "Add deal value, stage, expected close date, and notes.",
  addDeal: "Add deal",
  primaryDeal: "Primary",
  setPrimaryDeal: "Set as primary",
  dealSaved: "Deal saved.",
  dealSaveFailed: "Unable to save deal. Please try again.",
  dealDeleted: "Deal deleted.",
  dealDeleteFailed: "Unable to delete deal.",
  pipelineDragHint: "Drag cards between columns or use the stage menu.",
  dropHere: "Drop to move here",
} as const;

export const CONTACT_SEGMENT_FILTERS = [
  { id: "all" as const, label: CONTACTS_MESSAGES.segmentAll },
  { id: "hot_leads" as const, label: CONTACTS_MESSAGES.segmentHotLeads },
  { id: "no_reply_48h" as const, label: CONTACTS_MESSAGES.segmentNoReply48h },
] as const;

export const LEAD_SEGMENT_FILTERS = [
  { id: "all_leads" as const, label: CONTACTS_MESSAGES.segmentAllLeads },
  { id: "hot_leads" as const, label: CONTACTS_MESSAGES.segmentHotLeads },
  { id: "warm_leads" as const, label: CONTACTS_MESSAGES.segmentWarmLeads },
  { id: "stale_leads" as const, label: CONTACTS_MESSAGES.segmentStaleLeads },
] as const;

export const CONTACT_CHANNEL_FILTERS = [
  { id: null, label: CONTACTS_MESSAGES.filterAll },
  ...MESSAGING_INTEGRATION_CHANNELS.map((channelId) => ({
    id: channelId,
    label: channelLabelById.get(channelId) ?? channelId,
  })),
] as const;
