export const ENV_KEYS = {
  NEXT_PUBLIC_APP_URL: "NEXT_PUBLIC_APP_URL",
  NEXT_PUBLIC_SUPABASE_URL: "NEXT_PUBLIC_SUPABASE_URL",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  SUPABASE_SERVICE_ROLE_KEY: "SUPABASE_SERVICE_ROLE_KEY",
  RESEND_API_KEY: "RESEND_API_KEY",
  RESEND_FROM_EMAIL: "RESEND_FROM_EMAIL",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_DEFAULT_MODEL: "GEMINI_DEFAULT_MODEL",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  WHATSAPP_VERIFY_TOKEN: "WHATSAPP_VERIFY_TOKEN",
  WHATSAPP_APP_SECRET: "WHATSAPP_APP_SECRET",
  WHATSAPP_API_VERSION: "WHATSAPP_API_VERSION",
  NEXT_PUBLIC_META_APP_ID: "NEXT_PUBLIC_META_APP_ID",
  NEXT_PUBLIC_WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID:
    "NEXT_PUBLIC_WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID",
} as const;

export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];

export const REQUIRED_CLIENT_ENV_KEYS = [
  ENV_KEYS.NEXT_PUBLIC_APP_URL,
  ENV_KEYS.NEXT_PUBLIC_SUPABASE_URL,
  ENV_KEYS.NEXT_PUBLIC_SUPABASE_ANON_KEY,
] as const;

export const REQUIRED_SERVER_ENV_KEYS = [
  ENV_KEYS.SUPABASE_SERVICE_ROLE_KEY,
  ENV_KEYS.RESEND_API_KEY,
  ENV_KEYS.RESEND_FROM_EMAIL,
  ENV_KEYS.GEMINI_API_KEY,
] as const;

export const OPTIONAL_SERVER_ENV_KEYS = [
  ENV_KEYS.GEMINI_DEFAULT_MODEL,
  ENV_KEYS.GOOGLE_CLIENT_ID,
  ENV_KEYS.GOOGLE_CLIENT_SECRET,
  ENV_KEYS.WHATSAPP_VERIFY_TOKEN,
  ENV_KEYS.WHATSAPP_APP_SECRET,
  ENV_KEYS.WHATSAPP_API_VERSION,
  ENV_KEYS.NEXT_PUBLIC_META_APP_ID,
  ENV_KEYS.NEXT_PUBLIC_WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID,
] as const;
