import type { LandingLiveEvent } from "@/features/landing/demo/types";

const WHATSAPP_CRM = [
  { id: "wa-contact", label: "Contact linked", detail: "Amina R. · WhatsApp", status: "done" as const },
  { id: "wa-intent", label: "Intent detected", detail: "Booking request", status: "done" as const },
  { id: "wa-booking", label: "Calendar slot reserved", detail: "Tue · 15:30", status: "active" as const },
  { id: "wa-confirm", label: "Confirmation queued", detail: "WhatsApp + SMS", status: "queued" as const },
];

const TELEGRAM_CRM = [
  { id: "tg-contact", label: "Contact updated", detail: "Daniil K. · Telegram", status: "done" as const },
  { id: "tg-task", label: "Task created", detail: "Reschedule consultation", status: "active" as const },
  { id: "tg-note", label: "Note added", detail: "Prefers morning slots", status: "done" as const },
  { id: "tg-handoff", label: "Owner assigned", detail: "Sales · Elena", status: "queued" as const },
];

const EMAIL_CRM = [
  { id: "em-lead", label: "Lead enriched", detail: "Mira Clinic · Email", status: "done" as const },
  { id: "em-deal", label: "Deal opened", detail: "Enterprise discovery", status: "active" as const },
  { id: "em-task", label: "Follow-up task", detail: "Send Pro pricing deck", status: "queued" as const },
  { id: "em-owner", label: "Owner assigned", detail: "Account · Marcus", status: "done" as const },
];

const WEBCHAT_CRM = [
  { id: "wc-visitor", label: "Visitor identified", detail: "Website Chat", status: "done" as const },
  { id: "wc-page", label: "Page context", detail: "/pricing · 4m on page", status: "done" as const },
  { id: "wc-order", label: "Order draft started", detail: "Starter plan inquiry", status: "active" as const },
  { id: "wc-crm", label: "CRM timeline updated", detail: "Live chat · inbound", status: "queued" as const },
];

const VOICE_CRM = [
  { id: "vc-call", label: "Call logged", detail: "Inbound · Calls AI", status: "done" as const },
  { id: "vc-transcript", label: "Transcript saved", detail: "Live capture", status: "active" as const },
  { id: "vc-booking", label: "Booking created", detail: "Wed · 10:30", status: "queued" as const },
  { id: "vc-sms", label: "SMS summary queued", detail: "Post-call follow-up", status: "queued" as const },
];

export const LIVE_DEMO_EVENTS_EN: LandingLiveEvent[] = [
  {
    id: "whatsapp-booking",
    channel: "whatsapp",
    label: "WhatsApp",
    customer: "Amina R.",
    preview: "Can I book a consultation tomorrow after 3?",
    intent: "Booking request",
    deal: "Consultation · qualified",
    nextStep: "Send confirmation",
    callStatus: "No call needed",
    calendar: "Tue 15:30 reserved",
    metric: "12s reply",
    crmActions: WHATSAPP_CRM,
    bookings: [
      {
        id: "b-amina",
        dayIndex: 1,
        time: "15:30",
        title: "Consultation",
        customer: "Amina R.",
        status: "confirmed",
      },
    ],
    messages: [
      { role: "customer", text: "Hi — can I book a consultation tomorrow after 3?" },
      { role: "ai", text: "Of course. I have 15:30 and 16:15 open tomorrow. Which works better?" },
      { role: "customer", text: "15:30 is perfect." },
      { role: "ai", text: "Booked. I’ll send a WhatsApp confirmation and add it to your calendar." },
      { role: "system", text: "CRM: contact linked · calendar slot reserved · confirmation queued" },
      { role: "customer", text: "Can you also note that I prefer video?" },
      { role: "ai", text: "Done — meeting type set to video. Anything else before tomorrow?" },
      { role: "customer", text: "Will I get a reminder?" },
      { role: "ai", text: "Yes — WhatsApp reminder 2 hours before, plus an optional SMS." },
      { role: "customer", text: "Add my assistant Lena to the invite, please." },
      { role: "ai", text: "Lena is on the calendar invite now. You’ll both see the details." },
      { role: "customer", text: "That’s all, thank you!" },
      { role: "ai", text: "You’re set. See you tomorrow at 15:30." },
      { role: "system", text: "Deal stage → Consultation booked · owner: Sales" },
    ],
  },
  {
    id: "telegram-support",
    channel: "telegram",
    label: "Telegram",
    customer: "Daniil K.",
    preview: "Need to move my appointment to the morning",
    intent: "Reschedule",
    deal: "Existing client · warm",
    nextStep: "Confirm new slot",
    callStatus: "Optional callback",
    calendar: "Thu 09:00 proposed",
    metric: "Context kept",
    crmActions: TELEGRAM_CRM,
    bookings: [
      {
        id: "b-daniil",
        dayIndex: 3,
        time: "09:00",
        title: "Reschedule",
        customer: "Daniil K.",
        status: "pending",
      },
    ],
    messages: [
      { role: "customer", text: "Hey, I need to move my appointment to the morning." },
      { role: "ai", text: "I see your consult on Friday 16:00. Morning options: Thu 09:00 or Fri 10:30." },
      { role: "customer", text: "Thursday 9 works." },
      { role: "ai", text: "Moved to Thursday 09:00. Old slot released, confirmation sent on Telegram." },
      { role: "system", text: "CRM: task created · owner Elena · note: prefers morning" },
      { role: "customer", text: "Can someone call me 10 minutes before?" },
      { role: "ai", text: "Yes — reminder call scheduled for 08:50 on Thursday." },
      { role: "customer", text: "Also change the topic to pricing review." },
      { role: "ai", text: "Updated. Calendar title is now “Pricing review · Daniil K.”" },
      { role: "customer", text: "Perfect — thanks!" },
      { role: "ai", text: "You’re all set. Ping me here if plans change." },
      { role: "system", text: "Follow-up task closed · Telegram confirmation delivered" },
    ],
  },
  {
    id: "email-enterprise",
    channel: "email",
    label: "Email",
    customer: "Mira Clinic",
    preview: "Re: Enterprise rollout for three clinics",
    intent: "Enterprise inquiry",
    deal: "Enterprise · priority",
    nextStep: "Share Pro deck",
    callStatus: "Discovery call proposed",
    calendar: "Discovery · Fri 12:00",
    metric: "SLA on track",
    crmActions: EMAIL_CRM,
    bookings: [
      {
        id: "b-mira",
        dayIndex: 4,
        time: "12:00",
        title: "Discovery",
        customer: "Mira Clinic",
        status: "pending",
      },
    ],
    messages: [
      {
        role: "customer",
        text: "Subject: Enterprise rollout — We’re evaluating OrzuX for three clinic locations.",
      },
      {
        role: "ai",
        text: "Thanks for reaching out. Pro covers multi-location inbox, Calls AI, and shared CRM. I can send a short deck and book a discovery call.",
      },
      { role: "customer", text: "Please send pricing for 12 seats and suggest a call this week." },
      {
        role: "ai",
        text: "Deck attached in-thread. Open slots: Thu 15:30 or Fri 12:00. Which should I reserve?",
      },
      { role: "system", text: "CRM: deal opened · owner Marcus · follow-up task queued" },
      { role: "customer", text: "Friday noon works for our ops lead." },
      { role: "ai", text: "Booked Friday 12:00 — calendar invite sent to the thread recipients." },
      { role: "customer", text: "Great, looking forward to it." },
      { role: "ai", text: "We’ll prepare a clinic-focused walkthrough. Reply anytime with questions." },
    ],
  },
  {
    id: "website-chat",
    channel: "website_chat",
    label: "Website Chat",
    customer: "Visitor · Pricing",
    preview: "Do you support WhatsApp + Telegram in one inbox?",
    intent: "Product question",
    deal: "Starter · interest",
    nextStep: "Start trial",
    callStatus: "Not required",
    calendar: "—",
    metric: "On-page AI",
    crmActions: WEBCHAT_CRM,
    messages: [
      { role: "customer", text: "Do you support WhatsApp and Telegram in one inbox?" },
      {
        role: "ai",
        text: "Yes — WhatsApp, Telegram, Website Chat, and Email share one inbox with the same contact record.",
      },
      { role: "customer", text: "And Calls AI?" },
      {
        role: "ai",
        text: "Calls AI answers phone calls, saves transcripts, and can create bookings automatically.",
      },
      { role: "system", text: "CRM: visitor page /pricing · order draft started" },
      { role: "customer", text: "Can I try it without a card?" },
      { role: "ai", text: "Yes — start free from the header. I can also open a guided tour for your team." },
      { role: "customer", text: "Do you sync Google Calendar?" },
      { role: "ai", text: "Yes. Bookings, tasks, and events sync with Google Calendar when connected." },
      { role: "customer", text: "I’ll start free now." },
      { role: "ai", text: "Perfect. Your chat history will sync once you sign in." },
      { role: "system", text: "Lead score ↑ · channel intent: multi-inbox + voice" },
    ],
  },
  {
    id: "ai-calls",
    channel: "voice",
    label: "AI Calls",
    customer: "+49 000 ××××××",
    preview: "Inbound — availability and payment options",
    intent: "Appointment + payment",
    deal: "Inbound call · new",
    nextStep: "SMS summary",
    callStatus: "AI answering",
    calendar: "Wed 10:30 booked",
    metric: "Live call",
    dialNumber: "+49000XXXXXX",
    crmActions: VOICE_CRM,
    bookings: [
      {
        id: "b-call",
        dayIndex: 2,
        time: "10:30",
        title: "Consultation",
        customer: "+49 000 ××××××",
        status: "confirmed",
      },
      {
        id: "b-busy-1",
        dayIndex: 2,
        time: "15:30",
        title: "Busy",
        customer: "",
        status: "busy",
      },
    ],
    messages: [
      { role: "system", text: "Inbound call connected · Calls AI answering" },
      { role: "customer", text: "Hi, I’d like to book a consultation and ask about payment." },
      { role: "ai", text: "I can help. Tomorrow morning or Wednesday 10:30 — which do you prefer?" },
      { role: "customer", text: "Wednesday 10:30." },
      { role: "ai", text: "Reserved. We accept card and invoice. I’ll text a confirmation after the call." },
      { role: "system", text: "CRM: call logged · booking created · SMS summary queued" },
    ],
    callTurns: [
      {
        speaker: "ai",
        text: "Hello, you’ve reached OrzuX. How can I help today?",
      },
      {
        speaker: "customer",
        text: "Hi, I’d like to book a consultation and ask about payment options.",
      },
      {
        speaker: "ai",
        text: "Of course. I have Wednesday at 10:30 open. Does that work for you?",
      },
      { speaker: "customer", text: "Yes, Wednesday 10:30 is fine." },
      {
        speaker: "ai",
        text: "Booked. We accept card and invoice. I’ll send an SMS summary with the details now.",
      },
      { speaker: "customer", text: "Perfect, thank you." },
      { speaker: "ai", text: "You’re welcome. Have a great day." },
    ],
  },
];

export const LIVE_DEMO_EVENTS_RU: LandingLiveEvent[] = [
  {
    id: "whatsapp-booking",
    channel: "whatsapp",
    label: "WhatsApp",
    customer: "Амина Р.",
    preview: "Можно записаться завтра после 15:00?",
    intent: "Запрос на бронь",
    deal: "Консультация · qualified",
    nextStep: "Отправить подтверждение",
    callStatus: "Звонок не нужен",
    calendar: "Вт 15:30 зарезервировано",
    metric: "Ответ 12 сек",
    crmActions: [
      { id: "wa-contact", label: "Контакт связан", detail: "Амина Р. · WhatsApp", status: "done" },
      { id: "wa-intent", label: "Интент определён", detail: "Запрос на бронь", status: "done" },
      { id: "wa-booking", label: "Слот зарезервирован", detail: "Вт · 15:30", status: "active" },
      { id: "wa-confirm", label: "Подтверждение в очереди", detail: "WhatsApp + SMS", status: "queued" },
    ],
    bookings: [
      {
        id: "b-amina",
        dayIndex: 1,
        time: "15:30",
        title: "Консультация",
        customer: "Амина Р.",
        status: "confirmed",
      },
    ],
    messages: [
      { role: "customer", text: "Здравствуйте — можно записаться завтра после 15:00?" },
      { role: "ai", text: "Конечно. Свободны 15:30 и 16:15. Что удобнее?" },
      { role: "customer", text: "15:30 идеально." },
      { role: "ai", text: "Забронировала. Отправлю подтверждение в WhatsApp и добавлю в календарь." },
      { role: "system", text: "CRM: контакт связан · слот зарезервирован · подтверждение в очереди" },
      { role: "customer", text: "Отметьте, пожалуйста, что предпочитаю видео." },
      { role: "ai", text: "Готово — тип встречи: видео. Что-то ещё до завтра?" },
      { role: "customer", text: "Будет напоминание?" },
      { role: "ai", text: "Да — WhatsApp за 2 часа и опционально SMS." },
      { role: "customer", text: "Добавьте ассистента Лену в приглашение." },
      { role: "ai", text: "Лена уже в calendar invite. Оба увидите детали." },
      { role: "customer", text: "Нет, спасибо!" },
      { role: "ai", text: "Отлично. До завтра в 15:30." },
      { role: "system", text: "Сделка → Консультация забронирована · owner: Sales" },
    ],
  },
  {
    id: "telegram-support",
    channel: "telegram",
    label: "Telegram",
    customer: "Даниил К.",
    preview: "Нужно перенести запись на утро",
    intent: "Перенос",
    deal: "Текущий клиент · warm",
    nextStep: "Подтвердить новый слот",
    callStatus: "Опциональный callback",
    calendar: "Чт 09:00 предложено",
    metric: "Контекст сохранён",
    crmActions: [
      { id: "tg-contact", label: "Контакт обновлён", detail: "Даниил К. · Telegram", status: "done" },
      { id: "tg-task", label: "Задача создана", detail: "Перенести консультацию", status: "active" },
      { id: "tg-note", label: "Заметка добавлена", detail: "Предпочитает утро", status: "done" },
      { id: "tg-handoff", label: "Владелец назначен", detail: "Sales · Елена", status: "queued" },
    ],
    bookings: [
      {
        id: "b-daniil",
        dayIndex: 3,
        time: "09:00",
        title: "Перенос",
        customer: "Даниил К.",
        status: "pending",
      },
    ],
    messages: [
      { role: "customer", text: "Нужно перенести запись на утро." },
      { role: "ai", text: "Вижу консультацию в пятницу 16:00. Утро: чт 09:00 или пт 10:30." },
      { role: "customer", text: "Четверг в 9 подходит." },
      { role: "ai", text: "Перенесла на четверг 09:00. Старый слот освобождён, подтверждение в Telegram." },
      { role: "system", text: "CRM: задача создана · владелец Елена · заметка: предпочитает утро" },
      { role: "customer", text: "Можно позвонить за 10 минут?" },
      { role: "ai", text: "Да — напоминание на 08:50 в четверг." },
      { role: "customer", text: "И тему смените на обзор цен." },
      { role: "ai", text: "Готово. В календаре теперь «Обзор цен · Даниил К.»" },
      { role: "customer", text: "Отлично." },
      { role: "ai", text: "Готово. Напишите сюда, если планы изменятся." },
      { role: "system", text: "Follow-up закрыт · Telegram-подтверждение доставлено" },
    ],
  },
  {
    id: "email-enterprise",
    channel: "email",
    label: "Email",
    customer: "Mira Clinic",
    preview: "Re: Внедрение Enterprise на три клиники",
    intent: "Enterprise-запрос",
    deal: "Enterprise · priority",
    nextStep: "Отправить Pro-deck",
    callStatus: "Discovery предложено",
    calendar: "Discovery · Пт 12:00",
    metric: "SLA в норме",
    crmActions: [
      { id: "em-lead", label: "Лид обогащён", detail: "Mira Clinic · Email", status: "done" },
      { id: "em-deal", label: "Сделка открыта", detail: "Enterprise discovery", status: "active" },
      { id: "em-task", label: "Follow-up задача", detail: "Отправить Pro pricing", status: "queued" },
      { id: "em-owner", label: "Владелец назначен", detail: "Account · Marcus", status: "done" },
    ],
    bookings: [
      {
        id: "b-mira",
        dayIndex: 4,
        time: "12:00",
        title: "Discovery",
        customer: "Mira Clinic",
        status: "pending",
      },
    ],
    messages: [
      {
        role: "customer",
        text: "Тема: Enterprise — Рассматриваем OrzuX для трёх клиник.",
      },
      {
        role: "ai",
        text: "Спасибо. Pro закрывает multi-location inbox, Calls AI и общий CRM. Могу отправить deck и забронировать discovery.",
      },
      { role: "customer", text: "Пришлите цену на 12 мест и предложите звонок на этой неделе." },
      {
        role: "ai",
        text: "Deck в треде. Слоты: чт 15:30 или пт 12:00. Какой зарезервировать?",
      },
      { role: "system", text: "CRM: сделка открыта · владелец Marcus · follow-up в очереди" },
      { role: "customer", text: "Пятница в полдень подходит ops-лиду." },
      { role: "ai", text: "Забронировано пятница 12:00 — invite отправлен участникам треда." },
      { role: "customer", text: "Отлично, ждём." },
      { role: "ai", text: "Подготовим walkthrough для клиник. Пишите, если появятся вопросы." },
    ],
  },
  {
    id: "website-chat",
    channel: "website_chat",
    label: "Website Chat",
    customer: "Посетитель · Pricing",
    preview: "WhatsApp и Telegram в одном inbox?",
    intent: "Вопрос о продукте",
    deal: "Starter · interest",
    nextStep: "Начать trial",
    callStatus: "Не требуется",
    calendar: "—",
    metric: "AI на сайте",
    crmActions: [
      { id: "wc-visitor", label: "Посетитель определён", detail: "Website Chat", status: "done" },
      { id: "wc-page", label: "Контекст страницы", detail: "/pricing · 4 мин", status: "done" },
      { id: "wc-order", label: "Черновик заказа", detail: "Запрос Starter", status: "active" },
      { id: "wc-crm", label: "CRM обновлён", detail: "Live chat · inbound", status: "queued" },
    ],
    messages: [
      { role: "customer", text: "Поддерживаете WhatsApp и Telegram в одном inbox?" },
      {
        role: "ai",
        text: "Да — WhatsApp, Telegram, Website Chat и Email в одном inbox с общей карточкой контакта.",
      },
      { role: "customer", text: "А Calls AI?" },
      {
        role: "ai",
        text: "Calls AI отвечает на звонки, сохраняет транскрипт и может создавать бронирования.",
      },
      { role: "system", text: "CRM: страница /pricing · черновик заказа создан" },
      { role: "customer", text: "Можно попробовать без карты?" },
      { role: "ai", text: "Да — Start free в шапке. Могу также открыть тур для команды." },
      { role: "customer", text: "Синхронизируете Google Calendar?" },
      { role: "ai", text: "Да. Брони, задачи и события синхронизируются с Google Calendar." },
      { role: "customer", text: "Начну бесплатно." },
      { role: "ai", text: "Отлично. История чата подтянется после входа." },
      { role: "system", text: "Lead score ↑ · intent: multi-inbox + voice" },
    ],
  },
  {
    id: "ai-calls",
    channel: "voice",
    label: "AI Calls",
    customer: "+49 000 ××××××",
    preview: "Входящий — время и оплата",
    intent: "Запись + оплата",
    deal: "Входящий звонок · new",
    nextStep: "SMS-резюме",
    callStatus: "AI отвечает",
    calendar: "Ср 10:30 забронировано",
    metric: "Живой звонок",
    dialNumber: "+49000XXXXXX",
    crmActions: [
      { id: "vc-call", label: "Звонок записан", detail: "Входящий · Calls AI", status: "done" },
      { id: "vc-transcript", label: "Транскрипт сохранён", detail: "Live capture", status: "active" },
      { id: "vc-booking", label: "Бронь создана", detail: "Ср · 10:30", status: "queued" },
      { id: "vc-sms", label: "SMS-резюме в очереди", detail: "Post-call follow-up", status: "queued" },
    ],
    bookings: [
      {
        id: "b-call",
        dayIndex: 2,
        time: "10:30",
        title: "Консультация",
        customer: "+49 000 ××××××",
        status: "confirmed",
      },
      {
        id: "b-busy-1",
        dayIndex: 2,
        time: "15:30",
        title: "Занято",
        customer: "",
        status: "busy",
      },
    ],
    messages: [
      { role: "system", text: "Входящий звонок · Calls AI отвечает" },
      { role: "customer", text: "Здравствуйте, хочу записаться и узнать про оплату." },
      { role: "ai", text: "Помогу. Завтра утром или среда 10:30 — что удобнее?" },
      { role: "customer", text: "Среда 10:30." },
      { role: "ai", text: "Зарезервировано. Принимаем карту и счёт. После звонка пришлю SMS." },
      { role: "system", text: "CRM: звонок записан · бронь создана · SMS в очереди" },
    ],
    callTurns: [
      { speaker: "ai", text: "Здравствуйте, вы позвонили в OrzuX. Чем могу помочь?" },
      {
        speaker: "customer",
        text: "Хочу записаться на консультацию и узнать варианты оплаты.",
      },
      {
        speaker: "ai",
        text: "Конечно. Свободна среда в 10:30. Подходит?",
      },
      { speaker: "customer", text: "Да, среда 10:30 отлично." },
      {
        speaker: "ai",
        text: "Забронировано. Принимаем карту и счёт. Сейчас отправлю SMS с деталями.",
      },
      { speaker: "customer", text: "Спасибо." },
      { speaker: "ai", text: "Пожалуйста. Хорошего дня." },
    ],
  },
];

export const LIVE_DEMO_EVENTS_UZ: LandingLiveEvent[] = [
  {
    id: "whatsapp-booking",
    channel: "whatsapp",
    label: "WhatsApp",
    customer: "Amina R.",
    preview: "Ertaga soat 15:00 dan keyin yozilsa bo‘ladimi?",
    intent: "Bron so‘rovi",
    deal: "Konsultatsiya · qualified",
    nextStep: "Tasdiq yuborish",
    callStatus: "Qo‘ng‘iroq kerak emas",
    calendar: "Ses 15:30 band",
    metric: "12 soniya javob",
    crmActions: [
      { id: "wa-contact", label: "Kontakt bog‘landi", detail: "Amina R. · WhatsApp", status: "done" },
      { id: "wa-intent", label: "Intent aniqlandi", detail: "Bron so‘rovi", status: "done" },
      { id: "wa-booking", label: "Slot band qilindi", detail: "Ses · 15:30", status: "active" },
      { id: "wa-confirm", label: "Tasdiq navbatda", detail: "WhatsApp + SMS", status: "queued" },
    ],
    bookings: [
      {
        id: "b-amina",
        dayIndex: 1,
        time: "15:30",
        title: "Konsultatsiya",
        customer: "Amina R.",
        status: "confirmed",
      },
    ],
    messages: [
      { role: "customer", text: "Salom — ertaga soat 15:00 dan keyin yozilsa bo‘ladimi?" },
      { role: "ai", text: "Albatta. 15:30 va 16:15 bo‘sh. Qaysi biri qulay?" },
      { role: "customer", text: "15:30 ajoyib." },
      { role: "ai", text: "Band qildim. WhatsApp tasdig‘ini yuboraman va kalendarga qo‘shaman." },
      { role: "system", text: "CRM: kontakt bog‘landi · slot band · tasdiq navbatda" },
      { role: "customer", text: "Video uchrashuvni belgilab qo‘ying." },
      { role: "ai", text: "Tayyor — uchrashuv turi: video. Yana biror narsa bormi?" },
      { role: "customer", text: "Yo‘q, rahmat!" },
      { role: "ai", text: "Yaxshi. Ertaga 15:30 da ko‘rishamiz." },
    ],
  },
  {
    id: "telegram-support",
    channel: "telegram",
    label: "Telegram",
    customer: "Daniil K.",
    preview: "Uchrashuvni ertalabga ko‘chirmoqchiman",
    intent: "Qayta rejalash",
    deal: "Mavjud mijoz · warm",
    nextStep: "Yangi slotni tasdiqlash",
    callStatus: "Ixtiyoriy callback",
    calendar: "Pay 09:00 taklif",
    metric: "Kontekst saqlandi",
    crmActions: [
      { id: "tg-contact", label: "Kontakt yangilandi", detail: "Daniil K. · Telegram", status: "done" },
      { id: "tg-task", label: "Task yaratildi", detail: "Konsultatsiyani ko‘chirish", status: "active" },
      { id: "tg-note", label: "Izoh qo‘shildi", detail: "Ertalabni afzal ko‘radi", status: "done" },
      { id: "tg-handoff", label: "Owner tayinlandi", detail: "Sales · Elena", status: "queued" },
    ],
    bookings: [
      {
        id: "b-daniil",
        dayIndex: 3,
        time: "09:00",
        title: "Qayta reja",
        customer: "Daniil K.",
        status: "pending",
      },
    ],
    messages: [
      { role: "customer", text: "Uchrashuvni ertalabga ko‘chirmoqchiman." },
      { role: "ai", text: "Juma 16:00 dagi konsultatsiyani ko‘raman. Ertalab: pay 09:00 yoki jum 10:30." },
      { role: "customer", text: "Payshanba 9 bo‘ladi." },
      { role: "ai", text: "Payshanba 09:00 ga ko‘chirdim. Eski slot bo‘shatildi, Telegram tasdig‘i yuborildi." },
      { role: "system", text: "CRM: task yaratildi · owner Elena · izoh: ertalab" },
      { role: "customer", text: "10 daqiqa oldin qo‘ng‘iroq qilsangiz?" },
      { role: "ai", text: "Ha — payshanba 08:50 da eslatma qo‘ng‘irog‘i." },
      { role: "customer", text: "Ajoyib." },
      { role: "ai", text: "Tayyor. Reja o‘zgarsa shu yerdan yozing." },
    ],
  },
  {
    id: "email-enterprise",
    channel: "email",
    label: "Email",
    customer: "Mira Clinic",
    preview: "Re: Uch klinika uchun Enterprise",
    intent: "Enterprise so‘rov",
    deal: "Enterprise · priority",
    nextStep: "Pro deck yuborish",
    callStatus: "Discovery taklif",
    calendar: "Discovery · Jum 12:00",
    metric: "SLA normal",
    crmActions: [
      { id: "em-lead", label: "Lead boyitildi", detail: "Mira Clinic · Email", status: "done" },
      { id: "em-deal", label: "Deal ochildi", detail: "Enterprise discovery", status: "active" },
      { id: "em-task", label: "Follow-up task", detail: "Pro pricing yuborish", status: "queued" },
      { id: "em-owner", label: "Owner tayinlandi", detail: "Account · Marcus", status: "done" },
    ],
    bookings: [
      {
        id: "b-mira",
        dayIndex: 4,
        time: "12:00",
        title: "Discovery",
        customer: "Mira Clinic",
        status: "pending",
      },
    ],
    messages: [
      {
        role: "customer",
        text: "Mavzu: Enterprise — Uch klinika uchun OrzuX ni baholayapmiz.",
      },
      {
        role: "ai",
        text: "Rahmat. Pro multi-location inbox, Calls AI va umumiy CRM ni qamrab oladi. Deck yuborib, discovery bron qilaman.",
      },
      { role: "customer", text: "12 o‘rin uchun narx va shu hafta qo‘ng‘iroq taklif qiling." },
      {
        role: "ai",
        text: "Deck threadda. Slotlar: pay 15:30 yoki jum 12:00. Qaysinini band qilay?",
      },
      { role: "system", text: "CRM: deal ochildi · owner Marcus · follow-up navbatda" },
      { role: "customer", text: "Juma tush ops lead uchun qulay." },
      { role: "ai", text: "Juma 12:00 band — invite thread ishtirokchilariga yuborildi." },
      { role: "customer", text: "Ajoyib." },
      { role: "ai", text: "Klinika walkthrough tayyorlaymiz. Savol bo‘lsa yozing." },
    ],
  },
  {
    id: "website-chat",
    channel: "website_chat",
    label: "Website Chat",
    customer: "Mehmon · Pricing",
    preview: "WhatsApp va Telegram bitta inboxdami?",
    intent: "Mahsulot savoli",
    deal: "Starter · interest",
    nextStep: "Trial boshlash",
    callStatus: "Kerak emas",
    calendar: "—",
    metric: "Saytdagi AI",
    crmActions: [
      { id: "wc-visitor", label: "Mehmon aniqlandi", detail: "Website Chat", status: "done" },
      { id: "wc-page", label: "Sahifa konteksti", detail: "/pricing · 4 daqiqa", status: "done" },
      { id: "wc-order", label: "Buyurtma drafti", detail: "Starter so‘rovi", status: "active" },
      { id: "wc-crm", label: "CRM yangilandi", detail: "Live chat · inbound", status: "queued" },
    ],
    messages: [
      { role: "customer", text: "WhatsApp va Telegram bitta inboxda ishlaydimi?" },
      {
        role: "ai",
        text: "Ha — WhatsApp, Telegram, Website Chat va Email bitta inboxda, bitta kontakt kartasi bilan.",
      },
      { role: "customer", text: "Calls AI chi?" },
      {
        role: "ai",
        text: "Calls AI qo‘ng‘iroqlarga javob beradi, transkript saqlaydi va bron yaratishi mumkin.",
      },
      { role: "system", text: "CRM: /pricing sahifa · buyurtma drafti" },
      { role: "customer", text: "Kartasiz sinab ko‘rish mumkinmi?" },
      { role: "ai", text: "Ha — headerdagi Start free. Jamoa uchun tour ham ochaman." },
      { role: "customer", text: "Bepul boshlayman." },
      { role: "ai", text: "Ajoyib. Login qilgach chat tarixi sync bo‘ladi." },
    ],
  },
  {
    id: "ai-calls",
    channel: "voice",
    label: "AI Calls",
    customer: "+49 000 ××××××",
    preview: "Kiruvchi — vaqt va to‘lov",
    intent: "Yozilish + to‘lov",
    deal: "Kiruvchi qo‘ng‘iroq · new",
    nextStep: "SMS xulosa",
    callStatus: "AI javob bermoqda",
    calendar: "Chor 10:30 band",
    metric: "Jonli qo‘ng‘iroq",
    dialNumber: "+49000XXXXXX",
    crmActions: [
      { id: "vc-call", label: "Qo‘ng‘iroq yozildi", detail: "Kiruvchi · Calls AI", status: "done" },
      { id: "vc-transcript", label: "Transkript saqlandi", detail: "Live capture", status: "active" },
      { id: "vc-booking", label: "Bron yaratildi", detail: "Chor · 10:30", status: "queued" },
      { id: "vc-sms", label: "SMS xulosa navbatda", detail: "Post-call follow-up", status: "queued" },
    ],
    bookings: [
      {
        id: "b-call",
        dayIndex: 2,
        time: "10:30",
        title: "Konsultatsiya",
        customer: "+49 000 ××××××",
        status: "confirmed",
      },
      {
        id: "b-busy-1",
        dayIndex: 2,
        time: "15:30",
        title: "Band",
        customer: "",
        status: "busy",
      },
    ],
    messages: [
      { role: "system", text: "Kiruvchi qo‘ng‘iroq · Calls AI javob bermoqda" },
      { role: "customer", text: "Salom, konsultatsiyaga yozilmoqchiman va to‘lovni so‘ramoqchiman." },
      { role: "ai", text: "Yordam beraman. Ertaga ertalab yoki chorshanba 10:30?" },
      { role: "customer", text: "Chorshanba 10:30." },
      { role: "ai", text: "Band qildim. Karta va invoice qabul qilamiz. Qo‘ng‘iroqdan keyin SMS yuboraman." },
      { role: "system", text: "CRM: qo‘ng‘iroq yozildi · bron yaratildi · SMS navbatda" },
    ],
    callTurns: [
      { speaker: "ai", text: "Assalomu alaykum, OrzuX ga qo‘ng‘iroq qildingiz. Qanday yordam beray?" },
      {
        speaker: "customer",
        text: "Konsultatsiyaga yozilmoqchiman va to‘lov variantlarini bilmoqchiman.",
      },
      {
        speaker: "ai",
        text: "Albatta. Chorshanba soat 10:30 bo‘sh. Mos keladimi?",
      },
      { speaker: "customer", text: "Ha, chorshanba 10:30 bo‘ladi." },
      {
        speaker: "ai",
        text: "Band qildim. Karta va invoice qabul qilamiz. Hozir SMS yuboraman.",
      },
      { speaker: "customer", text: "Rahmat." },
      { speaker: "ai", text: "Marhamat. Yaxshi kun tilayman." },
    ],
  },
];
