/**
 * OrzuAI server secrets that may live in app_secrets.
 * Keep in sync with src/constants/env-keys.ts (server keys only, no NEXT_PUBLIC_*).
 */
export const MIGRATABLE_APP_SECRET_KEYS = [
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
  "GEMINI_API_KEY",
  "GEMINI_DEFAULT_MODEL",
  "OPENAI_API_KEY",
  "ELEVENLABS_API_KEY",
  "ANTHROPIC_API_KEY",
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_PRICE_STARTER",
  "STRIPE_PRICE_PRO",
  "STRIPE_PRICE_AGENCY",
  "TWILIO_ACCOUNT_SID",
  "TWILIO_AUTH_TOKEN",
  "TWILIO_CONNECT_APP_SID",
  "TWILIO_API_KEY_SID",
  "TWILIO_API_KEY_SECRET",
  "TWILIO_TWIML_APP_SID",
  "RETELL_API_KEY",
  "VAPI_API_KEY",
  "GOOGLE_CLIENT_ID",
  "GOOGLE_CLIENT_SECRET",
  "WHATSAPP_VERIFY_TOKEN",
  "WHATSAPP_APP_SECRET",
  "WHATSAPP_API_VERSION",
  "DIALOG360_PARTNER_API_KEY",
  "DIALOG360_PLATFORM_SECRET",
  "DIALOG360_USE_SANDBOX",
  "DIALOG360_API_BASE",
  "INSTAGRAM_VERIFY_TOKEN",
  "TELEGRAM_WEBHOOK_SECRET",
  "CRON_SECRET",
  "GMAIL_PUBSUB_TOPIC",
  "GMAIL_PUBSUB_PUSH_SECRET",
  "MEDIA_CDN_URL",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "QSTASH_TOKEN",
  "QSTASH_CURRENT_SIGNING_KEY",
  "QSTASH_NEXT_SIGNING_KEY",
  "WORKER_CONCURRENCY",
  "PLATFORM_LLM_PROVIDER_QUEUE",
  "VAPID_PRIVATE_KEY",
  "VAPID_SUBJECT",
] as const;

export type MigratableAppSecretKey = (typeof MIGRATABLE_APP_SECRET_KEYS)[number];

const MIGRATABLE_KEY_SET = new Set<string>(MIGRATABLE_APP_SECRET_KEYS);

export function isMigratableAppSecretKey(keyName: string): boolean {
  return MIGRATABLE_KEY_SET.has(keyName.trim());
}
