import type { PresentationThemeId } from "./types";

export type PresentationTheme = {
  id: PresentationThemeId;
  name: string;
  description: string;
  slideBg: string;
  canvasBg: string;
  titleColor: string;
  bodyColor: string;
  accent: string;
  muted: string;
  fontDisplay: string;
  fontBody: string;
  preview: [string, string, string];
};

export const PRESENTATION_THEMES: PresentationTheme[] = [
  {
    id: "midnight",
    name: "Midnight",
    description: "Dark stage, warm gold accents",
    slideBg: "linear-gradient(145deg, #0f1117 0%, #1a1f2e 55%, #12151c 100%)",
    canvasBg: "#0f1117",
    titleColor: "#f5f1e8",
    bodyColor: "#c8c2b6",
    accent: "#e8a54b",
    muted: "#8a857a",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#0f1117", "#e8a54b", "#f5f1e8"],
  },
  {
    id: "ivory",
    name: "Ivory",
    description: "Clean light board for reports",
    slideBg: "linear-gradient(160deg, #fbf8f2 0%, #f3eee4 100%)",
    canvasBg: "#fbf8f2",
    titleColor: "#1c1915",
    bodyColor: "#4a453c",
    accent: "#b45309",
    muted: "#8a8276",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#fbf8f2", "#b45309", "#1c1915"],
  },
  {
    id: "ocean",
    name: "Ocean",
    description: "Deep blue product decks",
    slideBg: "linear-gradient(150deg, #071821 0%, #0c2a3a 50%, #0a1c28 100%)",
    canvasBg: "#071821",
    titleColor: "#e8f4fa",
    bodyColor: "#9fc0d1",
    accent: "#38bdf8",
    muted: "#6b8fa0",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#071821", "#38bdf8", "#e8f4fa"],
  },
  {
    id: "forest",
    name: "Forest",
    description: "Calm green for sustainability",
    slideBg: "linear-gradient(155deg, #0c1510 0%, #15261c 60%, #0e1913 100%)",
    canvasBg: "#0c1510",
    titleColor: "#eef6ef",
    bodyColor: "#a8c4ad",
    accent: "#4ade80",
    muted: "#6f8a74",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#0c1510", "#4ade80", "#eef6ef"],
  },
  {
    id: "sunset",
    name: "Sunset",
    description: "Warm gradient pitch decks",
    slideBg: "linear-gradient(135deg, #1a0f14 0%, #3a1a22 45%, #1f1218 100%)",
    canvasBg: "#1a0f14",
    titleColor: "#fff5ee",
    bodyColor: "#e0b8a8",
    accent: "#fb7185",
    muted: "#a07a72",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#1a0f14", "#fb7185", "#fff5ee"],
  },
  {
    id: "graphite",
    name: "Graphite",
    description: "Neutral corporate grayscale",
    slideBg: "linear-gradient(160deg, #18181b 0%, #27272a 100%)",
    canvasBg: "#18181b",
    titleColor: "#fafafa",
    bodyColor: "#a1a1aa",
    accent: "#e4e4e7",
    muted: "#71717a",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#18181b", "#e4e4e7", "#fafafa"],
  },
  {
    id: "rose",
    name: "Rose",
    description: "Soft editorial look",
    slideBg: "linear-gradient(150deg, #1c1216 0%, #2a1820 100%)",
    canvasBg: "#1c1216",
    titleColor: "#fff1f2",
    bodyColor: "#e8c4cb",
    accent: "#f472b6",
    muted: "#9a7380",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#1c1216", "#f472b6", "#fff1f2"],
  },
  {
    id: "slate",
    name: "Slate",
    description: "Cool modern blue-gray",
    slideBg: "linear-gradient(155deg, #0f172a 0%, #1e293b 100%)",
    canvasBg: "#0f172a",
    titleColor: "#f8fafc",
    bodyColor: "#94a3b8",
    accent: "#60a5fa",
    muted: "#64748b",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#0f172a", "#60a5fa", "#f8fafc"],
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Northern lights teal–violet",
    slideBg: "linear-gradient(140deg, #06141a 0%, #0d2430 40%, #1a1530 100%)",
    canvasBg: "#06141a",
    titleColor: "#ecfeff",
    bodyColor: "#a5f3fc",
    accent: "#22d3ee",
    muted: "#67e8f9",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#06141a", "#22d3ee", "#a78bfa"],
  },
  {
    id: "ember",
    name: "Ember",
    description: "Bold fire for keynotes",
    slideBg: "linear-gradient(145deg, #140a08 0%, #2a1210 50%, #1a0c0a 100%)",
    canvasBg: "#140a08",
    titleColor: "#fff7ed",
    bodyColor: "#fdba74",
    accent: "#f97316",
    muted: "#c2410c",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#140a08", "#f97316", "#fff7ed"],
  },
  {
    id: "frost",
    name: "Frost",
    description: "Crisp light winter board",
    slideBg: "linear-gradient(160deg, #f0f7fc 0%, #e2eef8 100%)",
    canvasBg: "#f0f7fc",
    titleColor: "#0f172a",
    bodyColor: "#334155",
    accent: "#0284c7",
    muted: "#64748b",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#f0f7fc", "#0284c7", "#0f172a"],
  },
  {
    id: "orchid",
    name: "Orchid",
    description: "Creative purple decks",
    slideBg: "linear-gradient(150deg, #12081a 0%, #221033 55%, #160b20 100%)",
    canvasBg: "#12081a",
    titleColor: "#faf5ff",
    bodyColor: "#d8b4fe",
    accent: "#c084fc",
    muted: "#a78bfa",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#12081a", "#c084fc", "#faf5ff"],
  },
  {
    id: "ink",
    name: "Ink",
    description: "High-contrast print style",
    slideBg: "linear-gradient(180deg, #fafafa 0%, #f4f4f5 100%)",
    canvasBg: "#fafafa",
    titleColor: "#09090b",
    bodyColor: "#3f3f46",
    accent: "#18181b",
    muted: "#71717a",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#fafafa", "#18181b", "#09090b"],
  },
  {
    id: "sand",
    name: "Sand",
    description: "Warm desert neutrals",
    slideBg: "linear-gradient(155deg, #1c1612 0%, #2a211a 100%)",
    canvasBg: "#1c1612",
    titleColor: "#faf6f0",
    bodyColor: "#d6c4a8",
    accent: "#d4a574",
    muted: "#a89070",
    fontDisplay: "Syne, system-ui, sans-serif",
    fontBody: "DM Sans, system-ui, sans-serif",
    preview: ["#1c1612", "#d4a574", "#faf6f0"],
  },
];

export function getTheme(id: PresentationThemeId): PresentationTheme {
  return PRESENTATION_THEMES.find((t) => t.id === id) ?? PRESENTATION_THEMES[0];
}
