export const AI_ASSISTANT_MESSAGES = {
  pageTitle: "AI",
  pageSubtitle: "Choose how AI supports your customers and your team.",
  pageDescription:
    "Create your business profile to enable the AI Assistant and agents.",
  hubAssistantTitle: "AI Assistant",
  hubAssistantDescription:
    "24/7 customer support on your messaging channels.",
  hubAssistantInfoTitle: "What the AI Assistant does",
  hubAssistantInfoBody:
    "The AI Assistant replies to customers around the clock on WhatsApp, Instagram, and Telegram. It answers questions, shares information from your knowledge base, and keeps conversations moving when your team is offline. Turn it on per channel — no agents required.",
  hubAgentsTitle: "CRM Agents",
  hubAgentsDescription:
    "Background executors that update CRM from customer conversations.",
  hubAgentsInfoTitle: "What CRM Agents do",
  hubAgentsInfoBody:
    "CRM Agents run in the background after the AI Assistant replies. They route intent, create tasks and deals, save notes, and update contacts. Customers always talk to your AI Assistant — not separate chat bots.",
  sectionAssistantTitle: "AI Assistant",
  sectionAssistantSubtitle:
    "Enable 24/7 auto-reply on each connected channel.",
  sectionAgentsTitle: "CRM Agents",
  sectionAgentsSubtitle:
    "Configure background executors for CRM automation — not separate customer chat bots.",
  backToAiHub: "Back to AI",
  tabAssistant: "AI Assistant",
  tabAgents: "CRM Agents",
  assistantTabDescription:
    "Turn the assistant on for each channel. One AI Assistant replies to all customers.",
  assistantReplyEngineNote:
    "Customer replies use your AI Assistant profile with platform AI (Gemini first, then OpenAI or Claude if needed). Per-channel model settings do not apply to inbound auto-reply.",
  assistantContextLimitsNote:
    "Context: rolling conversation summary + last 20 messages (40 on Pro). Knowledge Base uses semantic search when available.",
  assistantEdit: "Edit",
  assistantEditTitle: "AI Assistant settings",
  assistantEditFormDescription:
    "Set how your assistant introduces itself and replies to customers.",
  assistantEditDescription:
    "Name, behavior, and communication style — available in the next update.",
  assistantEditBack: "Back to channels",
  assistantEditSave: "Save assistant",
  assistantEditSaved: "AI Assistant settings saved.",
  assistantNameLabel: "Assistant name",
  assistantNamePlaceholder: "e.g. Anna from Orzu Clinic",
  assistantBehaviorLabel: "Behavior & instructions",
  assistantBehaviorPlaceholder:
    "Describe what your business does and how the assistant should help customers…",
  assistantBehaviorHint:
    "This guides every auto-reply. Add FAQs and policies in Knowledge Base for accuracy.",
  assistantLanguageLabel: "Reply language",
  assistantChannelConnected: "Connected",
  assistantChannelNotConnected: "Not connected",
  assistantConnectChannel: "Connect",
  channelsTitle: "Channels",
  channelAgentActive: "AI agent enabled on this channel",
  channelAgentInactive: "No enabled AI agent on this channel",
  searchPlaceholder: "Search agents…",
  channelsTabDescription:
    "Turn AI auto-reply on or off for each channel. Replies use your AI Assistant profile.",
  channelsSummaryTitle: "Overview",
  channelsSummaryEnabled: (count: number, total: number) =>
    `${count} of ${total} channels active`,
  channelsSummaryAllOff: "AI auto-reply is off on all channels.",
  channelsEnableAll: "Enable all channels",
  channelsDisableAll: "Disable all channels",
  channelsKnowledgeHint:
    "Add FAQs and policies in Knowledge Base so AI answers accurately.",
  channelsAgentsHint:
    "Need CRM routing by intent? Open CRM Agents to configure background executors.",
  newAgent: "New CRM agent",
  wizardTitle: "Create CRM agent",
  wizardSubtitle:
    "Pick a CRM goal, channels, and background AI model. Customers still hear only your AI Assistant.",
  wizardStep1Title: "What should this agent do in CRM?",
  wizardStep1Description:
    "CRM agents do not change customer-facing replies. They run after the AI Assistant and update your CRM.",
  crmAgentsVoiceNotice:
    "All customer messages are answered by AI Assistant. This agent only handles background CRM work.",
  wizardStep2Title: "Where should it work?",
  wizardStep2Description:
    "Select connected channels. Connect new ones in Integrations if needed.",
  wizardStep3Title: "Background AI model",
  wizardStep3Description:
    "Model used for CRM planning and routing — not for customer chat replies.",
  wizardStep4Title: "Review and create",
  wizardStep4Description:
    "Confirm the name, instructions, and routing. Enable when you are ready to go live.",
  wizardBillingPlatformTitle: "OrzuAI Platform AI",
  wizardBillingPlatformDescription: "Included in your plan. No API setup required.",
  wizardBillingPlatformBadge: "Recommended",
  wizardBillingPlatformPoint1: "Ready to use immediately",
  wizardBillingPlatformPoint2: "No usage costs in Analytics",
  wizardBillingOwnTitle: "Your API key",
  wizardBillingOwnDescription:
    "Connect OpenAI, Gemini, or Claude with your own credentials.",
  wizardBillingOwnPoint1: "Use any supported model ID",
  wizardBillingOwnPoint2: "AI costs tracked in Analytics",
  wizardBillingOwnKeyHint:
    "Your key is stored securely and used only for your business account.",
  wizardBillingOwnKeyPending: "API key required on this step",
  wizardStep3NoPlatform:
    "Platform AI is not available in this environment. Connect your own API key to continue.",
  wizardStep3PlatformProviderHint:
    "Select a provider included with OrzuAI.",
  wizardStep3OwnProviderHint:
    "Choose a provider, then enter your API key below.",
  wizardStep3SavingKey: "Saving API key…",
  wizardSavedKeysTitle: "Your saved keys",
  wizardSavedKeysHint: "Select a key you already added. Manage keys in Settings.",
  wizardUseSavedKey: "Using saved key",
  wizardReplaceSavedKey: "Replace key",
  wizardUseForAllAgents: "Use for all agents",
  wizardUseForAllAgentsHint:
    "New agents will default to your API keys. You can change this in Settings.",
  wizardAddNewKey: "Add a new API key",
  wizardBackToGoals: "Back to goals",
  wizardBackToChannels: "Back to channels",
  wizardBackToModel: "Back to AI model",
  wizardContinue: "Continue",
  wizardCreateDraft: "Create as draft",
  wizardCreateAndEnable: "Create & enable",
  wizardAdvancedAi: "AI model (optional)",
  wizardSummaryTitle: "Summary",
  wizardRoutingHint: "Type a sample message to preview routing.",
  wizardChannelConnected: "Connected",
  wizardChannelDisconnected: "Not connected",
  wizardChannelSelect: "Add",
  wizardChannelSelected: "Added",
  wizardNoChannelsConnected:
    "Connect at least one channel in Integrations to enable this agent.",
  wizardPickGoalFirst: "Choose a goal to continue.",
  createAgentTitle: "Create AI agent",
  createAgentDescription:
    "Give your agent a name, choose a role, and select where it should work.",
  agentRole: "Agent role",
  agentRoleHint: "The role sets the starting instructions. You can edit them after creation.",
  createAgentSubmit: "Create agent",
  createAgentCancel: "Cancel",
  creatingAgent: "Creating your agent…",
  creatingAgentHint: "Setting up instructions and channel routing.",
  agentCreatedBannerTitle: "Agent created",
  agentCreatedBannerDescription:
    "Fine-tune instructions, keywords, and routing below. Enable the agent when you are ready to go live.",
  configureAgentTitle: "Agent settings",
  enableAgent: "Enable",
  disableAgent: "Disable",
  agentViewSubtitle: "Background CRM executor configuration.",
  agentSavedSettingsTitle: "Saved settings",
  agentSavedSettingsHint:
    "CRM routing and background AI settings. Customer replies always use AI Assistant.",
  agentStatus: "Status",
  agentDefaultRouting: "Default routing (no keywords)",
  aiProviderLabel: "AI provider",
  aiProviderReady: "API key configured",
  aiProvidersNone: "No AI providers configured. Add API keys to your environment.",
  aiProvidersConfigured: (count: number) =>
    count === 1
      ? "1 provider ready. Choose which one powers this agent."
      : `${count} providers ready. Choose which one powers this agent.`,
  aiProviderMissingEnv: (envKey: string) => `Add ${envKey} to enable`,
  aiProviderPlatformIncluded: "Included with OrzuAI",
  aiProviderOwnKey: "Your API key",
  aiProviderAddOwnKey: "Add your API key in agent settings",
  aiCustomModelLabel: "Use custom model ID",
  aiCustomModelHint:
    "Enter any model ID supported by the provider (e.g. gpt-4.1-mini).",
  aiCustomModelPlaceholder: "e.g. gpt-4o-mini",
  aiCredentialsTitle: "Your AI API keys",
  aiCredentialsDescription:
    "Optional. Add your own keys to use custom models and see AI costs in Analytics.",
  aiCredentialsKeyNameLabel: "Key name",
  aiCredentialsKeyNamePlaceholder: "e.g. Production OpenAI",
  aiCredentialsKeyNameRequired: "Enter a name for this API key.",
  aiCredentialsKeyLabel: "API key",
  aiCredentialsReplaceLabel: "Replace API key",
  aiCredentialsKeyPlaceholder: "sk-…",
  aiCredentialsKeyRequired: "Enter an API key.",
  aiCredentialsSave: "Save key",
  aiCredentialsUpdate: "Update key",
  aiCredentialsRemove: "Remove key",
  aiCredentialsSaved: "API key saved.",
  aiCredentialsRemoved: "API key removed.",
  aiCredentialsSaveFailed: "Unable to save API key.",
  aiCredentialsRemoveFailed: "Unable to remove API key.",
  aiCredentialsConfigured: (preview: string) => `Saved: ${preview}`,
  aiCredentialsNotConfigured: "Not configured",
  aiModelLabel: "AI model",
  aiLanguageLabel: "Reply language",
  sectionAiModel: "AI model & language",
  sectionAiModelHint: "Model for background CRM planning — not customer chat replies.",
  editAgent: "Edit",
  agentAnalytics: "Analytics",
  agentAnalyticsTitle: "AI agent analytics",
  agentAnalyticsClose: "Back to agent",
  agentAnalyticsEmpty: "No CRM activity yet. Stats appear after this agent runs in the background.",
  agentAnalyticsContacts: "Contacts served",
  agentAnalyticsContactsHint: "Contacts where this agent applied CRM actions.",
  agentAnalyticsConversations: "Conversations",
  agentAnalyticsConversationsHint: "Conversations where this agent ran CRM automation.",
  agentAnalyticsTotalReplies: "CRM runs",
  agentAnalyticsTotalRepliesHint: "Background CRM runs logged for this agent.",
  agentAnalyticsLast7Days: "Last 7 days",
  agentAnalyticsLast30DaysCount: (count: number) => `${count} in the last 30 days`,
  agentAnalyticsAvgPerContact: "Avg replies per contact",
  agentAnalyticsAvgPerConversation: "Avg replies per conversation",
  agentAnalyticsClientMessages: "Customer messages",
  agentAnalyticsClientMessagesHint: "Incoming messages in conversations handled by this agent.",
  agentAnalyticsHumanReplies: "Human replies",
  agentAnalyticsHumanRepliesHint: "Owner replies in the same conversations.",
  agentAnalyticsActivityTitle: "Reply activity",
  agentAnalyticsActivityHint: "AI replies per day over the last 14 days.",
  agentAnalyticsByChannel: "Performance by channel",
  agentAnalyticsTimeline: "Activity timeline",
  agentAnalyticsFirstReply: "First reply",
  agentAnalyticsLastReply: "Last reply",
  editAgentTitle: "Edit agent",
  editCancel: "Cancel",
  deleteAgent: "Delete",
  deleteAgentConfirmTitle: "Delete this agent?",
  deleteAgentConfirmDescription:
    "This cannot be undone. The agent will stop handling messages on its channels immediately.",
  deleteAgentConfirmCancel: "Cancel",
  wizardAddChannel: "Add new channel",
  communicationStyleLabel: "Communication style",
  communicationStyleHint:
    "Reference tone for CRM planning prompts. Does not change AI Assistant chat voice.",
  agentIconLabel: "Agent icon",
  agentIconHint: "Pick an icon to recognize this agent in the list.",
  sectionInstructions: "Instructions",
  sectionRouting: "Channels & routing",
  selectAgent: "Select an agent from the list or create a new one.",
  noAgents: "No agents yet. Create your first agent for this channel.",
  noAgentsFiltered: "No agents match your search.",
  agentEnabled: "Active",
  agentDisabled: "Paused",
  agentUpdated: "AI agent updated.",
  globalTitle: "Defaults for all channels",
  globalDescription:
    "Apply the same model, language, and instructions to WhatsApp, Instagram, and Telegram at once. You can still customize each channel afterward.",
  globalApply: "Apply to all channels",
  globalApplied: "Defaults applied to all channels.",
  channelNotConnected:
    "This channel is not connected yet. AI settings are saved, but auto-replies start after you connect the channel in Integrations.",
  goToIntegrations: "Connect channel",
  agentBuilderTitle: "Agent editor",
  agentBuilderDescription:
    "CRM agents route intent and update CRM in the background. AI Assistant handles every customer reply.",
  agentName: "Agent name",
  agentPrompt: "CRM instructions",
  agentChannels: "Active channels",
  agentTriggers: "Trigger keywords (comma-separated)",
  agentTriggersHint:
    "Leave empty only if this agent is the main default for its channels. Each channel allows one default agent.",
  agentDefaultBadge: "Default",
  agentSpecialistBadge: "Specialist",
  agentDefaultSummary: "Default · handles unmatched messages",
  agentRoutingConflictTitle: "Routing conflict",
  agentRoutingRuleHint:
    "Each channel has one default CRM agent (no keywords). Add keywords for specialized CRM routing.",
  agentKeywordsRequiredHint:
    "A default agent already exists on this channel. Add keywords to create a specialist agent.",
  agentCreate: "Create agent",
  agentSave: "Save changes",
  agentSaved: "AI agent saved.",
  agentDeleted: "AI agent deleted.",
  saveFailed: "Unable to save agent. Please try again.",
  deleteFailed: "Unable to delete agent. Please try again.",
  testMatchTitle: "Routing preview",
  testMatchHint:
    "Live messages use AI intent matching first; keywords are a fallback.",
  testMatchAgent: (name: string) => `Matched agent: ${name}`,
  testMatchFallback:
    "No agent match — the AI Assistant profile will handle the reply.",
  testMessage: "Sample customer message",
  testRun: "Preview routing",
  usageTitle: "AI usage limits",
  usageDescription:
    "Monthly AI reply quota for your subscription plan. Resets on the first day of each month.",
  salesAgentTitle: "AI Sales Agent (BANT)",
  salesAgentDescription:
    "Score Budget, Authority, Need, and Timeline on incoming messages. High scores can auto-move leads to Qualified.",
  salesAgentEnabled: "Enable BANT qualification on new customer messages",
  bantThresholdLabel: "Qualification threshold (0–100)",
  autoQualifyLabel: "Auto-move to Qualified pipeline when score exceeds threshold",
  salesAgentSave: "Save sales agent rules",
  salesAgentSaved: "Sales agent rules saved.",
  autoTaskEnabled: "Auto-create CRM task on high-intent messages",
  autoTaskThresholdLabel: "Intent threshold (0–100)",
  sentimentEnabled: "Analyze sentiment on incoming messages",
  followUpAgentTitle: "Follow-up Agent",
  followUpAgentDescription:
    "Automatically send AI follow-ups at 24h and 48h when customers stop replying.",
  followUpAgentEnabled: "Enable automatic follow-up messages",
  followUpAgentSaved: "Follow-up agent settings saved.",
  followUpAgentStats: (count: number) =>
    count === 1 ? "1 follow-up sent so far." : `${count} follow-ups sent so far.`,
  channelsIntro:
    "Channel toggles control AI Assistant auto-reply only. Customer voice and language come from AI Assistant settings.",
  save: "Save",
} as const;
