export const AI_ASSISTANT_MESSAGES = {
  pageTitle: "AI Agents",
  pageSubtitle: "Build agents, route by keywords, and customize replies per channel.",
  pageDescription:
    "Create AI agents with custom prompts, communication style, and keyword routing.",
  channelsTitle: "Channels",
  channelAgentActive: "AI agent enabled on this channel",
  channelAgentInactive: "No enabled AI agent on this channel",
  searchPlaceholder: "Search agents…",
  tabAgents: "Agents",
  newAgent: "New agent",
  wizardTitle: "Create AI agent",
  wizardSubtitle: "Set a goal, choose channels, and review before going live.",
  wizardStep1Title: "What should this agent do?",
  wizardStep1Description:
    "Pick the main job for this agent. You can fine-tune instructions on the last step.",
  wizardStep2Title: "Where should it work?",
  wizardStep2Description:
    "Select connected channels. Connect new ones in Integrations if needed.",
  wizardStep3Title: "Review and create",
  wizardStep3Description:
    "Confirm the name, instructions, and routing. Enable when you are ready to go live.",
  wizardBackToGoals: "Back to goals",
  wizardBackToChannels: "Back to channels",
  wizardContinue: "Continue",
  wizardCreateDraft: "Create as draft",
  wizardCreateAndEnable: "Create & enable",
  wizardAdvancedAi: "AI model (optional)",
  wizardSummaryTitle: "Summary",
  wizardRoutingHint: "Type a sample message to preview routing.",
  wizardChannelConnected: "Connected",
  wizardChannelDisconnected: "Not connected",
  wizardChannelSelect: "Add",
  wizardChannelSelected: "Added",
  wizardNoChannelsConnected:
    "Connect at least one channel in Integrations to enable this agent.",
  wizardPickGoalFirst: "Choose a goal to continue.",
  createAgentTitle: "Create AI agent",
  createAgentDescription:
    "Give your agent a name, choose a role, and select where it should work.",
  agentRole: "Agent role",
  agentRoleHint: "The role sets the starting instructions. You can edit them after creation.",
  createAgentSubmit: "Create agent",
  createAgentCancel: "Cancel",
  creatingAgent: "Creating your agent…",
  creatingAgentHint: "Setting up instructions and channel routing.",
  agentCreatedBannerTitle: "Agent created",
  agentCreatedBannerDescription:
    "Fine-tune instructions, keywords, and routing below. Enable the agent when you are ready to go live.",
  configureAgentTitle: "Agent settings",
  enableAgent: "Enable",
  disableAgent: "Disable",
  agentViewSubtitle: "Saved configuration for this agent.",
  agentSavedSettingsTitle: "Saved settings",
  agentSavedSettingsHint: "These are the current values stored for this agent.",
  agentStatus: "Status",
  agentDefaultRouting: "Default routing (no keywords)",
  aiProviderLabel: "AI provider",
  aiProviderReady: "API key configured",
  aiProvidersNone: "No AI providers configured. Add API keys to your environment.",
  aiProvidersConfigured: (count: number) =>
    count === 1
      ? "1 provider ready. Choose which one powers this agent."
      : `${count} providers ready. Choose which one powers this agent.`,
  aiProviderMissingEnv: (envKey: string) => `Add ${envKey} to enable`,
  aiModelLabel: "AI model",
  aiLanguageLabel: "Reply language",
  sectionAiModel: "AI model & language",
  sectionAiModelHint: "Choose which AI powers this agent's replies.",
  editAgent: "Edit",
  agentAnalytics: "Analytics",
  agentAnalyticsTitle: "AI agent analytics",
  agentAnalyticsClose: "Back to agent",
  agentAnalyticsEmpty: "No analytics yet. Stats appear after this agent sends replies.",
  agentAnalyticsContacts: "Contacts served",
  agentAnalyticsContactsHint: "Unique customers who received replies from this agent.",
  agentAnalyticsConversations: "Conversations",
  agentAnalyticsConversationsHint: "Chats where this agent sent at least one reply.",
  agentAnalyticsTotalReplies: "AI replies",
  agentAnalyticsTotalRepliesHint: "Total messages sent by this agent.",
  agentAnalyticsLast7Days: "Last 7 days",
  agentAnalyticsLast30DaysCount: (count: number) => `${count} in the last 30 days`,
  agentAnalyticsAvgPerContact: "Avg replies per contact",
  agentAnalyticsAvgPerConversation: "Avg replies per conversation",
  agentAnalyticsClientMessages: "Customer messages",
  agentAnalyticsClientMessagesHint: "Incoming messages in conversations handled by this agent.",
  agentAnalyticsHumanReplies: "Human replies",
  agentAnalyticsHumanRepliesHint: "Owner replies in the same conversations.",
  agentAnalyticsActivityTitle: "Reply activity",
  agentAnalyticsActivityHint: "AI replies per day over the last 14 days.",
  agentAnalyticsByChannel: "Performance by channel",
  agentAnalyticsTimeline: "Activity timeline",
  agentAnalyticsFirstReply: "First reply",
  agentAnalyticsLastReply: "Last reply",
  editAgentTitle: "Edit agent",
  editCancel: "Cancel",
  deleteAgent: "Delete",
  deleteAgentConfirmTitle: "Delete this agent?",
  deleteAgentConfirmDescription:
    "This cannot be undone. The agent will stop handling messages on its channels immediately.",
  deleteAgentConfirmCancel: "Cancel",
  wizardAddChannel: "Add new channel",
  communicationStyleLabel: "Communication style",
  communicationStyleHint:
    "How the agent should sound when replying to customers.",
  agentIconLabel: "Agent icon",
  agentIconHint: "Pick an icon to recognize this agent in the list.",
  sectionInstructions: "Instructions",
  sectionRouting: "Channels & routing",
  selectAgent: "Select an agent from the list or create a new one.",
  noAgents: "No agents yet. Create your first agent for this channel.",
  noAgentsFiltered: "No agents match your search.",
  agentEnabled: "Active",
  agentDisabled: "Paused",
  agentUpdated: "AI agent updated.",
  globalTitle: "Defaults for all channels",
  globalDescription:
    "Apply the same model, language, and instructions to WhatsApp, Instagram, and Telegram at once. You can still customize each channel afterward.",
  globalApply: "Apply to all channels",
  globalApplied: "Defaults applied to all channels.",
  channelNotConnected:
    "This channel is not connected yet. AI settings are saved, but auto-replies start after you connect the channel in Integrations.",
  goToIntegrations: "Connect channel",
  agentBuilderTitle: "Agent editor",
  agentBuilderDescription:
    "Agents override the channel default prompt when keywords match. Leave keywords empty to use an agent as the channel default.",
  agentName: "Agent name",
  agentPrompt: "System prompt",
  agentChannels: "Active channels",
  agentTriggers: "Trigger keywords (comma-separated)",
  agentTriggersHint:
    "Leave empty to use this agent as the default for selected channels.",
  agentCreate: "Create agent",
  agentSave: "Save changes",
  agentSaved: "AI agent saved.",
  agentDeleted: "AI agent deleted.",
  saveFailed: "Unable to save agent. Please try again.",
  deleteFailed: "Unable to delete agent. Please try again.",
  testMatchTitle: "Routing preview",
  testMatchAgent: (name: string) => `Matched agent: ${name}`,
  testMatchFallback: "No agent match — channel default prompt will be used.",
  testMessage: "Sample customer message",
  testRun: "Preview routing",
  usageTitle: "AI usage limits",
  usageDescription:
    "Monthly AI reply quota for your subscription plan. Resets on the first day of each month.",
  salesAgentTitle: "AI Sales Agent (BANT)",
  salesAgentDescription:
    "Score Budget, Authority, Need, and Timeline on incoming messages. High scores can auto-move leads to Qualified.",
  salesAgentEnabled: "Enable BANT qualification on new customer messages",
  bantThresholdLabel: "Qualification threshold (0–100)",
  autoQualifyLabel: "Auto-move to Qualified pipeline when score exceeds threshold",
  salesAgentSave: "Save sales agent rules",
  salesAgentSaved: "Sales agent rules saved.",
  autoTaskEnabled: "Auto-create CRM task on high-intent messages",
  autoTaskThresholdLabel: "Intent threshold (0–100)",
  sentimentEnabled: "Analyze sentiment on incoming messages",
  followUpAgentTitle: "Follow-up Agent",
  followUpAgentDescription:
    "Automatically send AI follow-ups at 24h and 48h when customers stop replying.",
  followUpAgentEnabled: "Enable automatic follow-up messages",
  followUpAgentSaved: "Follow-up agent settings saved.",
  followUpAgentStats: (count: number) =>
    count === 1 ? "1 follow-up sent so far." : `${count} follow-ups sent so far.`,
  channelsIntro:
    "Channel defaults apply when no agent matches. Model and language are shared per channel.",
  save: "Save",
} as const;
