export const CHAT_MESSAGES = {
  pageTitle: "Inbox",
  pageDescription:
    "All channels in one place — open WhatsApp, Instagram, Telegram, or Website Forms inboxes.",
  inboxSubtitle: "All your conversations in one place.",
  monitorTitle: "Overview",
  monitorDescription:
    "Summary of conversations and activity across every connected channel.",
  channelsTitle: "Channels",
  openChannel: "Open inbox",
  viewMonitor: "All channels",
  channelInbox: "Inbox",
  conversationsCount: "conversations",
  messagesToday: "messages",
  notConnectedHint: "Connect this channel in Integrations to receive messages.",
  websiteFormsReplyHint:
    "Website form leads are saved in OrzuX. Replies here are stored in the conversation (no external send).",
  noBusinessTitle: "Create your business profile first",
  noBusinessDescription:
    "Set up your business profile before viewing customer conversations.",
  emptyListTitle: "No conversations yet",
  emptyListDescription:
    "Connect a channel in Integrations and receive customer messages to see them here.",
  selectConversation: "Select a conversation to view message history.",
  whatsappNotConnected:
    "WhatsApp is not connected. Connect it in Integrations to send replies.",
  instagramNotConnected:
    "Instagram is not connected. Connect it in Integrations to send replies.",
  telegramNotConnected:
    "Telegram is not connected. Connect it in Integrations to send replies.",
  websiteFormsNotConnected:
    "Enable Website Forms in Integrations to receive leads here.",
  sendSuccess: "Message sent successfully.",
  sendFailed: "Unable to send message. Please try again.",
  aiEnabledSuccess: "AI auto-replies enabled.",
  aiDisabledSuccess: "AI auto-replies disabled.",
  aiToggleFailed: "Unable to update AI status. Please try again.",
  missingConfig: "Chat services are not configured.",
  genericError: "Something went wrong. Please try again.",
  searchPlaceholder: "Search by name, phone, or message…",
  searchMessagesPlaceholder: "Search messages…",
  aiAutoReply: "AI Auto-Reply",
  allChannelsFilter: "All Channels",
  notificationsLabel: "Notifications",
  contactDetailsTitle: "Contact Details",
  showContactDetails: "Show contact details",
  hideContactDetails: "Hide contact details",
  leadScoreLabel: "Lead Score",
  contactEmailUnavailable: "No email on file",
  contactLocationUnavailable: "No location on file",
  viewInCrm: "View in CRM",
  aiAssistantTitle: "AI Assistant",
  leadSummaryTitle: "Lead Summary",
  leadSummaryEmpty: "No AI summary yet for this contact.",
  generateReply: "Generate Reply",
  suggestedRepliesTitle: "Suggested Replies",
  suggestedRepliesEmpty: "Add quick replies in AI Assistant settings.",
  conversationInfoTitle: "Conversation Info",
  firstContactLabel: "First Contact",
  lastContactLabel: "Last Contact",
  channelLabel: "Channel",
  notAvailable: "—",
  unreadMessage: "Unread message",
  composerReplyTab: "Reply",
  composerNoteTab: "Note",
  composerPlaceholder: "Type your message…",
  sendLabel: "Send message",
  emojiPickerLabel: "Insert emoji",
  attachFileLabel: "Attach file",
  attachNotSupported: "File attachments are not supported yet for this channel.",
  voiceMessageLabel: "Record voice message",
  voiceRecordingLabel: "Recording voice message",
  voiceStopRecording: "Stop",
  voicePreviewTitle: "Voice message preview",
  voiceNotSupported: "Voice recording is not supported in this browser.",
  mediaPreviewTitle: "Attachment preview",
  mediaPreviewHint: "Review your attachment before sending.",
  mediaCaptionLabel: "Caption",
  mediaCaptionPlaceholder: "Add a caption (optional)…",
  mediaFullscreenPreview: "View fullscreen",
  voicePlay: "Play",
  voicePause: "Pause",
  sendAttachment: "Send",
  discardAttachment: "Discard",
  chatFullscreen: "Fullscreen chat",
  chatExitFullscreen: "Exit fullscreen",
  mediaSendSuccess: "Media sent successfully.",
  mediaSendFailed: "Unable to send media. Please try again.",
  mediaInvalidFile: "Choose a valid file to send.",
  mediaFileTooLarge: "File is too large. Maximum size is 16 MB.",
  mediaNotSupportedForChannel:
    "Media is not supported for this channel.",
  mediaLoadFailed: "Unable to load attachment",
  openMediaPreview: "Open attachment preview",
  closeMediaPreview: "Close preview",
  downloadAttachment: "Download file",
  typingLabel: "typing…",
  customerTyping: (name: string) => `${name} is typing…`,
  chatMenuLabel: "Chat actions",
  exportChatScreenshot: "Export chat screenshot",
  exportChatTranscript: "Export chat transcript",
  exportChatSuccess: "Chat export started.",
  exportChatFailed: "Unable to export chat.",
  deleteContactFromChat: "Delete contact",
  loadMoreConversationsShort: "Load more conversations",
  filterAll: "All",
  filterAiHandled: "AI handled",
  filterNeedsHuman: "Needs human",
  filterActive: "Active",
  emptySearchTitle: "No matching conversations",
  emptySearchDescription: "Try a different search term or filter.",
  unifiedInboxTitle: "All channels",
  unifiedInboxDescription:
    "Every conversation across WhatsApp, Instagram, Telegram, and Website Forms.",
  monitorConversationsSummary: (visible: number, total: number) =>
    `${visible} / ${total} ${total === 1 ? "conversation" : "conversations"}`,
  loadMoreConversations: "Load more conversations",
  monitorKpiConversations: "Conversations",
  monitorKpiMessages: "Messages",
  monitorChannelsLabel: "Channels",
  sortLabel: "Sort",
  sortLatest: "Latest",
  sortNeedsReplyFirst: "Needs reply first",
  sortByChannel: "By channel",
  needsAttentionTitle: "Needs attention",
  needsAttentionDescription: "Customers waiting for your reply",
  awaitingReply: "Awaiting reply",
  viewAll: "All",
  viewNeedsReply: "Needs reply",
  viewHighIntent: "High intent",
  highIntentBadge: "Hot lead",
  serverSearchHint: "Search runs across names, phones, and message text.",
  selectConversationOverview: "Select a conversation to preview and reply.",
  internalNotesTitle: "Internal note",
  internalNotesDescription:
    "Visible only to your team. Customers never see this note.",
  internalNotesPlaceholder: "Add context for your team…",
  internalNotesHint: "Use notes for handoffs, follow-ups, and customer context.",
  internalNotesPrivateBadge: "Team only",
  internalNotesSave: "Save note",
  internalNoteSaved: "Internal note saved.",
  statusLabel: "Conversation status",
  statusUpdated: "Conversation status updated.",
  suggestReplyTitle: "AI suggest reply",
  suggestReplyDescription:
    "Generate a draft reply based on conversation history and your knowledge base.",
  suggestReplyButton: "Generate suggestion",
  suggestReplyUse: "Use in reply",
  suggestReplyEmpty: "Click generate to get an AI draft for this conversation.",
  suggestReplyFailed: "Unable to generate a suggestion. Please try again.",
  suggestReplyNoMessages:
    "No customer messages yet. Wait for the customer to write first.",
  crmAssistantTitle: "CRM assistant",
  crmAssistantLoading: "Loading CRM insights…",
  crmSuggestedAction: "Suggested action",
  favoritesTabLabel: "Favorite contacts",
  favoritesEmptyTitle: "No favorite contacts yet",
  favoritesEmptyDescription:
    "Star a contact from any chat to add them here.",
  favoriteAddedTitle: "Added to favorites",
  favoriteAddedDescription: (name: string) =>
    `${name} is now in your favorites.`,
  favoriteRemovedTitle: "Removed from favorites",
  favoriteRemovedDescription: (name: string) =>
    `${name} was removed from your favorites.`,
  favoriteToggleLabel: "Toggle favorite contact",
} as const;

export type ChatInboxFilter = "all" | "ai_handled" | "needs_human" | "active";
export type ChatInboxSort = "latest" | "needs_reply_first" | "channel";
export type ChatInboxQuickView =
  | "all"
  | "needs_reply"
  | "high_intent"
  | "favorites";

export const HIGH_INTENT_LEAD_SCORE = 70;
export const INBOX_PAGE_SIZE = 50;
