export const CHAT_MESSAGES = {
  pageTitle: "Chats",
  pageDescription:
    "All channels in one place — open WhatsApp, Instagram, Telegram, or Website Forms inboxes.",
  inboxSubtitle: "All your conversations in one place.",
  monitorTitle: "Overview",
  monitorDescription:
    "Summary of conversations and activity across every connected channel.",
  channelsTitle: "Channels",
  openChannel: "Open chats",
  viewMonitor: "All channels",
  channelInbox: "Chats",
  conversationsCount: "conversations",
  messagesToday: "messages",
  notConnectedHint: "Connect this channel in Integrations to receive messages.",
  websiteFormsReplyHint:
    "Website form leads are saved in OrzuX. Replies here are stored in the conversation (no external send).",
  noBusinessTitle: "Create your business profile first",
  noBusinessDescription:
    "Set up your business profile before viewing customer conversations.",
  emptyListTitle: "No conversations yet",
  emptyListDescription:
    "Connect a channel in Integrations and receive customer messages to see them here.",
  selectConversation: "Select a conversation to view message history.",
  whatsappNotConnected:
    "WhatsApp is not connected. Connect it in Integrations to send replies.",
  instagramNotConnected:
    "Instagram is not connected. Connect it in Integrations to send replies.",
  telegramNotConnected:
    "Telegram is not connected. Connect it in Integrations to send replies.",
  websiteFormsNotConnected:
    "Enable Website Forms in Integrations to receive leads here.",
  emailNotConnected:
    "Gmail is not connected. Connect it in Integrations to send email replies.",
  outlookNotConnected:
    "Outlook is not connected. Connect it in Integrations to send Outlook replies.",
  emailSubjectLabel: "Subject",
  emailSubjectPlaceholder: "Re: Customer inquiry",
  emailBodyPlaceholder: "Write your email reply…",
  emailReplyAction: "Reply",
  emailDiscardAction: "Discard",
  emailComposeHint: "Reply in this thread",
  emailSendAction: "Send",
  sendSuccess: "Message sent successfully.",
  messageSending: "Sending…",
  messageRead: "Read",
  mediaUploadPreparing: "Preparing upload…",
  mediaUploadCompleting: "Finishing send…",
  messageDeliveryFailed: "Delivery failed",
  sendFailed: "Unable to send message. Please try again.",
  aiEnabledSuccess: "AI auto-replies enabled.",
  aiDisabledSuccess: "AI auto-replies disabled.",
  aiToggleFailed: "Unable to update AI status. Please try again.",
  missingConfig: "Chat services are not configured.",
  genericError: "Something went wrong. Please try again.",
  searchPlaceholder: "Search by name, phone, or message…",
  searchMessagesPlaceholder: "Search messages…",
  addContact: "Add contact",
  addContactTitle: "New email",
  addContactDescription: "Enter the recipient email, verify, then open the conversation.",
  composeWrite: "Write",
  composeWriteMenuTitle: "Write message",
  composeWriteEmail: "Email",
  composeWriteEmailHint: "Start a new email thread",
  addContactNameLabel: "Name (optional)",
  addContactNamePlaceholder: "Contact name",
  addContactWhatsAppLabel: "WhatsApp number",
  addContactWhatsAppPlaceholder: "+998 90 123 45 67",
  addContactTelegramLabel: "Telegram @username or phone",
  addContactTelegramPlaceholder: "@username or phone number",
  addContactEmailLabel: "Email address",
  addContactEmailPlaceholder: "customer@example.com",
  addContactVerify: "Verify",
  addContactWrite: "Write",
  addContactVerifying: "Verifying…",
  addContactOpening: "Opening chat…",
  addContactVerifySuccess: "Contact verified. You can open the chat.",
  addContactVerifyRequired: "Verify the contact before opening the chat.",
  addContactInvalidPhone: "Enter a valid phone number with country code.",
  addContactInvalidEmail: "Enter a valid email address.",
  addContactOwnEmail: "You cannot start a chat with your own connected Gmail address.",
  addContactEmailDomainInvalid: "This email domain does not accept mail (no MX records).",
  addContactTelegramInvalid: "Enter a Telegram @username, user ID, or a known phone number.",
  addContactTelegramNotFound:
    "Telegram user not found. Check the @username or ask them to message your bot first.",
  addContactTelegramPhoneHint:
    "Telegram phone numbers can only be verified after the person has messaged your bot, or use their @username instead.",
  addContactNoChannels: "Connect Gmail in Integrations first.",
  aiAutoReply: "AI Auto-Reply",
  aiAutoReplyToggleLabel: "Toggle AI auto-reply",
  allChannelsFilter: "All Channels",
  notificationsLabel: "Notifications",
  contactDetailsTitle: "Contact Details",
  showContactDetails: "Show contact details",
  hideContactDetails: "Hide contact details",
  leadScoreLabel: "Lead Score",
  contactEmailUnavailable: "No email on file",
  contactLocationUnavailable: "No location on file",
  viewInCrm: "View in CRM",
  editCrm: "Edit CRM",
  saveCrm: "Save CRM",
  crmSaved: "Contact updated.",
  aiAssistantTitle: "AI Assistant",
  leadSummaryTitle: "Lead Summary",
  leadSummaryEmpty: "No AI summary yet for this contact.",
  generateReply: "Generate Reply",
  suggestedRepliesTitle: "Suggested Replies",
  suggestedRepliesEmpty: "Add quick replies in AI Assistant settings.",
  conversationInfoTitle: "Conversation Info",
  firstContactLabel: "First Contact",
  lastContactLabel: "Last Contact",
  channelLabel: "Channel",
  notAvailable: "—",
  unreadMessage: "Unread message",
  unreadDivider: "Unread",
  scrollToBottom: "Scroll to latest",
  newMessagesBelow: (count: number) =>
    count === 1 ? "1 new message" : `${count} new messages`,
  showMoreText: "Read more",
  showLessText: "Show less",
  replyFromYou: "You",
  replyFromAi: "AI",
  messageActionsLabel: "Message actions",
  messageCopy: "Copy",
  messageDeleteForMe: "Delete for me",
  messageCopied: "Copied to clipboard.",
  messageCopyFailed: "Unable to copy message.",
  messageDeleteFailed: "Unable to delete message.",
  messageNotFound: "Message not found.",
  messageDeletedForAll: "This message was deleted",
  composerReplyTab: "Reply",
  composerNoteTab: "Note",
  composerAddNoteLabel: "Add note",
  contactNotesTitle: "Contact notes",
  contactNotesFor: (name: string) => `Notes for ${name}`,
  contactNotesPlaceholder: "Write a note about this contact…",
  contactNotesEmpty: "No notes yet. Tap + to add one.",
  contactNotesUnavailable: "Open a contact conversation to add notes.",
  contactNoteSaved: "Note saved to contact.",
  contactNoteDeleted: "Note deleted.",
  contactNoteDelete: "Delete note",
  composerPlaceholder: "Type your message…",
  sendLabel: "Send message",
  emojiPickerLabel: "Insert emoji",
  attachFileLabel: "Attach file",
  attachNotSupported: "File attachments are not supported yet for this channel.",
  voiceMessageLabel: "Record voice message",
  voiceRecordingLabel: "Recording voice message",
  voiceStopRecording: "Stop",
  voicePreviewTitle: "Voice message preview",
  voiceNotSupported: "Voice recording is not supported in this browser.",
  mediaPreviewTitle: "Attachment preview",
  mediaPreviewHint: "Review your attachment before sending.",
  mediaCaptionLabel: "Caption",
  mediaCaptionPlaceholder: "Add a caption (optional)…",
  mediaFullscreenPreview: "View fullscreen",
  voicePlay: "Play",
  voicePause: "Pause",
  sendAttachment: "Send",
  discardAttachment: "Discard",
  chatFullscreen: "Fullscreen chat",
  chatExitFullscreen: "Exit fullscreen",
  mediaSendSuccess: "Media sent successfully.",
  mediaSendFailed: "Unable to send media. Please try again.",
  mediaInvalidFile: "Choose a valid file to send.",
  mediaFileTooLarge: "File is too large. Maximum size is 16 MB.",
  mediaNotSupportedForChannel:
    "Media is not supported for this channel.",
  mediaLoadFailed: "Unable to load attachment",
  mediaHydratingPhoto: "Downloading photo…",
  mediaHydratingVoice: "Downloading voice message…",
  mediaHydratingVideo: "Downloading video…",
  mediaHydratingFile: "Downloading file…",
  mediaHydrationFailed: "Download failed",
  mediaRetryHydration: "Retry download",
  mediaRetryingHydration: "Retrying…",
  openMediaPreview: "Open attachment preview",
  closeMediaPreview: "Close preview",
  downloadAttachment: "Download file",
  loadMediaAttachment: "Load",
  typingLabel: "typing…",
  replyTypingLabel: "Печатает…",
  customerTyping: (name: string) => `${name} is typing…`,
  autoReplyErrorTitle: "Auto-reply failed",
  autoReplyErrorGeneric: "Could not generate an automatic reply.",
  autoReplyErrorSendFailed:
    "A reply was generated but could not be delivered to the channel.",
  autoReplyErrorAiDisabled: "Auto-reply is off for this channel.",
  autoReplyErrorSettings: "Auto-reply is not configured for this channel.",
  autoReplyErrorQuota:
    "Monthly AI reply limit reached. Open Billing to upgrade or wait until next month.",
  autoReplyErrorDismiss: "Dismiss",
  autoReplyDisabledBanner:
    "AI auto-reply is off for this channel. Enable it in",
  autoReplyDisabledBannerLink: "AI Agent → Channels",
  chatMenuLabel: "Chat actions",
  exportChatScreenshot: "Export chat screenshot",
  exportChatTranscript: "Export chat transcript",
  exportChatSuccess: "Chat export started.",
  exportChatFailed: "Unable to export chat.",
  deleteContactFromChat: "Delete contact",
  loadMoreConversationsShort: "Load more conversations",
  filterAll: "All",
  filterAiHandled: "AI handled",
  filterNeedsHuman: "Needs human",
  filterActive: "Active",
  emptySearchTitle: "No matching conversations",
  emptySearchDescription: "Try a different search term or filter.",
  unifiedInboxTitle: "All channels",
  unifiedInboxDescription:
    "Every conversation across WhatsApp, Instagram, Telegram, and Website Forms.",
  monitorConversationsSummary: (visible: number, total: number) =>
    `${visible} / ${total} ${total === 1 ? "conversation" : "conversations"}`,
  loadMoreConversations: "Load more conversations",
  monitorKpiConversations: "Conversations",
  monitorKpiMessages: "Messages",
  monitorChannelsLabel: "Channels",
  sortLabel: "Sort",
  sortLatest: "Latest",
  sortNeedsReplyFirst: "Needs reply first",
  sortByChannel: "By channel",
  needsAttentionTitle: "Needs attention",
  needsAttentionDescription: "Customers waiting for your reply",
  awaitingReply: "Awaiting reply",
  viewAll: "All",
  channelRailLabel: "Channels",
  channelRailFavorites: "Favorites",
  viewNeedsReply: "Needs reply",
  viewHighIntent: "High intent",
  highIntentBadge: "Hot lead",
  serverSearchHint: "Search runs across names, phones, and message text.",
  selectConversationOverview: "Select a conversation to preview and reply.",
  internalNotesTitle: "Internal note",
  internalNotesDescription:
    "Visible only to your team. Customers never see this note.",
  internalNotesPlaceholder: "Add context for your team…",
  internalNotesHint: "Use notes for handoffs, follow-ups, and customer context.",
  internalNotesPrivateBadge: "Team only",
  internalNotesSave: "Save note",
  internalNotesDelete: "Delete note",
  internalNoteSaved: "Internal note saved.",
  internalNoteDeleted: "Internal note deleted.",
  statusLabel: "Conversation status",
  statusUpdated: "Conversation status updated.",
  suggestReplyTitle: "AI suggest reply",
  suggestReplyDescription:
    "Generate a draft reply based on conversation history and your knowledge base.",
  suggestReplyButton: "Generate suggestion",
  suggestReplyUse: "Use in reply",
  suggestReplyEmpty: "Click generate to get an AI draft for this conversation.",
  suggestReplyFailed: "Unable to generate a suggestion. Please try again.",
  suggestReplyNoMessages:
    "No customer messages yet. Wait for the customer to write first.",
  crmAssistantTitle: "CRM assistant",
  crmAssistantLoading: "Loading CRM insights…",
  crmSuggestedAction: "Suggested action",
  suggestNextAction: "Suggest next action",
  loadOlderMessages: "Load older messages",
  favoritesTabLabel: "Favorite contacts",
  favoritesEmptyTitle: "No favorite contacts yet",
  favoritesEmptyDescription:
    "Star a contact from any chat to add them here.",
  favoriteAddedTitle: "Added to favorites",
  favoriteAddedDescription: (name: string) =>
    `${name} is now in your favorites.`,
  favoriteRemovedTitle: "Removed from favorites",
  favoriteRemovedDescription: (name: string) =>
    `${name} was removed from your favorites.`,
  favoriteToggleLabel: "Toggle favorite contact",
} as const;

export type ChatInboxFilter = "all" | "ai_handled" | "needs_human" | "active";
export type ChatInboxSort = "latest" | "needs_reply_first" | "channel";
export type ChatInboxQuickView =
  | "all"
  | "needs_reply"
  | "high_intent"
  | "favorites";

export const HIGH_INTENT_LEAD_SCORE = 70;
export const INBOX_PAGE_SIZE = 50;
export const CONVERSATION_MESSAGES_PAGE_SIZE = 80;
