export const VOICE_MESSAGES = {
  channelLabel: "AI Voice",
  channelDescription: "AI calls and answers phone leads automatically",
  connectTitle: "Connect AI Voice",
  connectDescription:
    "Enter your business phone number. When someone submits a form on your website, AI will call them to confirm the request.",
  connectedTitle: "AI Voice is active",
  phoneLabel: "Business phone number",
  phonePlaceholder: "+380501234567",
  phoneHint: "International format with country code (E.164), e.g. +1, +380, +49.",
  activateButton: "Activate AI Voice",
  updateButton: "Save number",
  disconnectButton: "Turn off",
  disconnected: "AI Voice turned off.",
  saved: "AI Voice settings saved.",
  saveFailed: "Unable to save settings.",
  noBusinessTitle: "Set up your business first",
  noBusinessDescription:
    "Create your business profile in Settings before connecting AI Voice.",
  platformMissing:
    "Voice service is not available yet. Contact support or try again later.",
  autoCallbackTitle: "Automatic callback after website form",
  autoCallbackDescription:
    "When a lead leaves a phone number on your website form, AI calls within a few minutes to confirm the request.",
  websiteFormsLink: "Connect Website Forms",
  testCallTitle: "Test call",
  testPhoneLabel: "Your phone number",
  testCallButton: "Send test call",
  testCallSent: "Test call queued.",
  testCallFailed: "Unable to place test call.",
  recentCallsTitle: "Recent calls",
  noCalls: "No calls yet.",
  advancedTitle: "Phone line setup (optional)",
  advancedDescription:
    "If you use Twilio or another provider for this number, paste these URLs in your phone settings.",
  webhookInbound: "Inbound calls",
  webhookOutbound: "Outbound calls",
  copy: "Copy",
  copied: "Copied",
  inboundEnabled: "Answer when customers call your number",
  outboundEnabled: "Call customers back",
  aiAssistantHint: "AI Voice is configured in Integrations.",
  openIntegrations: "Open AI Voice integration",
  aiTitle: "AI conversation",
  aiDescription:
    "AI listens and responds on calls using your Knowledge Base and business instructions.",
  aiEnabled: "AI answers on phone calls",
  aiActive: "AI voice assistant active",
  aiInactive: "Static script only (AI off)",
  aiMissing:
    "Add GEMINI_API_KEY (or OpenAI / Claude) to enable AI voice conversations.",
  aiSaved: "AI voice setting updated.",
  aiSaveFailed: "Unable to update AI voice setting.",
  knowledgeHint: "Improve answers in Knowledge Base and AI Agents settings.",
  inboxTabLabel: "Calls",
  inboxEmptyTitle: "No calls yet",
  inboxEmptyDescription: "Inbound and outbound calls will appear here.",
  inboxNotConnectedTitle: "Connect AI Voice",
  inboxNotConnectedDescription:
    "Connect Twilio in Integrations to start receiving and placing calls.",
  inboxOpenIntegrations: "Open AI Voice",
  callOutbound: "Call",
  callOutboundPending: "Calling…",
  callOutboundSuccess: "Call started.",
  callOutboundFailed: "Unable to place call.",
  callModeTitle: "Choose call mode",
  callModeDescription: "How do you want to call {phone}?",
  callModeDescriptionFallback: "How do you want to place this call?",
  callModeAiTitle: "AI Assistant",
  callModeAiDescription:
    "Use the business AI voice assistant, script, knowledge base and CRM context.",
  callModeAiUnavailable:
    "AI Assistant is disabled or missing an AI provider in business voice settings.",
  callModeHumanTitle: "Human Operator",
  callModeHumanDescription:
    "Use the browser phone for a live human conversation without AI.",
  callModeHumanUnavailable:
    "Browser phone is not configured or unavailable for this workspace.",
  callModeAiPromptLabel: "What should the AI do on this call?",
  callModeAiPromptPlaceholder:
    "e.g. confirm delivery, follow up on quote, schedule meeting",
  callModeAiPromptHint:
    "Write a few words — the AI will turn this into a professional conversation.",
  callDetailTitle: "Call transcript",
  callDetailEmpty: "Select a call to view the transcript.",
  callPostCallTitle: "Post-call analysis",
  callPostCallEmpty: "Post-call analysis will appear after the call ends.",
  callSummaryTitle: "Summary",
  callOutcomeTitle: "Outcome",
  callSentimentTitle: "Sentiment",
  callActionItemsTitle: "Action items",
  callEventLogTitle: "Event log",
  callDirectionInbound: "Inbound",
  inboundCallReceived: "Incoming call",
  inboundCallOpen: "Open",
  inboxLoading: "Loading calls…",
  callDirectionOutbound: "Outbound",
  callAiHandled: "AI handled",
  callDuration: "Duration",
  callStatusLabel: "Status",
  callContactLabel: "Contact",
  callPhoneLabel: "Phone",
  callStartedAt: "Started",
  callEndedAt: "Ended",
  callNoTranscript: "No transcript for this call.",
  callTranscriptUser: "Customer",
  callTranscriptAssistant: "AI",
  callFilterAll: "All",
  callFilterInbound: "Inbound",
  callFilterOutbound: "Outbound",
  callFilterMissed: "Missed",
  callLiveBanner: "Live call in progress",
  callLiveBannerDescription: "AI is handling the conversation. Transcript updates automatically.",
  callLiveBadge: "Live",
  callLiveMonitoringTitle: "Live monitoring",
  callLiveMonitoringDescription:
    "Watch status, transcript, recording and handoff readiness in real time.",
  callMonitoringStatus: "Status",
  callMonitoringSpeaker: "Now speaking",
  callMonitoringRecording: "Recording",
  callMonitoringTranscription: "Transcription",
  callMonitoringOperator: "Operator",
  callMonitoringOn: "On",
  callMonitoringOff: "Off",
  callMonitoringReady: "Ready",
  callMonitoringUnavailable: "Unavailable",
  callConferenceParticipantsTitle: "Conference participants",
  callConferenceParticipantUnknown: "participant",
  callConferenceActive: "Active",
  callConferenceHold: "Hold",
  callConferenceResume: "Resume",
  callConferenceMute: "Mute",
  callConferenceUnmute: "Unmute",
  callConferenceMuted: "Muted",
  callConferenceRemove: "Remove",
  callConferenceControlSuccess: "Conference updated.",
  callConferenceControlFailed: "Unable to update conference.",
  softphoneTitle: "Browser phone",
  softphoneGoOnline: "Go online",
  softphoneGoOnlineFirst:
    "Go online first to receive and place browser calls.",
  softphoneUnavailable: "Browser phone is unavailable.",
  softphoneGoOffline: "Go offline",
  softphoneOnlineHint: "Ready for browser calls and inbound when AI is off.",
  softphoneOfflineHint: "Go online to call from your browser or receive inbound calls.",
  softphoneCallInBrowser: "Call in browser",
  softphoneHangUp: "Hang up",
  softphoneMute: "Mute",
  softphoneUnmute: "Unmute",
  softphoneSpeaker: "Speaker",
  softphoneSpeakerOff: "Speaker off",
  softphoneDialpadTitle: "Dial",
  softphoneSearchContacts: "Search contacts",
  softphoneDeleteDigit: "Delete",
  callCardActive: "On call",
  callCardSelected: "Selected call",
  callCardTapToCall: "Tap the green button to call",
  softphoneConnecting: "Connecting…",
  aiCallLive: "AI call in progress…",
  softphoneOnCall: "On call",
  softphoneIncoming: "Incoming call",
  softphoneAccept: "Answer",
  softphoneReject: "Decline",
  softphoneNotConfigured: "Browser calling is not configured. Add Twilio API Key and TwiML App.",
  softphoneError: "Softphone error",
  softphoneRegisterFailed: "Unable to register browser phone.",
  callRecordingTitle: "Call recording",
  callRecordingDownload: "Download",
  callRecordingDelete: "Delete",
  callRecordingDeleteSuccess: "Recording deleted.",
  callRecordingDeleteFailed: "Unable to delete recording.",
  callRecordingDownloadFailed: "Unable to download recording.",
  callRecordingPlay: "Play",
  callRecordingPause: "Pause",
  callRecordingUnavailable: "No recording for this call.",
  callHandoff: "Take over call",
  callHandoffPending: "Transferring…",
  callHandoffSuccess: "Call transferred to browser phone.",
  callHandoffFailed: "Unable to transfer call.",
  callHumanHandled: "Human handled",
  callConversationLink: "Open voice thread",
  callSmsTitle: "SMS",
  callSmsPlaceholder: "Type a text message…",
  callSmsSend: "Send SMS",
  callSmsSending: "Sending…",
  callSmsSuccess: "SMS sent.",
  callSmsFailed: "Unable to send SMS.",
  callHistoryTitle: "Call history",
  callHistoryButton: "Call history",
  callHistoryEmpty: "No calls with this contact yet.",
  callHistoryTotalCalls: "Total calls",
  callHistoryTotalDuration: "Talk time",
  callHistoryCompleted: "Completed",
  callHistoryMissed: "Missed",
  callHistoryMissedLabel: "Missed",
  callQuickActionsSms: "SMS",
  callQuickActionsContact: "Open contact",
  callQuickActionsCall: "Call",
  addContactButton: "Add contact",
  addContactTitle: "Add contact",
  addContactDescription: "Save this number to CRM with name and details.",
  addContactNameLabel: "Name",
  addContactNamePlaceholder: "Contact name",
  addContactPhoneLabel: "Phone",
  addContactEmailLabel: "Email",
  addContactEmailPlaceholder: "email@company.com",
  addContactCompanyLabel: "Company",
  addContactCompanyPlaceholder: "Company name",
  addContactNotesLabel: "Notes",
  addContactNotesPlaceholder: "Optional notes",
  addContactSave: "Save contact",
  addContactSaving: "Saving…",
  addContactSuccess: "Contact saved to CRM.",
  addContactFailed: "Unable to save contact.",
  editContactButton: "Edit contact",
  editContactTitle: "Edit contact",
  editContactDescription: "Changes are saved to CRM immediately.",
  editContactSave: "Save changes",
  editContactSaving: "Saving…",
  editContactSuccess: "Contact updated.",
  editContactFailed: "Unable to update contact.",
  deleteContactButton: "Delete contact",
  deleteContactConfirm: "Delete",
  deleteContactDeleting: "Deleting…",
  deleteContactSuccess: "Contact deleted from CRM.",
  deleteContactFailed: "Unable to delete contact.",
  deleteContactPrompt: "Remove this contact from CRM, voice phonebook, and inbox?",
  deletePhoneHistoryTitle: "Remove number",
  deletePhoneHistoryDescription: "Delete all call history for this number from voice inbox.",
  deletePhoneHistoryButton: "Remove from inbox",
  deletePhoneHistoryPrompt: "Remove all calls with this number from voice inbox?",
  deletePhoneHistorySuccess: "Number removed from inbox.",
  deletePhoneHistoryFailed: "Unable to remove call history.",
  contactsButton: "Contacts",
  contactsTitle: "Phone contacts",
  contactsEmpty: "No contacts with phone numbers yet.",
  contactsOpenDialer: "Open dialer",
  detailsPanelToggle: "Contact details",
  callLineBusy:
    "This phone line is already on a call. Wait for the current call to end.",
  callEnd: "End call",
  callEndPending: "Ending…",
  callEndSuccess: "Call ended.",
  callEndFailed: "Unable to end call.",
  callHold: "Hold",
  callResume: "Resume",
  callTransfer: "Transfer",
  callJoin: "Join",
  callTakeOver: "Take over",
  callListenLive: "Listen live",
  callListenLiveDescription:
    "Open the live monitor to follow the transcript and join when needed.",
  callLiveCardTitle: "Live call",
  callLiveCardCollapse: "Collapse",
  callLiveCardExpand: "Expand",
  callActiveOperator: "Operator",
  callNoOperator: "No operator",
  callMonitorTitle: "Live Call Monitor",
  callMonitorDescription:
    "Monitor active AI and human calls in real time. Transcript updates automatically.",
  callMonitorEmpty: "No active calls right now.",
  callMonitorOpen: "Open monitor",
  callTranscriptLive: "Live transcript",
  callMonitorAudioStart: "Start listening",
  callMonitorAudioStop: "Stop listening",
  callMonitorAudioConnecting: "Connecting live audio…",
  callMonitorAudioListening: "Listening to the call in real time.",
  callMonitorAudioIdle: "Live audio is ready.",
  callMonitorAudioError: "Live audio is unavailable.",
  callMonitorAudioUnavailable: "Live audio is available only during active calls.",
} as const;
