export const VOICE_MESSAGES = {
  channelLabel: "AI Voice",
  channelDescription: "AI calls and answers phone leads automatically",
  connectTitle: "Connect AI Voice",
  connectDescription:
    "Enter your business phone number. When someone submits a form on your website, AI will call them to confirm the request.",
  connectedTitle: "AI Voice is active",
  phoneLabel: "Business phone number",
  phonePlaceholder: "+380501234567",
  phoneHint: "International format with country code (E.164), e.g. +1, +380, +49.",
  activateButton: "Activate AI Voice",
  updateButton: "Save number",
  disconnectButton: "Turn off",
  disconnected: "AI Voice turned off.",
  saved: "AI Voice settings saved.",
  saveFailed: "Unable to save settings.",
  noBusinessTitle: "Set up your business first",
  noBusinessDescription:
    "Create your business profile in Settings before connecting AI Voice.",
  platformMissing:
    "Voice service is not available yet. Contact support or try again later.",
  autoCallbackTitle: "Automatic callback after website form",
  autoCallbackDescription:
    "When a lead leaves a phone number on your website form, AI calls within a few minutes to confirm the request.",
  websiteFormsLink: "Connect Website Forms",
  testCallTitle: "Test call",
  testPhoneLabel: "Your phone number",
  testCallButton: "Send test call",
  testCallSent: "Test call queued.",
  testCallFailed: "Unable to place test call.",
  recentCallsTitle: "Recent calls",
  noCalls: "No calls yet.",
  advancedTitle: "Phone line setup (optional)",
  advancedDescription:
    "If you use Twilio or another provider for this number, paste these URLs in your phone settings.",
  webhookInbound: "Inbound calls",
  webhookOutbound: "Outbound calls",
  copy: "Copy",
  copied: "Copied",
  inboundEnabled: "Answer when customers call your number",
  outboundEnabled: "Call customers back",
  aiAssistantHint: "AI Voice is configured in Integrations.",
  openIntegrations: "Open AI Voice integration",
  aiTitle: "AI conversation",
  aiDescription:
    "AI listens and responds on calls using your Knowledge Base and business instructions.",
  aiEnabled: "AI answers on phone calls",
  aiActive: "AI voice assistant active",
  aiInactive: "Static script only (AI off)",
  aiMissing:
    "Add GEMINI_API_KEY (or OpenAI / Claude) to enable AI voice conversations.",
  aiSaved: "AI voice setting updated.",
  aiSaveFailed: "Unable to update AI voice setting.",
  knowledgeHint: "Improve answers in Knowledge Base and AI Agents settings.",
} as const;
