export const BILLING_MESSAGES = {
  pageTitle: "Billing",
  pageDescription:
    "Manage your plan, payment method, usage, and provider subscriptions.",
  tabOverview: "Overview",
  tabUsage: "Usage & Spending",
  tabInvoices: "Invoices",
  tabPayments: "Payments",
  tabWhatsApp: "WhatsApp",
  tabTwilio: "Twilio",
  paymentMethodTitle: "Payment method",
  paymentMethodDescription: "Default card used for platform subscriptions.",
  paymentMethodEmpty: "No card on file. Upgrade to a paid plan to add one.",
  paymentMethodManage: "Update payment method",
  invoicesTitle: "Invoices",
  invoicesDescription: "Full billing history for your OrzuX account.",
  invoicesEmpty: "No invoices yet.",
  invoicesView: "View details",
  paymentsTitle: "Recent payments",
  paymentsDescription: "Latest charges and subscription payments.",
  serviceCardsTitle: "Provider subscriptions",
  whatsappCardTitle: "WhatsApp",
  whatsappCardDescription: "Usage, estimated spend, and message analytics.",
  twilioCardTitle: "Voice & SMS",
  twilioCardDescription: "OrzuX numbers, minutes, and usage.",
  openService: "Open",
  whatsappPageTitle: "WhatsApp billing",
  whatsappPageDescription:
    "Connection status, message volume, and estimated provider spend.",
  twilioPageTitle: "Voice billing",
  twilioPageDescription:
    "OrzuX phone numbers and usage. Numbers and AI minutes are billed on your OrzuX subscription — no Twilio Connect.",
  connected: "Number active",
  disconnected: "No number yet",
  monthlySpend: "Estimated monthly spend",
  monthlyNumbers: "Phone numbers (monthly)",
  usage30d: "Last 30 days",
  purchaseNumberTitle: "Buy an OrzuX number",
  purchaseNumberDescription:
    "Numbers are purchased on OrzuX telephony and billed monthly on your subscription. Then set call forwarding in Voice settings.",
  countryLabel: "Country",
  areaCodeLabel: "Area code (optional)",
  searchNumbers: "Search numbers",
  buyNumber: "Buy number",
  numberMonthlyPrice: (price: string) => `${price}/mo on your subscription`,
  requiresPaidPlan: "Active paid subscription required to purchase numbers.",
  connectTwilio: "Get OrzuX number",
  twilioGetNumberHint:
    "Get an OrzuX number in Voice settings, then optionally forward your existing business line to it.",
  twilioGetNumberCta: "Open Voice setup",
  twilioBalance: "Available balance",
  twilioBalanceDescription:
    "AI minutes come from your OrzuX plan. Phone number fees are on the subscription.",
  twilioBalanceParentNote: "Platform Twilio balance (OrzuX account).",
  twilioConsoleTopUp: "Open Twilio billing",
  twilioTopUp: "Add funds",
  twilioCreditsDescription:
    "OrzuX usage wallet for platform telephony. Voice minutes also follow your plan entitlements.",
  twilioTopUpFeeNote: (feePercent: number) =>
    `A ${feePercent}% processing fee is added at checkout (covers Stripe fees).`,
  twilioProviderBalance: "Platform Twilio balance",
  twilioBalanceRefresh: "Refresh balance",
  twilioBalanceRefreshing: "Refreshing…",
  twilioVoiceRate: "Voice rate",
  twilioSmsRate: "SMS rate",
  usagePageTitle: "Usage & Spending",
  usagePageDescription:
    "Current consumption, plan limits, forecasts, and service breakdown.",
} as const;
