export const BILLING_MESSAGES = {
  pageTitle: "Billing",
  pageDescription:
    "Manage your plan, payment method, and provider subscriptions.",
  tabOverview: "Overview",
  tabWhatsApp: "WhatsApp",
  tabTwilio: "Twilio",
  paymentMethodTitle: "Payment method",
  paymentMethodDescription: "Default card used for platform subscriptions.",
  paymentMethodEmpty: "No card on file. Upgrade to a paid plan to add one.",
  paymentMethodManage: "Update in Stripe",
  invoicesTitle: "Recent payments",
  invoicesDescription: "Invoices from your OrzuAI subscription.",
  invoicesEmpty: "No invoices yet.",
  invoicesView: "View",
  serviceCardsTitle: "Provider subscriptions",
  whatsappCardTitle: "WhatsApp",
  whatsappCardDescription: "Usage, estimated spend, and message analytics.",
  twilioCardTitle: "Twilio Voice & SMS",
  twilioCardDescription: "Phone numbers, call/SMS usage, and monthly charges.",
  openService: "Open",
  whatsappPageTitle: "WhatsApp billing",
  whatsappPageDescription:
    "Connection status, message volume, and estimated provider spend.",
  twilioPageTitle: "Twilio billing",
  twilioPageDescription:
    "Phone numbers billed monthly through your subscription, plus usage analytics.",
  connected: "Connected",
  disconnected: "Not connected",
  monthlySpend: "Estimated monthly spend",
  monthlyNumbers: "Phone numbers (monthly)",
  usage30d: "Last 30 days",
  purchaseNumberTitle: "Buy a phone number",
  purchaseNumberDescription:
    "Numbers are billed monthly on your OrzuAI subscription.",
  countryLabel: "Country",
  areaCodeLabel: "Area code (optional)",
  searchNumbers: "Search numbers",
  buyNumber: "Buy number",
  numberMonthlyPrice: (price: string) => `${price}/mo on your subscription`,
  requiresPaidPlan: "Active paid subscription required to purchase numbers.",
  connectTwilio: "Connect Twilio",
} as const;
