export const BILLING_MESSAGES = {
  pageTitle: "Billing",
  pageDescription:
    "Manage your plan, payment method, usage, and provider subscriptions.",
  tabOverview: "Overview",
  tabUsage: "Usage & Spending",
  tabInvoices: "Invoices",
  tabPayments: "Payments",
  tabWhatsApp: "WhatsApp",
  tabTwilio: "Twilio",
  paymentMethodTitle: "Payment method",
  paymentMethodDescription: "Default card used for platform subscriptions.",
  paymentMethodEmpty: "No card on file. Upgrade to a paid plan to add one.",
  paymentMethodManage: "Update payment method",
  invoicesTitle: "Invoices",
  invoicesDescription: "Full billing history for your OrzuX account.",
  invoicesEmpty: "No invoices yet.",
  invoicesView: "View details",
  paymentsTitle: "Recent payments",
  paymentsDescription: "Latest charges and subscription payments.",
  serviceCardsTitle: "Provider subscriptions",
  whatsappCardTitle: "WhatsApp",
  whatsappCardDescription: "Usage, estimated spend, and message analytics.",
  twilioCardTitle: "Twilio Voice & SMS",
  twilioCardDescription: "Balance, usage, phone numbers, and charges.",
  openService: "Open",
  whatsappPageTitle: "WhatsApp billing",
  whatsappPageDescription:
    "Connection status, message volume, and estimated provider spend.",
  twilioPageTitle: "Twilio billing",
  twilioPageDescription:
    "Account balance, usage rates, phone numbers, and spending history.",
  connected: "Connected",
  disconnected: "Not connected",
  monthlySpend: "Estimated monthly spend",
  monthlyNumbers: "Phone numbers (monthly)",
  usage30d: "Last 30 days",
  purchaseNumberTitle: "Buy a phone number",
  purchaseNumberDescription:
    "Numbers are billed monthly on your OrzuX subscription.",
  countryLabel: "Country",
  areaCodeLabel: "Area code (optional)",
  searchNumbers: "Search numbers",
  buyNumber: "Buy number",
  numberMonthlyPrice: (price: string) => `${price}/mo on your subscription`,
  requiresPaidPlan: "Active paid subscription required to purchase numbers.",
  connectTwilio: "Connect Twilio",
  twilioBalance: "Available balance",
  twilioBalanceDescription:
    "Voice and SMS usage is billed to your Twilio account. Top up balance in Twilio Console.",
  twilioBalanceParentNote: "Shown from your main Twilio account balance.",
  twilioConsoleTopUp: "Open Twilio billing",
  twilioTopUp: "Add funds",
  twilioCreditsDescription: "OrzuX-managed usage wallet (legacy platform billing).",
  twilioTopUpFeeNote: (feePercent: number) =>
    `A ${feePercent}% processing fee is added at checkout (covers Stripe fees).`,
  twilioProviderBalance: "Twilio provider balance",
  twilioBalanceRefresh: "Refresh balance",
  twilioBalanceRefreshing: "Refreshing…",
  twilioVoiceRate: "Voice rate",
  twilioSmsRate: "SMS rate",
  usagePageTitle: "Usage & Spending",
  usagePageDescription:
    "Current consumption, plan limits, forecasts, and service breakdown.",
} as const;
