export const ANALYTICS_MESSAGES = {
  pageTitle: "Analytics",
  pageDescription:
    "Track conversations, pipeline health, and AI performance across your workspace.",
  tabPulse: "Overview",
  tabChannels: "Channels",
  tabSales: "CRM",
  tabAiOps: "AI",
  period7d: "7 days",
  period30d: "30 days",
  periodAll: "All time",
  pulseTitle: "Overview",
  pulseDescription:
    "Core metrics for the selected period compared to the previous window.",
  pulseNewContacts: "New contacts",
  pulseMessages: "Messages",
  pulseAiReplyShare: "AI reply rate",
  pulseAvgFirstResponse: "Avg first response",
  pulseQualified: "Qualified",
  pulseWonRevenue: "Won revenue",
  pulseDeltaVsPrevious: "vs previous period",
  pulseDeltaUnavailable: "No comparison for all-time view",
  pulseActivityTitle: "Message volume",
  pulseActivityDescription: (days: number) =>
    `Messages per day over the last ${days} day${days === 1 ? "" : "s"}.`,
  attentionTitle: "Needs attention",
  attentionEmpty: "No urgent issues. Metrics update as new activity arrives.",
  attentionOpenInbox: "Open Inbox",
  attentionViewCrm: "View CRM",
  attentionViewAutomations: "View Automations",
  attentionConnectChannel: "Connect channel",
  attentionSlaTitle: (percent: number) =>
    `SLA compliance is ${percent}% — below target`,
  attentionSlaDescription: (minutes: number) =>
    `First replies should land within ${minutes} minutes.`,
  attentionStaleNewTitle: (count: number) =>
    `${count} contact${count === 1 ? "" : "s"} stuck in New for 7+ days`,
  attentionStaleNewDescription:
    "Review pipeline and follow up before leads go cold.",
  attentionChannelDisconnected: (label: string) => `${label} is not connected`,
  attentionAutomationsTitle: (count: number) =>
    `${count} automation run${count === 1 ? "" : "s"} today`,
  attentionNegativeSentimentTitle: (percent: number) =>
    `${percent}% of analyzed contacts are negative`,
  attentionNegativeSentimentDescription:
    "Check unhappy conversations and adjust AI or team follow-up.",
  attentionGettingStartedTitle: "Connect a channel to start tracking",
  attentionGettingStartedDescription:
    "Analytics fills in after your first messages and contacts arrive.",
  comingSoonTitle: "Coming soon",
  channelsPanelTitle: "Channels",
  channelsPanelDescription:
    "Compare volume and AI usage per connected channel.",
  channelsColumnChannel: "Channel",
  channelsColumnMessages: "Messages",
  channelsColumnContacts: "Contacts",
  channelsColumnAiShare: "AI share",
  channelsColumnStatus: "Status",
  channelsStatusConnected: "Connected",
  channelsStatusPending: "Pending",
  channelsStatusDisconnected: "Not connected",
  channelsSelectHint: "Select a channel",
  channelsSelectDescription:
    "Pick a channel to see activity, recent messages, and inbox link.",
  channelsDisconnectedTitle: (label: string) => `${label} is not connected`,
  salesPanelTitle: "CRM & pipeline",
  salesPanelDescription:
    "Lead sources, funnel snapshot, deal value, and customer sentiment.",
  salesStepLeads: "Lead sources",
  salesStepFunnel: "Pipeline funnel",
  salesStepRevenue: "Revenue",
  salesStepSentiment: "Sentiment",
  viewInCrm: "View in CRM",
  viewContacts: (count: number) =>
    `View ${count} contact${count === 1 ? "" : "s"}`,
  viewChannelContacts: (count: number) =>
    `View ${count} contact${count === 1 ? "" : "s"}`,
  aiOpsPanelTitle: "AI performance",
  aiOpsPanelDescription:
    "How AI handles conversations, CRM actions, and automation runs.",
  aiOpsOperationsTitle: "Response performance",
  aiOpsOperationsDescription:
    "AI vs human replies, SLA compliance, and response speed.",
  aiOpsAgentsTitle: "AI agents",
  aiOpsAgentsDescription:
    "Rollup across all agents. Open any row for full per-agent analytics.",
  aiOpsAgentsEmpty: "No AI agents yet. Create one in AI Agents to start tracking replies.",
  aiOpsAgentsColumnName: "Agent",
  aiOpsAgentsColumnStatus: "Status",
  aiOpsAgentsColumnContacts: "Contacts",
  aiOpsAgentsColumnReplies: "AI replies",
  aiOpsAgentsColumnLast7d: "Last 7 days",
  aiOpsAgentOn: "On",
  aiOpsAgentOff: "Off",
  aiOpsViewAgent: "Details",
  aiOpsAutomationsTitle: "Automations",
  aiOpsAutomationsDescription:
    "Custom workflow runs over the last 30 days.",
  aiOpsAutomationsEmpty:
    "No workflow runs yet. Create a custom workflow in Automations.",
  aiOpsRunsToday: "Runs today",
  aiOpsRuns30d: "Runs (30 days)",
  aiOpsSuccessRate: "Success rate",
  aiOpsViewAutomations: "View Automations",
  aiOpsFailedRuns: (count: number) =>
    `${count} failed run${count === 1 ? "" : "s"} in the last 30 days`,
  aiOpsAgentRunsTitle: "CRM agent actions",
  aiOpsAgentRunsDescription:
    "AI Assistant CRM updates from inbound messages — contacts, tasks, deals, notes.",
  aiOpsAgentRunsEmpty:
    "No CRM agent runs yet. Enable AI on a channel and process customer messages.",
  aiOpsAgentRunsActions30d: "CRM actions (30 days)",
  aiOpsAgentRunsRouteIntent: "AI intent",
  aiOpsAgentRunsRouteKeyword: "Keyword",
  aiOpsAgentRunsRouteAssistant: "Assistant only",
  aiOpsAgentRunsIntentCount: (count: number) =>
    `${count} intent route${count === 1 ? "" : "s"}`,
  aiOpsAgentRunsKeywordCount: (count: number) =>
    `${count} keyword route${count === 1 ? "" : "s"}`,
  aiOpsAgentRunsAssistantCount: (count: number) =>
    `${count} assistant-only`,
  aiOpsAgentRunsNoActions: "No CRM fields changed",
  aiOpsAgentRunsFailed: "Failed",
  aiOpsAgentRunsAssistantOnly: "AI Agent",
  aiOpsAgentRunsViewContact: "View contact",
  aiOpsViewAiAssistant: "Open AI Agent",
  aiAgentSummaryTitle: "AI Agent output",
  aiAgentSummaryDescription:
    "Text and voice replies, contacts served, and call time.",
  aiAgentTextReplies: "AI text replies",
  aiAgentVoiceReplies: "Voice AI replies",
  aiAgentContactsServed: "Contacts served",
  aiAgentCallTime: "Call time",
  channelsTitle: "Channels",
  overviewTitle: "All channels",
  overviewDescription: "Combined metrics across every connected messaging channel.",
  channelNotConnected:
    "This channel is not connected yet. Connect it in Integrations to start collecting analytics.",
  goToIntegrations: "Connect channel",
  totalMessages: "Total messages",
  totalContacts: "Contacts",
  aiReplies: "AI replies",
  activeConversations: "Active conversations",
  aiPerformanceTitle: "AI performance",
  aiPerformanceDescription:
    "How often AI handles replies vs. when your team takes over.",
  aiResolutionRate: "AI reply rate",
  aiResolutionDescription: "Share of outbound replies sent by AI.",
  aiAssistantOnlyReplies: "Assistant-only replies",
  aiAssistantOnlyDescription:
    "AI replies without a matched specialized agent (profile-only handling).",
  aiDelegatedReplies: "Delegated agent replies",
  aiDelegatedDescription:
    "AI replies routed to a specialized agent for CRM actions or goal handling.",
  handoffRate: "Human reply rate",
  handoffDescription: "Outbound replies sent manually by your team.",
  timeSaved: "Estimated time saved",
  timeSavedDescription: "Rough minutes saved assuming 2 min per AI reply.",
  aiVsHuman: "AI vs human replies",
  aiVsHumanDescription: "Total AI-generated vs manual team messages.",
  leadSourceTitle: "Lead sources",
  leadSourceDescription: "Where contacts originated across messaging channels.",
  leadSourceEmpty: "No contacts yet. Connect a channel to start tracking sources.",
  responseTimeTitle: "Response time",
  responseTimeDescription:
    "Average first reply and resolution time across recent conversations.",
  avgFirstResponse: "Avg first response",
  avgResolution: "Avg resolution time",
  crmFunnelTitle: "Pipeline funnel",
  crmFunnelDescription: "Current distribution across pipeline stages.",
  newToQualified: "New → Qualified",
  qualifiedToWon: "Qualified → Won",
  aiCostTitle: "AI usage",
  aiCostDescription:
    "Platform AI replies included in your plan.",
  aiCostPlatformIncludedTitle: "Platform AI usage",
  aiCostPlatformIncludedDescription:
    "AI replies powered by OrzuX are included in your subscription.",
  aiCostMonth: "This month",
  aiCostPerReply: "Avg cost per reply",
  aiCostEmpty:
    "No AI usage logged yet. Metrics appear after your agent starts replying.",
  teamTitle: "Team analytics",
  teamDescription: "Human team replies and SLA compliance on first response.",
  teamReplies: "Team replies",
  slaCompliance: "SLA compliance",
  revenueTitle: "Revenue",
  revenueDescription: "Pipeline and won revenue from CRM deal values.",
  pipelineValue: "Open pipeline",
  wonRevenue: "Won revenue",
  sentimentTitle: "Customer sentiment",
  sentimentDescription: "AI-classified tone stored on each contact profile.",
  sentimentPositive: "Positive",
  sentimentNeutral: "Neutral",
  sentimentNegative: "Negative",
  sentimentUnknown: "Not analyzed",
  sentimentEmpty: "No sentiment data yet. Enable sentiment analysis in AI Agent.",
} as const;
