export const ANALYTICS_MESSAGES = {
  pageTitle: "Analytics",
  pageDescription:
    "Message volume, contacts, and AI performance for WhatsApp, Instagram, Telegram, and Website Forms.",
  channelsTitle: "Channels",
  overviewTitle: "All channels",
  overviewDescription: "Combined metrics across every connected messaging channel.",
  channelNotConnected:
    "This channel is not connected yet. Connect it in Integrations to start collecting analytics.",
  goToIntegrations: "Connect channel",
  totalMessages: "Total messages",
  totalContacts: "Contacts",
  aiReplies: "AI replies",
  activeConversations: "Active conversations",
  aiPerformanceTitle: "AI performance",
  aiPerformanceDescription:
    "How often AI handles replies vs. when your team takes over.",
  aiResolutionRate: "AI resolution rate",
  aiResolutionDescription: "Share of outbound replies sent by AI.",
  handoffRate: "Human handoff rate",
  handoffDescription: "Outbound replies sent manually by your team.",
  timeSaved: "Estimated time saved",
  timeSavedDescription: "Rough minutes saved assuming 2 min per AI reply.",
  aiVsHuman: "AI vs human replies",
  aiVsHumanDescription: "Total AI-generated vs manual team messages.",
  leadSourceTitle: "Lead source attribution",
  leadSourceDescription: "Where contacts originated across messaging channels.",
  leadSourceEmpty: "No contacts yet. Connect a channel to start tracking sources.",
  responseTimeTitle: "Response time",
  responseTimeDescription:
    "Average first reply and resolution time across recent conversations.",
  avgFirstResponse: "Avg first response",
  avgResolution: "Avg resolution time",
  crmFunnelTitle: "CRM funnel",
  crmFunnelDescription: "Pipeline distribution and stage conversion rates.",
  newToQualified: "New → Qualified",
  qualifiedToWon: "Qualified → Won",
  aiCostTitle: "AI cost tracking",
  aiCostDescription: "Estimated spend per AI reply based on provider token usage.",
  aiCostMonth: "This month",
  aiCostPerReply: "Avg per reply",
  aiCostEmpty: "No AI usage logged yet. Costs appear after the first AI reply.",
  assistantTitle: "AI Analytics Assistant",
  assistantDescription:
    "Ask natural-language questions about conversions, channels, and AI performance.",
  assistantPlaceholder: "e.g. Why did conversions drop this week?",
  assistantAsk: "Ask AI",
} as const;
