import {
  BotIcon,
  MessageSquareIcon,
  PercentIcon,
  UsersIcon,
} from "lucide-react";

import { ANALYTICS_CARD_LABELS } from "@/features/dashboard/constants";
import type { DashboardMetrics } from "@/types/dashboard.types";
import {
  formatConversionRate,
  formatMetricValue,
} from "@/utils/dashboard";

import { AnalyticsCard } from "./AnalyticsCard";

type AnalyticsCardsGridProps = {
  metrics: DashboardMetrics;
};

const CARD_CONFIG = [
  {
    key: "totalMessages" as const,
    label: ANALYTICS_CARD_LABELS.totalMessages,
    description: "All messages across your WhatsApp conversations.",
    icon: MessageSquareIcon,
    format: formatMetricValue,
  },
  {
    key: "uniqueContacts" as const,
    label: ANALYTICS_CARD_LABELS.uniqueContacts,
    description: "Distinct customers who have contacted your business.",
    icon: UsersIcon,
    format: formatMetricValue,
  },
  {
    key: "aiResponses" as const,
    label: ANALYTICS_CARD_LABELS.aiResponses,
    description: "Replies automatically generated by your AI assistant.",
    icon: BotIcon,
    format: formatMetricValue,
  },
  {
    key: "conversionRate" as const,
    label: ANALYTICS_CARD_LABELS.conversionRate,
    description: "Share of messages handled by AI responses.",
    icon: PercentIcon,
    format: formatConversionRate,
  },
];

export function AnalyticsCardsGrid({ metrics }: AnalyticsCardsGridProps) {
  return (
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {CARD_CONFIG.map((card) => (
        <AnalyticsCard
          key={card.key}
          title={card.label}
          value={card.format(metrics[card.key])}
          description={card.description}
          icon={card.icon}
        />
      ))}
    </div>
  );
}
