export const WEBSITE_CHAT_MESSAGES = {
  connectTitle: "Website Chat",
  connectDescription:
    "Add a live chat widget to your site. Visitor messages appear in Inbox instantly.",
  connectButton: "Enable Website Chat",
  connectSuccess: "Website Chat is live. Copy the embed code below.",
  noBusinessTitle: "Business profile required",
  noBusinessDescription: "Complete your business settings before enabling Website Chat.",
  notConfigured: "Set NEXT_PUBLIC_APP_URL to your HTTPS production URL.",
  widgetTokenLabel: "Widget ID",
  embedCodeLabel: "Embed code",
  embedHint: "Paste before the closing </body> tag on every page where chat should appear.",
  copySuccess: "Copied to clipboard",
  siteNameLabel: "Site name (optional)",
  siteUrlLabel: "Site URL (optional)",
  welcomeMessageLabel: "Welcome message",
  primaryColorLabel: "Brand color",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved",
  disconnect: "Disconnect",
  disconnectSuccess: "Website Chat disconnected",
  previewTitle: "Preview",
  previewDescription: "The widget opens in the bottom-right corner on your website.",
} as const;
