export const WEBSITE_CHAT_MESSAGES = {
  connectTitle: "Website Chat",
  connectDescription:
    "Add a live chat widget to your site. Visitor messages appear in Inbox instantly.",
  connectButton: "Enable Website Chat",
  connectSuccess: "Website Chat is live. Copy the embed code below.",
  noBusinessTitle: "Business profile required",
  noBusinessDescription: "Complete your business settings before enabling Website Chat.",
  notConfigured: "Set NEXT_PUBLIC_APP_URL to your HTTPS production URL.",
  widgetTokenLabel: "Widget ID",
  embedCodeLabel: "Embed code",
  embedHint: "Paste once before </body>. Includes your connection key.",
  connectionKeyLabel: "Connection key",
  connectionKeyHint:
    "Secret key embedded in the script. Regenerate if it was exposed.",
  connectedSiteLabel: "Connected site",
  connectedSiteHint: "Detected automatically after the first message from your site.",
  connectedSitePending: "Waiting for first message from your website…",
  newKeyTitle: "Save your connection key",
  newKeyDescription: "Shown once. Copy the embed code and key before leaving.",
  regenerateKey: "Regenerate connection key",
  regenerateConfirm:
    "Regenerating invalidates the old key. Update the embed code on your site.",
  copySuccess: "Copied to clipboard",
  siteNameLabel: "Site name (optional)",
  siteUrlLabel: "Site URL (optional)",
  welcomeMessageLabel: "Welcome message",
  primaryColorLabel: "Brand color",
  saveSettings: "Save settings",
  settingsSaved: "Settings saved",
  disconnect: "Disconnect",
  disconnectSuccess: "Website Chat disconnected",
  previewTitle: "Preview",
  previewDescription: "The widget opens in the bottom-right corner on your website.",
} as const;
