"""CapCut-style FFmpeg look library: transitions, grades, motion, text, stills."""

from __future__ import annotations

# Official xfade transition names (FFmpeg) — 36+ CapCut-like wipes/dissolves
TRANSITION_LIBRARY: list[str] = [
    "fade",
    "fadeblack",
    "fadewhite",
    "fadegrays",
    "dissolve",
    "pixelize",
    "distance",
    "radial",
    "hblur",
    "wipeleft",
    "wiperight",
    "wipeup",
    "wipedown",
    "wipetl",
    "wipetr",
    "wipebl",
    "wipebr",
    "slideleft",
    "slideright",
    "slideup",
    "slidedown",
    "smoothleft",
    "smoothright",
    "smoothup",
    "smoothdown",
    "circlecrop",
    "rectcrop",
    "circleopen",
    "circleclose",
    "vertopen",
    "vertclose",
    "horzopen",
    "horzclose",
    "diagtl",
    "diagtr",
    "diagbl",
    "diagbr",
    "hlslice",
    "hrslice",
    "vuslice",
    "vdslice",
    "squeezeh",
    "squeezev",
    "zoomin",
]

# Color / film grades (25+)
EFFECT_FILTERS: dict[str, str] = {
    "none": "",
    "cinematic": "eq=contrast=1.08:saturation=1.12:brightness=0.02,vignette=PI/5.5",
    "vivid": "eq=contrast=1.14:saturation=1.28:brightness=0.03",
    "soft": "eq=contrast=0.96:saturation=0.92:brightness=0.04:gamma=1.05",
    "noir": "hue=s=0,eq=contrast=1.2:brightness=-0.02",
    "punch": "eq=contrast=1.18:saturation=1.22:brightness=0.05",
    "vignette": "vignette=PI/4.5,eq=contrast=1.06:saturation=1.08",
    "warm": "eq=contrast=1.06:saturation=1.1:gamma_r=1.05:gamma_b=0.95,colorbalance=rs=0.06:gs=0.02:bs=-0.04",
    "cool": "eq=contrast=1.05:saturation=1.05:gamma_b=1.08:gamma_r=0.95,colorbalance=rs=-0.04:bs=0.06",
    "teal_orange": "colorbalance=rs=0.08:gs=-0.02:bs=-0.06:rm=0.04:bm=-0.05,eq=contrast=1.1:saturation=1.15",
    "vintage": "eq=contrast=0.95:saturation=0.75:brightness=0.03:gamma=1.08,vignette=PI/4,noise=alls=8:allf=t",
    "bleach": "eq=contrast=1.25:saturation=0.55:brightness=0.08",
    "neon": "eq=contrast=1.2:saturation=1.45:brightness=0.04,unsharp=5:5:1.0:5:5:0.0",
    "pastel": "eq=contrast=0.92:saturation=0.85:brightness=0.06:gamma=1.1",
    "drama": "eq=contrast=1.22:saturation=0.95:brightness=-0.03,vignette=PI/4",
    "glow": "gblur=sigma=1.2,eq=contrast=1.05:saturation=1.12:brightness=0.04",
    "sharp": "unsharp=5:5:1.2:5:5:0.0,eq=contrast=1.08:saturation=1.05",
    "dream": "gblur=sigma=2.5,eq=saturation=1.15:brightness=0.05:gamma=1.08",
    "chrome": "eq=contrast=1.15:saturation=0.4:brightness=0.02",
    "sunset": "eq=gamma_r=1.12:gamma_g=1.02:gamma_b=0.88:saturation=1.18:contrast=1.06",
    "arctic": "eq=gamma_b=1.15:gamma_r=0.9:saturation=0.85:contrast=1.08:brightness=0.03",
    "ember": "eq=gamma_r=1.18:gamma_g=0.95:gamma_b=0.85:saturation=1.2:contrast=1.1",
    "matrix": "colorchannelmixer=rr=0.1:rg=0.7:rb=0.1:gr=0.05:gg=0.85:gb=0.1:br=0:bg=0.4:bb=0.2,eq=contrast=1.15",
    "retro_tv": "noise=alls=12:allf=t,eq=contrast=1.1:saturation=1.2,vignette=PI/3.5",
    "film_grain": "noise=alls=10:allf=t+u,eq=contrast=1.05:saturation=1.05",
    "high_key": "eq=brightness=0.12:contrast=0.92:saturation=1.05:gamma=1.12",
    "low_key": "eq=brightness=-0.08:contrast=1.2:saturation=0.9,vignette=PI/3.8",
    "sepia": "colorchannelmixer=.393:.769:.189:0:.349:.686:.168:0:.272:.534:.131,eq=contrast=1.05",
    "duo_pink": "colorchannelmixer=rr=0.9:rg=0.2:rb=0.3:gr=0.2:gg=0.5:gb=0.4:br=0.5:bg=0.2:bb=0.7,eq=contrast=1.08",
    "clarity": "unsharp=7:7:1.5:7:7:0.0,eq=contrast=1.1:saturation=1.08",
    "kodak": "eq=contrast=1.08:saturation=1.15:gamma_r=1.06:gamma_b=0.94,colorbalance=rs=0.05:bs=-0.03",
    "fuji": "eq=contrast=1.05:saturation=0.95:gamma_g=1.04,colorbalance=gs=0.04:rs=-0.02",
    "bleach_bypass": "eq=contrast=1.28:saturation=0.45:brightness=0.04,unsharp=5:5:0.8:5:5:0.0",
    "golden_hour": "eq=gamma_r=1.14:gamma_g=1.05:gamma_b=0.88:saturation=1.2:contrast=1.05,vignette=PI/5",
    "steel_blue": "eq=gamma_b=1.12:gamma_r=0.92:saturation=0.9:contrast=1.12,colorbalance=bs=0.05:rs=-0.04",
    "cross_process": "curves=vintage,eq=contrast=1.15:saturation=1.25",
    "night_mood": "eq=brightness=-0.1:contrast=1.18:saturation=0.75:gamma_b=1.1,vignette=PI/3.2",
    "pop_art": "eq=contrast=1.35:saturation=1.55:brightness=0.06",
    "soft_glow": "gblur=sigma=0.8,eq=contrast=1.04:saturation=1.1:brightness=0.05",
    "blockbuster": "colorbalance=rs=0.1:bs=-0.08:rm=0.05:bm=-0.06,eq=contrast=1.14:saturation=1.18",
    "moody_teal": "colorbalance=bs=0.08:rs=-0.05:gs=-0.02,eq=contrast=1.12:saturation=1.05:brightness=-0.02",
    "neon_pop": "eq=contrast=1.22:saturation=1.5:brightness=0.06,unsharp=5:5:1.0:5:5:0.0,vignette=PI/3.8",
    "warm_glow": "eq=contrast=1.1:saturation=1.25:brightness=0.06:gamma=1.05,colorbalance=rs=0.06:bs=-0.04,vignette=PI/5",
    "cold_steel": "eq=contrast=1.16:saturation=0.9:brightness=0.01:gamma_b=1.1,colorbalance=bs=0.06:rs=-0.04,vignette=PI/3.5",
    "pastel_dream": "eq=contrast=0.95:saturation=1.15:brightness=0.08:gamma=1.08,gblur=sigma=0.6",
    "noir_hard": "hue=s=0,eq=contrast=1.4:brightness=-0.02,vignette=PI/3,noise=alls=12:allf=t",
    "sunset_flare": "eq=gamma_r=1.16:gamma_g=1.02:gamma_b=0.86:saturation=1.32:contrast=1.1,vignette=PI/4",
    "soft_film": "eq=contrast=1.05:saturation=1.05:brightness=0.02:gamma=1.03,noise=alls=4:allf=t,vignette=PI/5.5",
    "punch_pop": "eq=contrast=1.26:saturation=1.42:brightness=0.05,unsharp=5:5:0.9:5:5:0.0,vignette=PI/4.5",
    "ice_crystal": "eq=contrast=1.12:saturation=0.8:brightness=0.04:gamma_b=1.14,colorbalance=bs=0.07,unsharp=5:5:0.7:5:5:0.0",
    "amber_rush": "eq=gamma_r=1.2:gamma_g=1.05:gamma_b=0.82:saturation=1.28:contrast=1.12,vignette=PI/4.2",
    "cyber_lime": "eq=contrast=1.22:saturation=1.35:brightness=0.03,colorchannelmixer=rr=0.85:gg=1.25:bb=0.7,vignette=PI/3.8",
    "rose_gold": "eq=contrast=1.1:saturation=1.18:brightness=0.04:gamma_r=1.1,colorbalance=rs=0.08:bs=-0.03,vignette=PI/5",
    "deep_ocean": "eq=contrast=1.14:saturation=0.95:brightness=-0.02:gamma_b=1.12,colorbalance=bs=0.08:rs=-0.05,vignette=PI/3.4",
    "paper_matte": "eq=contrast=0.98:saturation=0.88:brightness=0.05:gamma=1.06,noise=alls=5:allf=t",
    "vaporwave": "eq=contrast=1.12:saturation=1.35:brightness=0.04,colorbalance=rs=0.1:bs=0.12:gs=-0.04,vignette=PI/4",
    "comic_ink": "eq=contrast=1.4:saturation=0.35:brightness=0.02,unsharp=7:7:1.6:7:7:0.0",
    "desert_dust": "eq=gamma_r=1.16:gamma_g=1.08:gamma_b=0.86:saturation=1.15:contrast=1.08,noise=alls=7:allf=t,vignette=PI/4",
    "rainforest": "eq=contrast=1.1:saturation=1.2:gamma_g=1.1:gamma_b=0.95,colorbalance=gs=0.06:rs=-0.03,vignette=PI/4.5",
    "mono_blue": "hue=s=0.15,eq=contrast=1.18:saturation=0.7:gamma_b=1.2,colorbalance=bs=0.1",
    "heatwave": "eq=contrast=1.15:saturation=1.3:brightness=0.05:gamma_r=1.18,colorbalance=rs=0.1:bs=-0.06,vignette=PI/3.8",
    "silver_screen": "hue=s=0,eq=contrast=1.25:brightness=0.02,noise=alls=9:allf=t,vignette=PI/3.5",
    "candy_pop": "eq=contrast=1.2:saturation=1.55:brightness=0.06,unsharp=5:5:0.8:5:5:0.0",
    "ink_wash": "eq=contrast=0.95:saturation=0.55:brightness=0.06:gamma=1.1,gblur=sigma=0.5",
    "night_neon": "eq=contrast=1.24:saturation=1.4:brightness=-0.02:gamma_b=1.15,vignette=PI/3.2,unsharp=5:5:1.0:5:5:0.0",
    "crimson_rush": "eq=contrast=1.18:saturation=1.35:brightness=0.03:gamma_r=1.15,vignette=PI/4",
    "mint_fresh": "eq=contrast=1.06:saturation=1.12:gamma_g=1.1,colorbalance=gs=0.05",
    "lavender_haze": "eq=contrast=0.98:saturation=1.1:brightness=0.05,colorbalance=rs=0.04:bs=0.06,gblur=sigma=0.7",
    "graphite": "hue=s=0.2,eq=contrast=1.2:saturation=0.5:brightness=0.01",
    "honey_glaze": "eq=gamma_r=1.12:gamma_g=1.06:saturation=1.22:contrast=1.06,colorbalance=rs=0.07",
    "electric_blue": "eq=contrast=1.16:saturation=1.3:gamma_b=1.2,unsharp=5:5:0.8:5:5:0.0",
    "moss": "eq=contrast=1.08:saturation=0.9:gamma_g=1.12,colorbalance=gs=0.06:rs=-0.03",
    "sandstorm": "eq=contrast=1.1:saturation=1.05:brightness=0.04,noise=alls=11:allf=t,colorbalance=rs=0.08",
    "plasma": "eq=contrast=1.25:saturation=1.5:brightness=0.05,hue=h=15",
    "copper": "eq=contrast=1.12:saturation=1.15:gamma_r=1.1,colorbalance=rs=0.1:bs=-0.05,vignette=PI/4.5",
    "pearl": "eq=contrast=0.94:saturation=0.8:brightness=0.08:gamma=1.1",
    "obsidian": "eq=brightness=-0.12:contrast=1.3:saturation=0.7,vignette=PI/3",
    "sakura": "eq=contrast=1.05:saturation=1.15:brightness=0.05,colorbalance=rs=0.08:bs=0.02",
    "jade": "eq=contrast=1.1:saturation=1.18:gamma_g=1.12,colorbalance=gs=0.08",
    "cobalt": "eq=contrast=1.14:saturation=1.05:gamma_b=1.18,colorbalance=bs=0.08",
    "rust": "eq=contrast=1.15:saturation=1.1:gamma_r=1.2:gamma_b=0.85,sepia=0.15",
    "fog": "eq=contrast=0.9:saturation=0.7:brightness=0.06,gblur=sigma=1.4",
    "spark": "eq=contrast=1.2:saturation=1.35:brightness=0.06,unsharp=7:7:1.2:7:7:0.0",
    "velvet": "eq=contrast=1.08:saturation=1.05:brightness=-0.02,vignette=PI/3.5,colorbalance=rs=0.04",
    "aurora": "eq=contrast=1.1:saturation=1.25,colorbalance=gs=0.05:bs=0.08:rs=-0.03",
    "noir_blue": "hue=s=0.25,eq=contrast=1.28:saturation=0.6:gamma_b=1.15",
    "candy_crush": "eq=contrast=1.22:saturation=1.6:brightness=0.07",
    "smoke": "eq=contrast=1.05:saturation=0.65:brightness=0.02,gblur=sigma=0.9,noise=alls=6:allf=t",
    "laser": "eq=contrast=1.3:saturation=1.45:brightness=0.04,unsharp=5:5:1.4:5:5:0.0",
    "bronze": "eq=contrast=1.1:saturation=1.08:gamma_r=1.08,colorbalance=rs=0.09:bs=-0.04",
    "ice_blue": "eq=contrast=1.12:saturation=0.85:brightness=0.05:gamma_b=1.16",
    "mango": "eq=contrast=1.08:saturation=1.3:gamma_r=1.14:gamma_g=1.05,colorbalance=rs=0.08",
    "plum": "eq=contrast=1.12:saturation=1.15,colorbalance=rs=0.06:bs=0.08",
    "slate": "eq=contrast=1.1:saturation=0.75:brightness=0.01,colorbalance=bs=0.03",
    "flare_warm": "eq=contrast=1.08:saturation=1.28:brightness=0.06:gamma_r=1.16,vignette=PI/4",
    "bleach_soft": "eq=contrast=1.15:saturation=0.65:brightness=0.06",
    "cinema_teal": "colorbalance=bs=0.1:rs=-0.06,eq=contrast=1.16:saturation=1.1:brightness=-0.01",
    "punch_red": "eq=contrast=1.24:saturation=1.4:gamma_r=1.12,vignette=PI/4.2",
    "soft_sepia": "eq=contrast=0.98:saturation=0.7:brightness=0.04,sepia=0.45",
    "neon_violet": "eq=contrast=1.2:saturation=1.4,colorbalance=rs=0.08:bs=0.12",
    "forest_dusk": "eq=contrast=1.12:saturation=0.95:brightness=-0.03:gamma_g=1.08,vignette=PI/3.6",
    "chrome_blue": "eq=contrast=1.18:saturation=0.45:gamma_b=1.1",
    "glow_amber": "eq=contrast=1.08:saturation=1.22:brightness=0.05,gblur=sigma=0.5,colorbalance=rs=0.07",
    "hard_contrast": "eq=contrast=1.4:saturation=1.05:brightness=0.02",
    "soft_matte": "eq=contrast=0.92:saturation=0.95:brightness=0.05:gamma=1.08",
    "urban_night": "eq=brightness=-0.08:contrast=1.22:saturation=0.85:gamma_b=1.1,vignette=PI/3.2",
    "tropical": "eq=contrast=1.1:saturation=1.35:brightness=0.04:gamma_g=1.08",
    "winter_fade": "eq=contrast=1.05:saturation=0.7:brightness=0.06:gamma_b=1.1,gblur=sigma=0.4",
    "ink_red": "eq=contrast=1.2:saturation=1.25:gamma_r=1.2,colorbalance=rs=0.12",
    "mint_noir": "hue=s=0.35,eq=contrast=1.25:saturation=0.55:gamma_g=1.1",
    "gold_rush": "eq=contrast=1.12:saturation=1.25:gamma_r=1.12:gamma_g=1.05,colorbalance=rs=0.1",
    "steel_noir": "hue=s=0.15,eq=contrast=1.3:saturation=0.4:gamma_b=1.05,vignette=PI/3.4",
    "bubblegum": "eq=contrast=1.15:saturation=1.5:brightness=0.06,colorbalance=rs=0.1:bs=0.05",
    "deep_purple": "eq=contrast=1.14:saturation=1.2:brightness=-0.02,colorbalance=rs=0.05:bs=0.1",
    "lime_crush": "eq=contrast=1.2:saturation=1.4,colorchannelmixer=rr=0.9:gg=1.3:bb=0.75",
    "ocean_mist": "eq=contrast=1.05:saturation=0.9:brightness=0.04:gamma_b=1.12,gblur=sigma=0.6",
    "ember_glow": "eq=contrast=1.14:saturation=1.28:gamma_r=1.18,vignette=PI/4,gblur=sigma=0.35",
}

# Ken Burns / camera moves
MOTION_PRESETS: list[dict[str, str]] = [
    {
        "id": "punch_in",
        "zoom": "min(zoom+0.0028,1.28)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.14:saturation=1.22:brightness=0.04",
    },
    {
        "id": "slow_push",
        "zoom": "min(zoom+0.0012,1.18)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.06:saturation=1.1:brightness=0.02",
    },
    {
        "id": "rise",
        "zoom": "min(zoom+0.0015,1.2)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.52-(ih/zoom/2)-on*0.35",
        "eq": "eq=contrast=1.08:saturation=1.12:brightness=0.025",
    },
    {
        "id": "drift_left",
        "zoom": "min(1.12+0.0004*on,1.2)",
        "x": "iw/2-(iw/zoom/2)-on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.07:saturation=1.1:brightness=0.02",
    },
    {
        "id": "drift_right",
        "zoom": "min(1.12+0.0004*on,1.2)",
        "x": "iw/2-(iw/zoom/2)+on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.07:saturation=1.1:brightness=0.02",
    },
    {
        "id": "snap_zoom",
        "zoom": "if(lt(on,8),1.35-on*0.02,min(zoom+0.0009,1.16))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.16:saturation=1.25:brightness=0.05",
    },
    {
        "id": "pull_out",
        "zoom": "max(1.28-0.0018*on,1.05)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.05:saturation=1.08",
    },
    {
        "id": "tilt_up",
        "zoom": "min(1.15+0.0003*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.62-(ih/zoom/2)-on*0.7",
        "eq": "eq=contrast=1.07:saturation=1.1",
    },
    {
        "id": "tilt_down",
        "zoom": "min(1.15+0.0003*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.38-(ih/zoom/2)+on*0.7",
        "eq": "eq=contrast=1.07:saturation=1.1",
    },
    {
        "id": "handheld",
        "zoom": "min(1.1+0.0002*on,1.16)",
        "x": "iw/2-(iw/zoom/2)+sin(on/7)*8",
        "y": "ih/2-(ih/zoom/2)+cos(on/9)*6",
        "eq": "eq=contrast=1.05:saturation=1.08",
    },
    {
        "id": "orbit",
        "zoom": "min(1.14+0.0005*on,1.22)",
        "x": "iw/2-(iw/zoom/2)+sin(on/18)*18",
        "y": "ih/2-(ih/zoom/2)+cos(on/18)*12",
        "eq": "eq=contrast=1.08:saturation=1.12",
    },
    {
        "id": "crash_zoom",
        "zoom": "if(lt(on,12),1.05+on*0.035,min(zoom+0.0008,1.35))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.2:saturation=1.25:brightness=0.04",
    },
    {
        "id": "whip_left",
        "zoom": "min(1.18+0.0005*on,1.28)",
        "x": "iw/2-(iw/zoom/2)-on*1.4",
        "y": "ih/2-(ih/zoom/2)+sin(on/11)*4",
        "eq": "eq=contrast=1.1:saturation=1.15:brightness=0.03",
    },
    {
        "id": "whip_right",
        "zoom": "min(1.18+0.0005*on,1.28)",
        "x": "iw/2-(iw/zoom/2)+on*1.4",
        "y": "ih/2-(ih/zoom/2)+sin(on/11)*4",
        "eq": "eq=contrast=1.1:saturation=1.15:brightness=0.03",
    },
    {
        "id": "breathe",
        "zoom": "1.12+0.04*sin(on/18)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.06:saturation=1.12:brightness=0.02",
    },
    {
        "id": "reveal_up",
        "zoom": "min(1.2+0.0006*on,1.3)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.7-(ih/zoom/2)-on*1.1",
        "eq": "eq=contrast=1.09:saturation=1.14:brightness=0.03",
    },
    {
        "id": "zoom_out_punch",
        "zoom": "if(lt(on,10),1.4-on*0.025,max(1.4-0.002*on,1.08))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.12:saturation=1.18:brightness=0.03",
    },
    {
        "id": "vertigo",
        "zoom": "min(1.05+0.003*on,1.4)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)+on*0.15",
        "eq": "eq=contrast=1.1:saturation=1.05",
    },
    {
        "id": "shake_hit",
        "zoom": "min(1.2+0.0002*on,1.25)",
        "x": "iw/2-(iw/zoom/2)+if(lt(on,15),sin(on*2.2)*14,sin(on/8)*3)",
        "y": "ih/2-(ih/zoom/2)+if(lt(on,15),cos(on*1.8)*10,cos(on/9)*2)",
        "eq": "eq=contrast=1.15:saturation=1.2:brightness=0.04",
    },
    {
        "id": "slide_diag",
        "zoom": "min(1.16+0.0004*on,1.24)",
        "x": "iw/2-(iw/zoom/2)+on*0.7",
        "y": "ih/2-(ih/zoom/2)-on*0.45",
        "eq": "eq=contrast=1.08:saturation=1.12",
    },
    {
        "id": "whip_zoom",
        "zoom": "if(lt(on,8),1.05+on*0.05,min(1.45+0.001*on,1.55))",
        "x": "iw/2-(iw/zoom/2)+if(lt(on,8),sin(on)*20,0)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.14:saturation=1.22:brightness=0.04",
    },
    {
        "id": "parallax_drift",
        "zoom": "min(1.18+0.0003*on,1.28)",
        "x": "iw/2-(iw/zoom/2)+sin(on/22)*28",
        "y": "ih/2-(ih/zoom/2)+cos(on/28)*18",
        "eq": "eq=contrast=1.08:saturation=1.15:brightness=0.02",
    },
    {
        "id": "snap_in",
        "zoom": "if(lt(on,6),1.55-on*0.08,min(1.12+0.0004*on,1.22))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.16:saturation=1.2:brightness=0.05",
    },
    {
        "id": "float_rise",
        "zoom": "min(1.1+0.0005*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)-on*0.9",
        "eq": "eq=contrast=1.05:saturation=1.1:brightness=0.03",
    },
    {
        "id": "orbit_soft",
        "zoom": "min(1.14+0.00035*on,1.26)",
        "x": "iw/2-(iw/zoom/2)+cos(on/16)*22",
        "y": "ih/2-(ih/zoom/2)+sin(on/16)*16",
        "eq": "eq=contrast=1.09:saturation=1.14",
    },
    {
        "id": "slow_dolly",
        "zoom": "min(1.06+0.0009*on,1.28)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)+on*0.12",
        "eq": "eq=contrast=1.07:saturation=1.08:brightness=0.01",
    },
    {
        "id": "impact_shake",
        "zoom": "min(1.22+0.0003*on,1.3)",
        "x": "iw/2-(iw/zoom/2)+if(lt(on,10),sin(on*3.1)*18,sin(on/10)*4)",
        "y": "ih/2-(ih/zoom/2)+if(lt(on,10),cos(on*2.6)*14,cos(on/11)*3)",
        "eq": "eq=contrast=1.18:saturation=1.22:brightness=0.05",
    },
    {
        "id": "peek_left",
        "zoom": "min(1.2+0.0004*on,1.28)",
        "x": "iw*0.62-(iw/zoom/2)-on*0.4",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.1:saturation=1.14",
    },
    {
        "id": "peek_right",
        "zoom": "min(1.2+0.0004*on,1.28)",
        "x": "iw*0.38-(iw/zoom/2)+on*0.4",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.1:saturation=1.14",
    },
    {
        "id": "rack_focus",
        "zoom": "min(1.08+0.002*on,1.32)",
        "x": "iw/2-(iw/zoom/2)+sin(on/40)*6",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.12:saturation=1.08:brightness=0.02",
    },
    {
        "id": "boom_down",
        "zoom": "min(1.14+0.0004*on,1.24)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.35-(ih/zoom/2)+on*1.0",
        "eq": "eq=contrast=1.08:saturation=1.12",
    },
    {
        "id": "glitch_jitter",
        "zoom": "min(1.18+0.0002*on,1.26)",
        "x": "iw/2-(iw/zoom/2)+if(lt(mod(on,12),3),sin(on*4)*22,sin(on/9)*3)",
        "y": "ih/2-(ih/zoom/2)+if(lt(mod(on,12),3),cos(on*3.5)*16,0)",
        "eq": "eq=contrast=1.2:saturation=1.25:brightness=0.04",
    },
    {
        "id": "slam_zoom",
        "zoom": "if(lt(on,5),1.02+on*0.08,min(1.5+0.0005*on,1.58))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.22:saturation=1.28:brightness=0.05",
    },
    {
        "id": "sway",
        "zoom": "1.14+0.03*sin(on/24)",
        "x": "iw/2-(iw/zoom/2)+sin(on/20)*16",
        "y": "ih/2-(ih/zoom/2)+cos(on/26)*10",
        "eq": "eq=contrast=1.06:saturation=1.1:brightness=0.02",
    },
    {
        "id": "dutch_roll",
        "zoom": "min(1.16+0.0004*on,1.26)",
        "x": "iw/2-(iw/zoom/2)+sin(on/14)*12",
        "y": "ih/2-(ih/zoom/2)+cos(on/11)*14",
        "eq": "eq=contrast=1.1:saturation=1.12",
    },
    {
        "id": "micro_push",
        "zoom": "min(1.04+0.0007*on,1.16)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.05:saturation=1.06:brightness=0.01",
    },
    {
        "id": "smash_cut_zoom",
        "zoom": "if(lt(on,4),1.6-on*0.12,min(1.18+0.0006*on,1.3))",
        "x": "iw/2-(iw/zoom/2)+if(lt(on,4),sin(on*5)*10,0)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.2:saturation=1.3:brightness=0.05",
    },

    {
        "id": "spin_in",
        "zoom": "min(1.05+0.004*on,1.35)",
        "x": "iw/2-(iw/zoom/2)+sin(on/10)*8",
        "y": "ih/2-(ih/zoom/2)+cos(on/10)*6",
        "eq": "eq=contrast=1.12:saturation=1.15",
    },
    {
        "id": "roll_left",
        "zoom": "min(1.14+0.0004*on,1.24)",
        "x": "iw/2-(iw/zoom/2)-on*0.9",
        "y": "ih/2-(ih/zoom/2)+sin(on/15)*8",
        "eq": "eq=contrast=1.1:saturation=1.12",
    },
    {
        "id": "roll_right",
        "zoom": "min(1.14+0.0004*on,1.24)",
        "x": "iw/2-(iw/zoom/2)+on*0.9",
        "y": "ih/2-(ih/zoom/2)+sin(on/15)*8",
        "eq": "eq=contrast=1.1:saturation=1.12",
    },
    {
        "id": "drop_in",
        "zoom": "if(lt(on,10),1.45-on*0.03,min(1.15+0.0005*on,1.25))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.35-(ih/zoom/2)+on*0.8",
        "eq": "eq=contrast=1.14:saturation=1.18",
    },
    {
        "id": "lift_out",
        "zoom": "max(1.3-0.002*on,1.06)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)-on*0.5",
        "eq": "eq=contrast=1.08:saturation=1.1",
    },
    {
        "id": "pulse_zoom",
        "zoom": "1.12+0.06*sin(on/10)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.12:saturation=1.2:brightness=0.03",
    },
    {
        "id": "side_sweep",
        "zoom": "min(1.18+0.0003*on,1.28)",
        "x": "iw/2-(iw/zoom/2)+on*1.1",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.1:saturation=1.14",
    },
    {
        "id": "corner_crawl",
        "zoom": "min(1.2+0.0004*on,1.3)",
        "x": "iw*0.55-(iw/zoom/2)-on*0.35",
        "y": "ih*0.55-(ih/zoom/2)-on*0.25",
        "eq": "eq=contrast=1.09:saturation=1.1",
    },
    {
        "id": "hard_punch",
        "zoom": "if(lt(on,6),1.02+on*0.07,min(1.4+0.0004*on,1.48))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.22:saturation=1.28:brightness=0.05",
    },
    {
        "id": "soft_drift",
        "zoom": "min(1.08+0.0005*on,1.18)",
        "x": "iw/2-(iw/zoom/2)+sin(on/30)*20",
        "y": "ih/2-(ih/zoom/2)+cos(on/34)*14",
        "eq": "eq=contrast=1.05:saturation=1.08",
    },
    {
        "id": "kick_zoom",
        "zoom": "if(lt(on,7),1.5-on*0.06,min(1.16+0.0005*on,1.26))",
        "x": "iw/2-(iw/zoom/2)+if(lt(on,7),sin(on)*12,0)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.18:saturation=1.22",
    },
    {
        "id": "hover",
        "zoom": "1.1+0.025*sin(on/22)",
        "x": "iw/2-(iw/zoom/2)+sin(on/40)*6",
        "y": "ih/2-(ih/zoom/2)+cos(on/38)*6",
        "eq": "eq=contrast=1.06:saturation=1.1",
    },
    {
        "id": "dive",
        "zoom": "min(1.08+0.0025*on,1.4)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.4-(ih/zoom/2)+on*0.9",
        "eq": "eq=contrast=1.12:saturation=1.1",
    },
    {
        "id": "rise_spin",
        "zoom": "min(1.12+0.0006*on,1.28)",
        "x": "iw/2-(iw/zoom/2)+sin(on/12)*14",
        "y": "ih/2-(ih/zoom/2)-on*0.7",
        "eq": "eq=contrast=1.1:saturation=1.14",
    },
    {
        "id": "jitter_push",
        "zoom": "min(1.15+0.0008*on,1.3)",
        "x": "iw/2-(iw/zoom/2)+sin(on*1.6)*5",
        "y": "ih/2-(ih/zoom/2)+cos(on*1.4)*4",
        "eq": "eq=contrast=1.14:saturation=1.16",
    },
    {
        "id": "wide_pull",
        "zoom": "max(1.35-0.0015*on,1.05)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.05:saturation=1.05",
    },
    {
        "id": "snap_left",
        "zoom": "min(1.2+0.0003*on,1.28)",
        "x": "iw*0.65-(iw/zoom/2)-on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.12:saturation=1.15",
    },
    {
        "id": "snap_right",
        "zoom": "min(1.2+0.0003*on,1.28)",
        "x": "iw*0.35-(iw/zoom/2)+on*0.55",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.12:saturation=1.15",
    },
    {
        "id": "boom_up",
        "zoom": "min(1.16+0.0005*on,1.28)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.65-(ih/zoom/2)-on*1.05",
        "eq": "eq=contrast=1.1:saturation=1.12",
    },
    {
        "id": "crash_down",
        "zoom": "min(1.1+0.0012*on,1.32)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih*0.3-(ih/zoom/2)+on*1.1",
        "eq": "eq=contrast=1.16:saturation=1.2",
    },
    {
        "id": "twist_drift",
        "zoom": "min(1.14+0.0004*on,1.26)",
        "x": "iw/2-(iw/zoom/2)+sin(on/9)*18",
        "y": "ih/2-(ih/zoom/2)+cos(on/13)*12",
        "eq": "eq=contrast=1.09:saturation=1.13",
    },
    {
        "id": "stomp_zoom",
        "zoom": "if(lt(on,5),1.65-on*0.1,min(1.2+0.0004*on,1.3))",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.2:saturation=1.25:brightness=0.04",
    },
    {
        "id": "glide_diag",
        "zoom": "min(1.15+0.0005*on,1.27)",
        "x": "iw/2-(iw/zoom/2)+on*0.6",
        "y": "ih/2-(ih/zoom/2)-on*0.55",
        "eq": "eq=contrast=1.08:saturation=1.1",
    },
    {
        "id": "focus_pull",
        "zoom": "min(1.06+0.0022*on,1.34)",
        "x": "iw/2-(iw/zoom/2)+sin(on/50)*4",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.1:saturation=1.05",
    },
    {
        "id": "shake_roll",
        "zoom": "min(1.18+0.0002*on,1.26)",
        "x": "iw/2-(iw/zoom/2)+sin(on*2)*10",
        "y": "ih/2-(ih/zoom/2)+cos(on*1.7)*8",
        "eq": "eq=contrast=1.15:saturation=1.18",
    },
    {
        "id": "pop_breathe",
        "zoom": "1.14+0.05*sin(on/14)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.1:saturation=1.18:brightness=0.03",
    },
    {
        "id": "laser_track",
        "zoom": "min(1.22+0.0005*on,1.34)",
        "x": "iw/2-(iw/zoom/2)+on*0.3",
        "y": "ih/2-(ih/zoom/2)-sin(on/8)*6",
        "eq": "eq=contrast=1.16:saturation=1.22",
    },
    {
        "id": "anchor_push",
        "zoom": "min(1.05+0.001*on,1.22)",
        "x": "iw/2-(iw/zoom/2)",
        "y": "ih/2-(ih/zoom/2)",
        "eq": "eq=contrast=1.07:saturation=1.08",
    },
    {
        "id": "whip_diag",
        "zoom": "min(1.2+0.0006*on,1.32)",
        "x": "iw/2-(iw/zoom/2)+on*1.2",
        "y": "ih/2-(ih/zoom/2)+on*0.4",
        "eq": "eq=contrast=1.14:saturation=1.2",
    },
    {
        "id": "soft_orbit",
        "zoom": "min(1.12+0.00035*on,1.24)",
        "x": "iw/2-(iw/zoom/2)+cos(on/20)*20",
        "y": "ih/2-(ih/zoom/2)+sin(on/20)*14",
        "eq": "eq=contrast=1.07:saturation=1.1",
    },
]

# Editing pace profiles for AI montage
MONTAGE_PACE: dict[str, dict[str, float | str]] = {
    "viral": {
        "overlap": 0.68,
        "hook_ratio": 0.09,
        "hook_min": 1.8,
        "hook_max": 2.5,
        "flash_bias": 0.7,
        "speed_body": 1.08,
    },
    "fast": {
        "overlap": 0.62,
        "hook_ratio": 0.10,
        "hook_min": 2.0,
        "hook_max": 2.7,
        "flash_bias": 0.55,
        "speed_body": 1.05,
    },
    "medium": {
        "overlap": 0.55,
        "hook_ratio": 0.12,
        "hook_min": 2.4,
        "hook_max": 3.0,
        "flash_bias": 0.25,
        "speed_body": 1.0,
    },
    "cinematic": {
        "overlap": 0.40,
        "hook_ratio": 0.14,
        "hook_min": 2.8,
        "hook_max": 3.6,
        "flash_bias": 0.08,
        "speed_body": 0.96,
    },
}

FLASH_TRANSITION_POOL = (
    "fadewhite",
    "fadeblack",
    "radial",
    "zoomin",
    "circleopen",
    "circleclose",
    "distance",
    "hblur",
    "pixelize",
    "squeezeh",
    "squeezev",
    "diagtl",
    "diagbr",
    "hlslice",
    "hrslice",
)

# ASS subtitle / title looks (PrimaryColour is &HAABBGGRR)
SUBTITLE_STYLES: dict[str, dict[str, str]] = {
    "classic": {
        "name": "Classic",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "karaoke_gold": {
        "name": "Karaoke Gold",
        "font": "Arial Black",
        "size": "82",
        "primary": "&H0000E5FF",
        "outline": "&H00000000",
        "outline_w": "7",
        "shadow": "0",
        "bold": "-1",
    },
    "box_white": {
        "name": "Box White",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&H99000000",
    },
    "neon_pink": {
        "name": "Neon Pink",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FF66FF",
        "outline": "&H00FF00AA",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "minimal": {
        "name": "Minimal",
        "font": "Arial",
        "size": "64",
        "primary": "&H00F0F0F0",
        "outline": "&H66000000",
        "outline_w": "2",
        "shadow": "0",
        "bold": "0",
    },
    "impact": {
        "name": "Impact",
        "font": "Impact",
        "size": "90",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "8",
        "shadow": "0",
        "bold": "-1",
    },
    "soft_shadow": {
        "name": "Soft Shadow",
        "font": "Arial",
        "size": "74",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "3",
        "shadow": "4",
        "bold": "-1",
    },
    "yellow_pop": {
        "name": "Yellow Pop",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H0000FFFF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "lower_third": {
        "name": "Lower Third",
        "font": "Arial",
        "size": "58",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HC0000000",
        "align": "2",
    },
    "hook_banner": {
        "name": "Hook Banner",
        "font": "Arial Black",
        "size": "92",
        "primary": "&H0000E5FF",
        "outline": "&H00000000",
        "outline_w": "8",
        "shadow": "0",
        "bold": "-1",
    },
    "cyan_glow": {
        "name": "Cyan Glow",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FFE066",
        "outline": "&H00FFAA00",
        "outline_w": "3",
        "shadow": "3",
        "bold": "-1",
    },
    "fire_orange": {
        "name": "Fire Orange",
        "font": "Impact",
        "size": "86",
        "primary": "&H0000A5FF",
        "outline": "&H0000288B",
        "outline_w": "6",
        "shadow": "2",
        "bold": "-1",
    },
    "lime_pulse": {
        "name": "Lime Pulse",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H0000FF99",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "comic_pop": {
        "name": "Comic Pop",
        "font": "Comic Sans MS",
        "size": "76",
        "primary": "&H00FFFFFF",
        "outline": "&H000000FF",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "glass_frost": {
        "name": "Glass Frost",
        "font": "Arial",
        "size": "68",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HAA1A1A2E",
    },
    "serif_clean": {
        "name": "Serif Clean",
        "font": "Georgia",
        "size": "70",
        "primary": "&H00F8F8F8",
        "outline": "&H66000000",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
    },
    "stack_outline": {
        "name": "Stack Outline",
        "font": "Arial Black",
        "size": "84",
        "primary": "&H00000000",
        "outline": "&H00FFFFFF",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "typewriter": {
        "name": "Typewriter",
        "font": "Courier New",
        "size": "64",
        "primary": "&H00E8E8E8",
        "outline": "&H00000000",
        "outline_w": "3",
        "shadow": "0",
        "bold": "0",
    },
    "viral_white": {
        "name": "Viral White",
        "font": "Arial Black",
        "size": "86",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "9",
        "shadow": "0",
        "bold": "-1",
    },
    "duotone_sub": {
        "name": "Duotone Sub",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFCC66",
        "outline": "&H00AA4400",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "neon_cyan": {
        "name": "Neon Cyan",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FFE060",
        "outline": "&H00FF0080",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "soft_white": {
        "name": "Soft White",
        "font": "Arial",
        "size": "68",
        "primary": "&H00FFFFFF",
        "outline": "&H00404040",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
        "back": "&H60000000",
        "border_style": "3",
    },
    "mint_clean": {
        "name": "Mint Clean",
        "font": "Arial",
        "size": "70",
        "primary": "&H00C8FFD0",
        "outline": "&H00204030",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "purple_wave": {
        "name": "Purple Wave",
        "font": "Arial Black",
        "size": "74",
        "primary": "&H00FFB0E0",
        "outline": "&H00600080",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "newspaper": {
        "name": "Newspaper",
        "font": "Georgia",
        "size": "64",
        "primary": "&H00F5F5F5",
        "outline": "&H00000000",
        "outline_w": "2",
        "shadow": "0",
        "bold": "0",
        "back": "&H90000000",
        "border_style": "3",
    },
    "street_graffiti": {
        "name": "Street Graffiti",
        "font": "Impact",
        "size": "84",
        "primary": "&H0000FF80",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "elegant_gold": {
        "name": "Elegant Gold",
        "font": "Georgia",
        "size": "72",
        "primary": "&H0000D4FF",
        "outline": "&H00201000",
        "outline_w": "3",
        "shadow": "2",
        "bold": "0",
    },
    "bold_white": {
        "name": "Bold White",
        "font": "Impact",
        "size": "88",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "7",
        "shadow": "0",
        "bold": "-1",
    },

    "hot_pink": {
        "name": "Hot Pink",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FF66CC",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "1",
        "bold": "-1",
    },
    "ice_white": {
        "name": "Ice White",
        "font": "Arial",
        "size": "74",
        "primary": "&H00FFFFFF",
        "outline": "&H00AA8866",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "blood_red": {
        "name": "Blood Red",
        "font": "Impact",
        "size": "84",
        "primary": "&H000000FF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "sky_blue": {
        "name": "Sky Blue",
        "font": "Arial Black",
        "size": "76",
        "primary": "&H00FFCC66",
        "outline": "&H00402000",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "lemon_zap": {
        "name": "Lemon Zap",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H0000FFFF",
        "outline": "&H00004080",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "orange_blast": {
        "name": "Orange Blast",
        "font": "Impact",
        "size": "82",
        "primary": "&H000080FF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "violet_neon": {
        "name": "Violet Neon",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FF66FF",
        "outline": "&H008000FF",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "emerald": {
        "name": "Emerald",
        "font": "Arial Black",
        "size": "76",
        "primary": "&H0080FF80",
        "outline": "&H00204020",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "sand_gold": {
        "name": "Sand Gold",
        "font": "Georgia",
        "size": "70",
        "primary": "&H00AADDFF",
        "outline": "&H00201000",
        "outline_w": "3",
        "shadow": "1",
        "bold": "0",
    },
    "ink_black": {
        "name": "Ink Black",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00000000",
        "outline": "&H00FFFFFF",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "cloud_soft": {
        "name": "Cloud Soft",
        "font": "Arial",
        "size": "68",
        "primary": "&H00FFFFFF",
        "outline": "&H00404040",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
        "border_style": "3",
        "back": "&H70000000",
    },
    "ticker": {
        "name": "Ticker",
        "font": "Arial",
        "size": "58",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HC0000000",
        "align": "2",
    },
    "poster": {
        "name": "Poster",
        "font": "Impact",
        "size": "92",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "9",
        "shadow": "0",
        "bold": "-1",
    },
    "outline_cyan": {
        "name": "Outline Cyan",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00000000",
        "outline": "&H00FFE060",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "outline_gold": {
        "name": "Outline Gold",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00000000",
        "outline": "&H0000D4FF",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "bubble": {
        "name": "Bubble",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HAA2060A0",
    },
    "warning": {
        "name": "Warning",
        "font": "Impact",
        "size": "86",
        "primary": "&H0000FFFF",
        "outline": "&H00000000",
        "outline_w": "7",
        "shadow": "0",
        "bold": "-1",
    },
    "whisper": {
        "name": "Whisper",
        "font": "Georgia",
        "size": "62",
        "primary": "&H00E8E8E8",
        "outline": "&H66000000",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
    },
    "mega_hook": {
        "name": "Mega Hook",
        "font": "Arial Black",
        "size": "96",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "10",
        "shadow": "0",
        "bold": "-1",
    },
    "teal_pop": {
        "name": "Teal Pop",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00CCFF66",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "1",
        "bold": "-1",
    },
    "rose_soft": {
        "name": "Rose Soft",
        "font": "Arial",
        "size": "70",
        "primary": "&H00D0C0FF",
        "outline": "&H00402040",
        "outline_w": "3",
        "shadow": "1",
        "bold": "0",
    },
    "steel_caption": {
        "name": "Steel Caption",
        "font": "Arial",
        "size": "66",
        "primary": "&H00F0F0F0",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HA0283038",
    },
    "comic_yellow": {
        "name": "Comic Yellow",
        "font": "Comic Sans MS",
        "size": "76",
        "primary": "&H0000FFFF",
        "outline": "&H000000FF",
        "outline_w": "4",
        "shadow": "0",
        "bold": "-1",
    },
    "night_lime": {
        "name": "Night Lime",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H0000FF99",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "2",
        "bold": "-1",
    },
    "royal": {
        "name": "Royal",
        "font": "Georgia",
        "size": "72",
        "primary": "&H00FFD0A0",
        "outline": "&H00400020",
        "outline_w": "3",
        "shadow": "2",
        "bold": "0",
    },
    "pixel_block": {
        "name": "Pixel Block",
        "font": "Courier New",
        "size": "68",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "4",
        "shadow": "0",
        "bold": "-1",
    },
    "glow_white": {
        "name": "Glow White",
        "font": "Arial Black",
        "size": "82",
        "primary": "&H00FFFFFF",
        "outline": "&H00AAAAAA",
        "outline_w": "3",
        "shadow": "3",
        "bold": "-1",
    },
    "shadow_heavy": {
        "name": "Shadow Heavy",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "4",
        "shadow": "6",
        "bold": "-1",
    },
    "caption_bar": {
        "name": "Caption Bar",
        "font": "Arial",
        "size": "60",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HD0000000",
        "align": "2",
    },
    "duo_cyan": {
        "name": "Duo Cyan",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFE080",
        "outline": "&H00FF4080",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "magma": {
        "name": "Magma",
        "font": "Impact",
        "size": "84",
        "primary": "&H000055FF",
        "outline": "&H00000040",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "frost": {
        "name": "Frost",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFF8F0",
        "outline": "&H00806040",
        "outline_w": "3",
        "shadow": "1",
        "bold": "0",
    },
    "acid": {
        "name": "Acid",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H0000FF00",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "cinema_lower": {
        "name": "Cinema Lower",
        "font": "Georgia",
        "size": "58",
        "primary": "&H00F5F5F5",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "0",
        "border_style": "3",
        "back": "&HC0000000",
        "align": "2",
    },
    "ultra_bold": {
        "name": "Ultra Bold",
        "font": "Impact",
        "size": "94",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "8",
        "shadow": "0",
        "bold": "-1",
    },
    # --- Expansion pack: 37 additional distinct caption looks ---
    "crimson_pop": {
        "name": "Crimson Pop",
        "font": "Impact",
        "size": "84",
        "primary": "&H003C14DC",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "aqua_flash": {
        "name": "Aqua Flash",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FFE500",
        "outline": "&H00403000",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "sunset_glow": {
        "name": "Sunset Glow",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H004370FF",
        "outline": "&H00001840",
        "outline_w": "5",
        "shadow": "2",
        "bold": "-1",
    },
    "midnight_gold": {
        "name": "Midnight Gold",
        "font": "Georgia",
        "size": "72",
        "primary": "&H0060C8E8",
        "outline": "&H00001020",
        "outline_w": "3",
        "shadow": "2",
        "bold": "0",
    },
    "bubblegum": {
        "name": "Bubblegum",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HAACC66FF",
    },
    "forest_mint": {
        "name": "Forest Mint",
        "font": "Arial Black",
        "size": "74",
        "primary": "&H00A0E08C",
        "outline": "&H001A3010",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "steel_blue": {
        "name": "Steel Blue",
        "font": "Arial",
        "size": "70",
        "primary": "&H00D0A87F",
        "outline": "&H00000000",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "molten": {
        "name": "Molten",
        "font": "Impact",
        "size": "86",
        "primary": "&H002255FF",
        "outline": "&H00000820",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "paper_note": {
        "name": "Paper Note",
        "font": "Georgia",
        "size": "62",
        "primary": "&H001A1A1A",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "0",
        "border_style": "3",
        "back": "&HE6D8EFF5",
    },
    "holographic": {
        "name": "Holographic",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00EEFF66",
        "outline": "&H00AA00FF",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "amber_bold": {
        "name": "Amber Bold",
        "font": "Impact",
        "size": "84",
        "primary": "&H0000BFFF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "glacier": {
        "name": "Glacier",
        "font": "Arial",
        "size": "72",
        "primary": "&H00FFF6DF",
        "outline": "&H00A08055",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "graphite": {
        "name": "Graphite",
        "font": "Arial Black",
        "size": "76",
        "primary": "&H00D0CCC8",
        "outline": "&H00000000",
        "outline_w": "4",
        "shadow": "3",
        "bold": "-1",
    },
    "candy_red": {
        "name": "Candy Red",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H005533FF",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "1",
        "bold": "-1",
    },
    "lime_shock": {
        "name": "Lime Shock",
        "font": "Arial Black",
        "size": "82",
        "primary": "&H0000FFB6",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "deep_purple": {
        "name": "Deep Purple",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FF80B0",
        "outline": "&H00500030",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "sunrise": {
        "name": "Sunrise",
        "font": "Georgia",
        "size": "72",
        "primary": "&H0080D0FF",
        "outline": "&H00002040",
        "outline_w": "3",
        "shadow": "2",
        "bold": "0",
    },
    "mono_type": {
        "name": "Mono Type",
        "font": "Courier New",
        "size": "64",
        "primary": "&H00E8E8E8",
        "outline": "&H00000000",
        "outline_w": "3",
        "shadow": "0",
        "bold": "0",
    },
    "tv_caption": {
        "name": "TV Caption",
        "font": "Arial",
        "size": "58",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HD0000000",
        "align": "2",
    },
    "gold_bar": {
        "name": "Gold Bar",
        "font": "Arial",
        "size": "60",
        "primary": "&H004AD2FF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HC0000000",
        "align": "2",
    },
    "electric_blue": {
        "name": "Electric Blue",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FF9933",
        "outline": "&H00301000",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "peach_soft": {
        "name": "Peach Soft",
        "font": "Arial",
        "size": "70",
        "primary": "&H00A4CBFF",
        "outline": "&H000F2040",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
    },
    "jade": {
        "name": "Jade",
        "font": "Arial Black",
        "size": "76",
        "primary": "&H008CC800",
        "outline": "&H00000000",
        "outline_w": "4",
        "shadow": "1",
        "bold": "-1",
    },
    "ruby_glow": {
        "name": "Ruby Glow",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H006622FF",
        "outline": "&H00200050",
        "outline_w": "4",
        "shadow": "2",
        "bold": "-1",
    },
    "cobalt": {
        "name": "Cobalt",
        "font": "Impact",
        "size": "82",
        "primary": "&H00DD5522",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "0",
        "bold": "-1",
    },
    "tangerine": {
        "name": "Tangerine",
        "font": "Impact",
        "size": "82",
        "primary": "&H002295FF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "blush": {
        "name": "Blush",
        "font": "Arial",
        "size": "70",
        "primary": "&H00CCAAFF",
        "outline": "&H003A2040",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
    },
    "onyx": {
        "name": "Onyx",
        "font": "Arial Black",
        "size": "78",
        "primary": "&H00FFFFFF",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HCC000000",
    },
    "seafoam": {
        "name": "Seafoam",
        "font": "Arial",
        "size": "72",
        "primary": "&H00D8F09F",
        "outline": "&H00405020",
        "outline_w": "3",
        "shadow": "1",
        "bold": "-1",
    },
    "flare_yellow": {
        "name": "Flare Yellow",
        "font": "Impact",
        "size": "84",
        "primary": "&H0000F2FF",
        "outline": "&H00000000",
        "outline_w": "6",
        "shadow": "1",
        "bold": "-1",
    },
    "violet_pop": {
        "name": "Violet Pop",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00FF66C2",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "2",
        "bold": "-1",
    },
    "copper": {
        "name": "Copper",
        "font": "Georgia",
        "size": "72",
        "primary": "&H003878C8",
        "outline": "&H00051020",
        "outline_w": "3",
        "shadow": "2",
        "bold": "0",
    },
    "arctic": {
        "name": "Arctic",
        "font": "Arial Black",
        "size": "74",
        "primary": "&H00FFF6EA",
        "outline": "&H00A08860",
        "outline_w": "3",
        "shadow": "2",
        "bold": "-1",
    },
    "magenta_pop": {
        "name": "Magenta Pop",
        "font": "Arial Black",
        "size": "80",
        "primary": "&H00AA33FF",
        "outline": "&H00000000",
        "outline_w": "5",
        "shadow": "0",
        "bold": "-1",
    },
    "slate_caption": {
        "name": "Slate Caption",
        "font": "Arial",
        "size": "60",
        "primary": "&H00ECE6E0",
        "outline": "&H00000000",
        "outline_w": "0",
        "shadow": "0",
        "bold": "-1",
        "border_style": "3",
        "back": "&HA0383028",
        "align": "2",
    },
    "neon_lime": {
        "name": "Neon Lime",
        "font": "Arial Black",
        "size": "82",
        "primary": "&H0000FFA8",
        "outline": "&H00001500",
        "outline_w": "5",
        "shadow": "2",
        "bold": "-1",
    },
    "cream_serif": {
        "name": "Cream Serif",
        "font": "Georgia",
        "size": "70",
        "primary": "&H00D8F4FF",
        "outline": "&H00001E2A",
        "outline_w": "2",
        "shadow": "1",
        "bold": "0",
    },
}

# Legacy / UI aliases → canonical SUBTITLE_STYLES keys
_SUBTITLE_ALIASES: dict[str, str] = {
    "karaoke_bold": "karaoke_gold",
    "karaoke": "karaoke_gold",
    "gold": "karaoke_gold",
    "bold": "bold_white",
    "tiktok": "viral_white",
    "youtube": "classic",
    "banner": "hook_banner",
    "hook": "hook_banner",
    "cyan": "neon_cyan",
    "neon": "neon_pink",
    "clean": "soft_white",
    "fire": "fire_orange",
    "mint": "mint_clean",
    "purple": "purple_wave",
    "comic": "comic_pop",
    "serif": "serif_clean",
    "graffiti": "street_graffiti",
    "news": "newspaper",
    "elegant": "elegant_gold",
}


def normalize_subtitle_style(style_id: str | None) -> str:
    """Map UI / legacy ids to a key present in SUBTITLE_STYLES."""
    raw = (style_id or "classic").strip().lower().replace(" ", "_").replace("-", "_")
    if not raw:
        return "classic"
    mapped = _SUBTITLE_ALIASES.get(raw, raw)
    if mapped in SUBTITLE_STYLES:
        return mapped
    for key in SUBTITLE_STYLES:
        if key in mapped or mapped in key:
            return key
    return "classic"


# Training video_style → montage defaults (overridden by explicit training fields)
VIDEO_STYLE_MONTAGE: dict[str, dict[str, str | bool | list[str]]] = {
    "cinematic_mixer": {
        "visual_effect": "blockbuster",
        "preferred_transition": "dissolve",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["slow_push", "breathe", "slow_dolly", "orbit_soft", "float_rise"],
    },
    "fast_cuts": {
        "visual_effect": "punch",
        "preferred_transition": "zoomin",
        "montage_pace": "viral",
        "flash_cuts": True,
        "preferred_motions": ["crash_zoom", "snap_zoom", "whip_zoom", "impact_shake", "snap_in"],
    },
    "slow_zoom": {
        "visual_effect": "cinematic",
        "preferred_transition": "fade",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["slow_push", "slow_dolly", "rack_focus", "breathe"],
    },
    "karaoke_focus": {
        "visual_effect": "vivid",
        "preferred_transition": "fade",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["punch_in", "slow_push", "breathe", "orbit"],
    },
    "punch_hook": {
        "visual_effect": "punch_pop",
        "preferred_transition": "radial",
        "montage_pace": "fast",
        "flash_cuts": True,
        "preferred_motions": ["punch_in", "crash_zoom", "shake_hit", "snap_in"],
    },
    "smooth_glide": {
        "visual_effect": "soft",
        "preferred_transition": "smoothleft",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["drift_left", "drift_right", "parallax_drift", "orbit_soft"],
    },
    "gritty_handheld": {
        "visual_effect": "drama",
        "preferred_transition": "fadeblack",
        "montage_pace": "fast",
        "flash_cuts": True,
        "preferred_motions": ["handheld", "glitch_jitter", "shake_hit", "impact_shake"],
    },
    "luxury_slow": {
        "visual_effect": "golden_hour",
        "preferred_transition": "dissolve",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["breathe", "slow_dolly", "float_rise", "orbit_soft"],
    },
    "hype_edit": {
        "visual_effect": "pop_art",
        "preferred_transition": "circleopen",
        "montage_pace": "viral",
        "flash_cuts": True,
        "preferred_motions": ["whip_left", "whip_right", "crash_zoom", "glitch_jitter", "whip_zoom"],
    },
    "clean_minimal": {
        "visual_effect": "soft_film",
        "preferred_transition": "fade",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["slow_push", "rise", "tilt_up", "breathe"],
    },
    "boom_viral": {
        "visual_effect": "punch_pop",
        "preferred_transition": "zoomin",
        "montage_pace": "viral",
        "flash_cuts": True,
        "preferred_motions": ["slam_zoom", "smash_cut_zoom", "crash_zoom", "impact_shake", "whip_zoom"],
    },
    "documentary_cut": {
        "visual_effect": "soft_film",
        "preferred_transition": "dissolve",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["micro_push", "slow_dolly", "rack_focus", "breathe"],
    },
    "street_reel": {
        "visual_effect": "heatwave",
        "preferred_transition": "slideright",
        "montage_pace": "fast",
        "flash_cuts": True,
        "preferred_motions": ["handheld", "whip_left", "dutch_roll", "glitch_jitter"],
    },
    "soft_story": {
        "visual_effect": "pastel_dream",
        "preferred_transition": "smoothleft",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["sway", "float_rise", "orbit_soft", "breathe"],
    },
    "techno_flash": {
        "visual_effect": "night_neon",
        "preferred_transition": "pixelize",
        "montage_pace": "viral",
        "flash_cuts": True,
        "preferred_motions": ["glitch_jitter", "slam_zoom", "whip_zoom", "snap_in"],
    },
    "epic_trailer": {
        "visual_effect": "blockbuster",
        "preferred_transition": "fadeblack",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["slow_push", "crash_zoom", "impact_shake", "slow_dolly"],
    },
    "warm_vlog": {
        "visual_effect": "golden_hour",
        "preferred_transition": "smoothleft",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["handheld", "drift_left", "breathe", "sway"],
    },
    "product_showcase": {
        "visual_effect": "vivid",
        "preferred_transition": "smoothup",
        "montage_pace": "medium",
        "flash_cuts": False,
        "preferred_motions": ["orbit_soft", "slow_push", "rack_focus", "float_rise"],
    },
    "news_brief": {
        "visual_effect": "soft_film",
        "preferred_transition": "slideleft",
        "montage_pace": "fast",
        "flash_cuts": False,
        "preferred_motions": ["micro_push", "slow_dolly", "tilt_up", "rise"],
    },
    "retro_vhs": {
        "visual_effect": "heatwave",
        "preferred_transition": "pixelize",
        "montage_pace": "medium",
        "flash_cuts": True,
        "preferred_motions": ["glitch_jitter", "handheld", "dutch_roll", "shake_hit"],
    },
    "dreamy_aesthetic": {
        "visual_effect": "pastel_dream",
        "preferred_transition": "dissolve",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["float_rise", "sway", "orbit_soft", "breathe"],
    },
    "sport_energy": {
        "visual_effect": "punch",
        "preferred_transition": "zoomin",
        "montage_pace": "viral",
        "flash_cuts": True,
        "preferred_motions": ["crash_zoom", "impact_shake", "whip_zoom", "snap_zoom"],
    },
    "mystery_dark": {
        "visual_effect": "drama",
        "preferred_transition": "fadeblack",
        "montage_pace": "cinematic",
        "flash_cuts": False,
        "preferred_motions": ["slow_push", "rack_focus", "micro_push", "breathe"],
    },
}

VIDEO_STYLE_ALIASES: dict[str, str] = {
    "viral": "boom_viral",
    "cinema": "cinematic_mixer",
    "clean": "clean_minimal",
    "dark": "gritty_handheld",
    "hype": "hype_edit",
    "luxury": "luxury_slow",
    "boom": "boom_viral",
    "street": "street_reel",
    "techno": "techno_flash",
}


def resolve_training_montage(
    training: dict | None,
    *,
    script_data: dict | None = None,
    meta0: dict | None = None,
) -> dict[str, str | bool | None]:
    """Prefer AI Training montage fields, then video_style, then script/meta."""
    training = dict(training or {})
    # Fallback when DB columns not migrated yet — mirrored by /api/training
    prefs = training.get("music_prefs") or {}
    if isinstance(prefs, dict):
        look = prefs.get("montage_look")
        if isinstance(look, dict):
            for key in (
                "visual_effect",
                "preferred_transition",
                "montage_pace",
                "flash_cuts",
                "subtitle_style",
            ):
                if not training.get(key) and look.get(key) is not None:
                    training[key] = look[key]
    script_data = script_data or {}
    meta0 = meta0 or {}
    style_key = str(training.get("video_style") or "").strip().lower().replace(" ", "_")
    style_key = VIDEO_STYLE_ALIASES.get(style_key, style_key)
    from_style = VIDEO_STYLE_MONTAGE.get(style_key) or {}

    def pick_str(*keys: str, default: str = "") -> str:
        for src in (training, from_style, script_data, meta0):
            for k in keys:
                v = src.get(k)
                if v is None:
                    continue
                s = str(v).strip()
                if s:
                    return s
        return default

    def pick_bool(*keys: str, default: bool = False) -> bool:
        for src in (training, from_style, script_data, meta0):
            for k in keys:
                if k in src and src.get(k) is not None:
                    return bool(src.get(k))
        return default

    subtitle = normalize_subtitle_style(
        pick_str("subtitle_style", default="classic")
    )
    effect = pick_str("visual_effect", "effect", default="cinematic")
    if effect not in EFFECT_FILTERS:
        effect = "cinematic"
    transition = pick_str("preferred_transition", default="")
    if transition and transition not in TRANSITION_LIBRARY:
        transition = ""
    pace = pick_str("montage_pace", default="medium").lower()
    if pace not in MONTAGE_PACE:
        pace = "medium"
    flash = pick_bool("flash_cuts", default=False)

    preferred_motions: list[str] | None = None
    raw_motions = from_style.get("preferred_motions")
    if isinstance(raw_motions, list) and raw_motions:
        preferred_motions = [str(m) for m in raw_motions if m]

    return {
        "subtitle_style": subtitle,
        "visual_effect": effect,
        "preferred_transition": transition or None,
        "montage_pace": pace,
        "flash_cuts": flash,
        "preferred_motions": preferred_motions,
    }

# drawtext title cards / still overlays
TEXT_STYLES: dict[str, dict[str, str]] = {
    "bold_center": {
        "fontsize": "72",
        "fontcolor": "white",
        "borderw": "5",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "hook_top": {
        "fontsize": "64",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.18",
    },
    "caption_bottom": {
        "fontsize": "56",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.78",
    },
    "box_lower": {
        "fontsize": "52",
        "fontcolor": "white",
        "box": "1",
        "boxcolor": "black@0.55",
        "boxborderw": "16",
        "x": "(w-text_w)/2",
        "y": "h*0.72",
    },
    "tiny_credit": {
        "fontsize": "36",
        "fontcolor": "white@0.85",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.92",
    },
    "mega_title": {
        "fontsize": "96",
        "fontcolor": "white",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "slide_left_title": {
        "fontsize": "70",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w*0.08",
        "y": "(h-text_h)/2",
    },
    "slide_right_title": {
        "fontsize": "70",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w-text_w-w*0.08",
        "y": "(h-text_h)/2",
    },
    "kinetic_center": {
        "fontsize": "88",
        "fontcolor": "0x66FFE0",
        "borderw": "6",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.42",
    },
    "stamp_corner": {
        "fontsize": "48",
        "fontcolor": "0xFF66AA",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w*0.06",
        "y": "h*0.12",
    },
    "cta_bottom": {
        "fontsize": "54",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "box": "1",
        "boxcolor": "black@0.45",
        "boxborderw": "14",
        "x": "(w-text_w)/2",
        "y": "h*0.82",
    },
    "word_slam": {
        "fontsize": "102",
        "fontcolor": "white",
        "borderw": "9",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.36",
    },

    "center_gold": {
        "fontsize": "72",
        "fontcolor": "0xFFD400",
        "borderw": "5",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "top_banner": {
        "fontsize": "60",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.1",
    },
    "mid_left": {
        "fontsize": "64",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w*0.06",
        "y": "(h-text_h)/2",
    },
    "mid_right": {
        "fontsize": "64",
        "fontcolor": "0x66FFE0",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w-text_w-w*0.06",
        "y": "(h-text_h)/2",
    },
    "bottom_wide": {
        "fontsize": "58",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.85",
    },
    "hook_center": {
        "fontsize": "88",
        "fontcolor": "0xE8A54B",
        "borderw": "7",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.38",
    },
    "tiny_top": {
        "fontsize": "34",
        "fontcolor": "white@0.9",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.06",
    },
    "stamp_br": {
        "fontsize": "44",
        "fontcolor": "0xFF6688",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w-text_w-w*0.05",
        "y": "h*0.88",
    },
    "stamp_bl": {
        "fontsize": "44",
        "fontcolor": "0x88FFAA",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w*0.05",
        "y": "h*0.88",
    },
    "mega_top": {
        "fontsize": "100",
        "fontcolor": "white",
        "borderw": "9",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.2",
    },
    "soft_caption": {
        "fontsize": "50",
        "fontcolor": "white",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.8",
    },
    "boxed_center": {
        "fontsize": "56",
        "fontcolor": "white",
        "borderw": "0",
        "bordercolor": "black",
        "box": "1",
        "boxcolor": "black@0.55",
        "boxborderw": "14",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "kinetic_top": {
        "fontsize": "80",
        "fontcolor": "0x66FFE0",
        "borderw": "6",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.22",
    },
    "kinetic_low": {
        "fontsize": "80",
        "fontcolor": "0xFF88CC",
        "borderw": "6",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.7",
    },
    "side_stack_l": {
        "fontsize": "62",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w*0.05",
        "y": "h*0.35",
    },
    "side_stack_r": {
        "fontsize": "62",
        "fontcolor": "white",
        "borderw": "4",
        "bordercolor": "black",
        "x": "w-text_w-w*0.05",
        "y": "h*0.35",
    },
    "credit_right": {
        "fontsize": "32",
        "fontcolor": "white@0.8",
        "borderw": "2",
        "bordercolor": "black",
        "x": "w-text_w-w*0.04",
        "y": "h*0.94",
    },
    "credit_left": {
        "fontsize": "32",
        "fontcolor": "white@0.8",
        "borderw": "2",
        "bordercolor": "black",
        "x": "w*0.04",
        "y": "h*0.94",
    },
    "warn_center": {
        "fontsize": "76",
        "fontcolor": "0xFFCC00",
        "borderw": "6",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "cta_center": {
        "fontsize": "68",
        "fontcolor": "0xE8A54B",
        "borderw": "5",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.55",
    },
    "cta_top": {
        "fontsize": "60",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.14",
    },
    "word_top": {
        "fontsize": "96",
        "fontcolor": "white",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.28",
    },
    "word_low": {
        "fontsize": "96",
        "fontcolor": "white",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.62",
    },
    "outline_only": {
        "fontsize": "74",
        "fontcolor": "black",
        "borderw": "6",
        "bordercolor": "white",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "neon_mid": {
        "fontsize": "70",
        "fontcolor": "0xFF66FF",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.45",
    },
    "cyan_mid": {
        "fontsize": "70",
        "fontcolor": "0x66E0FF",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.45",
    },
    "lime_mid": {
        "fontsize": "70",
        "fontcolor": "0x99FF00",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.45",
    },
    "serif_center": {
        "fontsize": "66",
        "fontcolor": "0xF8F8F8",
        "borderw": "3",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "serif_bottom": {
        "fontsize": "54",
        "fontcolor": "0xF8F8F8",
        "borderw": "3",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.78",
    },
    "poster_center": {
        "fontsize": "110",
        "fontcolor": "white",
        "borderw": "10",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "(h-text_h)/2",
    },
    "thin_top": {
        "fontsize": "48",
        "fontcolor": "white",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.12",
    },
    "thin_bottom": {
        "fontsize": "48",
        "fontcolor": "white",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.86",
    },
    "box_top": {
        "fontsize": "52",
        "fontcolor": "white",
        "borderw": "0",
        "bordercolor": "black",
        "box": "1",
        "boxcolor": "black@0.55",
        "boxborderw": "14",
        "x": "(w-text_w)/2",
        "y": "h*0.16",
    },
    "box_mid": {
        "fontsize": "52",
        "fontcolor": "white",
        "borderw": "0",
        "bordercolor": "black",
        "box": "1",
        "boxcolor": "black@0.55",
        "boxborderw": "14",
        "x": "(w-text_w)/2",
        "y": "h*0.48",
    },
    "impact_mid": {
        "fontsize": "90",
        "fontcolor": "white",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.4",
    },
    "impact_low": {
        "fontsize": "90",
        "fontcolor": "0xFFA500",
        "borderw": "8",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.65",
    },
    "float_ul": {
        "fontsize": "50",
        "fontcolor": "white",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w*0.08",
        "y": "h*0.12",
    },
    "float_ur": {
        "fontsize": "50",
        "fontcolor": "white",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w-text_w-w*0.08",
        "y": "h*0.12",
    },
    "float_ll": {
        "fontsize": "50",
        "fontcolor": "white",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w*0.08",
        "y": "h*0.82",
    },
    "float_lr": {
        "fontsize": "50",
        "fontcolor": "white",
        "borderw": "3",
        "bordercolor": "black",
        "x": "w-text_w-w*0.08",
        "y": "h*0.82",
    },
    "chapter": {
        "fontsize": "58",
        "fontcolor": "0xE8A54B",
        "borderw": "4",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.3",
    },
    "subtitle_safe": {
        "fontsize": "46",
        "fontcolor": "white",
        "borderw": "3",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.82",
    },
    "brand_tag": {
        "fontsize": "40",
        "fontcolor": "0xE8A54B",
        "borderw": "2",
        "bordercolor": "black",
        "x": "(w-text_w)/2",
        "y": "h*0.9",
    },
}

FADE_BOOKENDS = ("none", "fade", "fadeblack", "fadewhite")


def effect_chain(effect_id: str) -> str:
    return EFFECT_FILTERS.get(effect_id or "none", "") or ""


def motion_by_id(motion_id: str) -> dict[str, str] | None:
    for m in MOTION_PRESETS:
        if m["id"] == motion_id:
            return m
    return None


def pace_profile(pace_id: str | None) -> dict[str, float | str]:
    key = (pace_id or "medium").strip().lower()
    return dict(MONTAGE_PACE.get(key) or MONTAGE_PACE["medium"])

def catalog_prompt_block() -> str:
    """Compact tool list for LLM system prompts (effects / subs / motions / text)."""
    effects = [k for k in EFFECT_FILTERS.keys() if k != "none"]
    motions = [m["id"] for m in MOTION_PRESETS]
    subs = list(SUBTITLE_STYLES.keys())
    texts = list(TEXT_STYLES.keys())
    frames = [k for k in VIDEO_FRAMES.keys()]
    return (
        "AVAILABLE TOOLS (pick only these ids):\n"
        f"- visual_effect ({len(effects)}): {', '.join(effects)}\n"
        f"- subtitle_style ({len(subs)}): {', '.join(subs)}\n"
        f"- video_frame ({len(frames)}): {', '.join(frames)}\n"
        f"- motion ({len(motions)}): {', '.join(motions)}\n"
        f"- text_style ({len(texts)}): {', '.join(texts)}\n"
        f"- preferred_transition: {', '.join(TRANSITION_LIBRARY)}\n"
        "- montage_pace: viral, fast, medium, cinematic\n"
    )


# ---------------------------------------------------------------------------
# Decorative video frames ("рамки") — an outer border / cinematic treatment
# drawn on top of the finished picture. `kind` drives both the web CSS preview
# and the ffmpeg render below, so previews match the exported video.
#   weight  = border/bar thickness as a fraction of output height
#   color   = 6-digit RGB hex (no #)
#   radius  = corner radius fraction (preview only; ffmpeg draws square)
# ---------------------------------------------------------------------------
VIDEO_FRAMES: dict[str, dict[str, object]] = {
    "frame_white": {"name": "White", "kind": "solid", "color": "FFFFFF", "weight": 0.014},
    "frame_white_bold": {"name": "White Bold", "kind": "solid", "color": "FFFFFF", "weight": 0.028},
    "frame_black": {"name": "Black", "kind": "solid", "color": "000000", "weight": 0.02},
    "frame_gold": {"name": "Gold", "kind": "solid", "color": "E8C15A", "weight": 0.016},
    "frame_gold_bold": {"name": "Gold Bold", "kind": "solid", "color": "E8C15A", "weight": 0.03},
    "frame_red": {"name": "Red", "kind": "solid", "color": "E23B3B", "weight": 0.02},
    "frame_cyan": {"name": "Cyan", "kind": "solid", "color": "00E5FF", "weight": 0.016},
    "frame_pink": {"name": "Pink", "kind": "solid", "color": "FF4FA3", "weight": 0.016},
    "frame_lime": {"name": "Lime", "kind": "solid", "color": "A8FF00", "weight": 0.016},
    "frame_purple": {"name": "Purple", "kind": "solid", "color": "9B5CFF", "weight": 0.016},
    "frame_orange": {"name": "Orange", "kind": "solid", "color": "FF7A1A", "weight": 0.016},
    "frame_teal": {"name": "Teal", "kind": "solid", "color": "14B8A6", "weight": 0.016},
    "frame_navy": {"name": "Navy", "kind": "solid", "color": "1E3A8A", "weight": 0.02},
    "frame_mint": {"name": "Mint", "kind": "solid", "color": "7CF0C8", "weight": 0.016},
    "frame_round_white": {"name": "Round White", "kind": "rounded", "color": "FFFFFF", "weight": 0.014, "radius": 0.06},
    "frame_round_black": {"name": "Round Black", "kind": "rounded", "color": "000000", "weight": 0.02, "radius": 0.06},
    "frame_round_gold": {"name": "Round Gold", "kind": "rounded", "color": "E8C15A", "weight": 0.016, "radius": 0.06},
    "frame_pill": {"name": "Pill", "kind": "rounded", "color": "FFFFFF", "weight": 0.012, "radius": 0.12},
    "frame_double_white": {"name": "Double White", "kind": "double", "color": "FFFFFF", "weight": 0.01},
    "frame_double_gold": {"name": "Double Gold", "kind": "double", "color": "E8C15A", "weight": 0.01},
    "frame_double_black": {"name": "Double Black", "kind": "double", "color": "000000", "weight": 0.012},
    "frame_dashed_white": {"name": "Dashed White", "kind": "dashed", "color": "FFFFFF", "weight": 0.014},
    "frame_dashed_black": {"name": "Dashed Black", "kind": "dashed", "color": "000000", "weight": 0.016},
    "frame_dotted_white": {"name": "Dotted White", "kind": "dotted", "color": "FFFFFF", "weight": 0.016},
    "frame_dotted_gold": {"name": "Dotted Gold", "kind": "dotted", "color": "E8C15A", "weight": 0.016},
    "frame_glow_cyan": {"name": "Glow Cyan", "kind": "glow", "color": "00E5FF", "weight": 0.014},
    "frame_glow_pink": {"name": "Glow Pink", "kind": "glow", "color": "FF4FA3", "weight": 0.014},
    "frame_glow_lime": {"name": "Glow Lime", "kind": "glow", "color": "A8FF00", "weight": 0.014},
    "frame_glow_purple": {"name": "Glow Purple", "kind": "glow", "color": "9B5CFF", "weight": 0.014},
    "frame_glow_gold": {"name": "Glow Gold", "kind": "glow", "color": "E8C15A", "weight": 0.014},
    "frame_vignette": {"name": "Vignette", "kind": "vignette", "color": "000000", "weight": 0.0},
    "frame_vignette_soft": {"name": "Vignette Soft", "kind": "vignette_soft", "color": "000000", "weight": 0.0},
    "frame_spotlight": {"name": "Spotlight", "kind": "vignette_soft", "color": "000000", "weight": 0.0},
    "frame_grunge": {"name": "Grunge", "kind": "vignette", "color": "000000", "weight": 0.0},
    "frame_cinematic": {"name": "Cinematic", "kind": "letterbox", "color": "000000", "weight": 0.11},
    "frame_cinematic_thin": {"name": "Cinematic Thin", "kind": "letterbox", "color": "000000", "weight": 0.06},
    "frame_film_gold": {"name": "Film Gold", "kind": "letterbox", "color": "16110A", "weight": 0.1},
    "frame_polaroid": {"name": "Polaroid", "kind": "polaroid", "color": "FFFFFF", "weight": 0.16},
    "frame_polaroid_black": {"name": "Polaroid Black", "kind": "polaroid", "color": "111111", "weight": 0.16},
}


def normalize_frame_style(frame_id: str | None) -> str | None:
    """Map a UI frame id to a canonical VIDEO_FRAMES key (or None for 'no frame')."""
    raw = (frame_id or "").strip().lower().replace(" ", "_").replace("-", "_")
    if not raw or raw in ("none", "off", "no_frame"):
        return None
    return raw if raw in VIDEO_FRAMES else None


def frame_filter(frame_id: str | None, w: int, h: int) -> str | None:
    """Build an ffmpeg -vf fragment that draws the decorative frame on top.

    Best-effort: rounded / dashed / dotted corners are approximated as solid
    borders of the same colour (ffmpeg cannot draw rounded/dashed rectangles),
    while vignette / letterbox / polaroid are reproduced faithfully.
    """
    key = normalize_frame_style(frame_id)
    if not key:
        return None
    spec = VIDEO_FRAMES.get(key) or {}
    kind = str(spec.get("kind") or "solid")
    color = str(spec.get("color") or "FFFFFF")
    weight = float(spec.get("weight") or 0.016)
    t = max(2, round(weight * h))

    def box(c: str, thick: int, alpha: float = 1.0) -> str:
        return f"drawbox=x=0:y=0:w=iw:h=ih:t={thick}:color=0x{c}@{alpha:.2f}"

    if kind == "vignette":
        return "vignette=angle=PI/3.6"
    if kind == "vignette_soft":
        return "vignette=angle=PI/4.5"
    if kind == "letterbox":
        bar = max(8, round(weight * h))
        return (
            f"drawbox=x=0:y=0:w=iw:h={bar}:t=fill:color=0x{color}@1.00,"
            f"drawbox=x=0:y=ih-{bar}:w=iw:h={bar}:t=fill:color=0x{color}@1.00"
        )
    if kind == "polaroid":
        bar = max(8, round(weight * h))
        border = max(2, round(0.012 * h))
        return (
            box(color, border)
            + f",drawbox=x=0:y=ih-{bar}:w=iw:h={bar}:t=fill:color=0x{color}@1.00"
        )
    if kind == "double":
        gap = max(2, t)
        off = t + gap
        return (
            box(color, t)
            + f",drawbox=x={off}:y={off}:w={max(2, w - 2 * off)}:h={max(2, h - 2 * off)}:t={t}:color=0x{color}@1.00"
        )
    if kind == "glow":
        return box(color, t + max(2, round(t * 1.6)), 0.30) + "," + box(color, t)
    # solid / rounded / dashed / dotted → solid border of same colour
    return box(color, t)

