ALTER TABLE public.ai_agents
  ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT 'gemini',
  ADD COLUMN IF NOT EXISTS model TEXT NOT NULL DEFAULT 'gemini-2.5-flash',
  ADD COLUMN IF NOT EXISTS language TEXT NOT NULL DEFAULT 'English';
