import {
  Building2Icon,
  CameraIcon,
  CarIcon,
  DumbbellIcon,
  Flower2Icon,
  GraduationCapIcon,
  HeartIcon,
  HomeIcon,
  HotelIcon,
  LaptopIcon,
  PawPrintIcon,
  ScaleIcon,
  ScissorsIcon,
  SparklesIcon,
  SprayCanIcon,
  StethoscopeIcon,
  TicketIcon,
  UtensilsCrossedIcon,
  type LucideIcon,
} from "lucide-react";

import type { BusinessBookingType } from "@/types/business-calendar-resource.types";

export const BUSINESS_TYPE_ICONS: Record<BusinessBookingType, LucideIcon> = {
  generic: Building2Icon,
  salon: SparklesIcon,
  barbershop: ScissorsIcon,
  clinic: StethoscopeIcon,
  restaurant: UtensilsCrossedIcon,
  hotel: HotelIcon,
  auto_service: CarIcon,
  spa: Flower2Icon,
  gym: DumbbellIcon,
  dentist: StethoscopeIcon,
  veterinary: PawPrintIcon,
  photography: CameraIcon,
  tutoring: GraduationCapIcon,
  legal: ScaleIcon,
  real_estate: HomeIcon,
  coworking: LaptopIcon,
  pet_grooming: PawPrintIcon,
  yoga_studio: HeartIcon,
  cleaning: SprayCanIcon,
  event_venue: TicketIcon,
};
